<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Modele;
use App\Models\Seeders;

class ModelesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $seeder = Modele::where('type',1)->count();

        //Check if the seeder exist in the DB
        if ($seeder==0) {
            $modeles =
            [
            /*larg= 500*/
				[
                    'type'    =>1 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 500,
                    'largeur'  =>500 ,
                    'prix'  =>410 ,
				],
				[
                    'type'    =>1 ,
                    'couleur'    => 1,
                    'hauteur'    =>600 ,
                    'largeur'  =>500 ,
                    'prix'  => 439,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    => 1,
                    'hauteur'    => 700,
                    'largeur'  =>500 ,
                    'prix'  => 449,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    => 1,
                    'hauteur'    => 800,
                    'largeur'  =>500 ,
                    'prix'  =>527 ,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    => 1,
                    'hauteur'    => 900,
                    'largeur'  =>500 ,
                    'prix'  => 549,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1000,
                    'largeur'  =>500 ,
                    'prix'  => 576,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    =>1 ,
                    'hauteur'    =>1100 ,
                    'largeur'  =>500 ,
                    'prix'  =>595 ,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1200,
                    'largeur'  =>500 ,
                    'prix'  => 621,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1300,
                    'largeur'  =>500 ,
                    'prix'  => 634,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1400,
                    'largeur'  =>500 ,
                    'prix'  => 666,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1500,
                    'largeur'  =>500 ,
                    'prix'  => 716,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1600,
                    'largeur'  =>500 ,
                    'prix'  => 751,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1700,
                    'largeur'  =>500 ,
                    'prix'  => 779,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1800,
                    'largeur'  =>500 ,
                    'prix'  =>806 ,
                ],
                /* couleur 2*/
				[
                    'type'    =>1 ,
                    'couleur'    =>2 ,
                    'hauteur'    => 500,
                    'largeur'  =>500 ,
                    'prix'  => 510,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    => 2,
                    'hauteur'    => 600,
                    'largeur'  =>500 ,
                    'prix'  => 534,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    =>2 ,
                    'hauteur'    => 700,
                    'largeur'  =>500 ,
                    'prix'  => 549,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    =>2 ,
                    'hauteur'    => 800,
                    'largeur'  =>500 ,
                    'prix'  => 634,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    => 2,
                    'hauteur'    => 900,
                    'largeur'  =>500 ,
                    'prix'  => 666,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    =>2 ,
                    'hauteur'    => 1000,
                    'largeur'  =>500 ,
                    'prix'  =>687 ,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    =>2 ,
                    'hauteur'    => 1100,
                    'largeur'  =>500 ,
                    'prix'  => 716,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    =>2 ,
                    'hauteur'    => 1200,
                    'largeur'  =>500 ,
                    'prix'  => 728,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    =>2 ,
                    'hauteur'    => 1300,
                    'largeur'  =>500 ,
                    'prix'  => 767,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    =>2 ,
                    'hauteur'    => 1400,
                    'largeur'  =>500 ,
                    'prix'  => 791,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    => 2,
                    'hauteur'    => 1500,
                    'largeur'  =>500 ,
                    'prix'  => 840,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    =>2 ,
                    'hauteur'    => 1600,
                    'largeur'  =>500 ,
                    'prix'  => 891,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    =>2 ,
                    'hauteur'    => 1700,
                    'largeur'  =>500 ,
                    'prix'  =>930 ,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    =>2 ,
                    'hauteur'    => 1800,
                    'largeur'  =>500 ,
                    'prix'  => 972,
                ],
                /* couleur 3*/
				[
                    'type'    =>1 ,
                    'couleur'    =>3 ,
                    'hauteur'    => 500,
                    'largeur'  =>500 ,
                    'prix'  => 550,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    =>3 ,
                    'hauteur'    => 600,
                    'largeur'  =>500 ,
                    'prix'  => 577,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    =>3 ,
                    'hauteur'    => 700,
                    'largeur'  =>500 ,
                    'prix'  => 621,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    =>3 ,
                    'hauteur'    => 800,
                    'largeur'  =>500 ,
                    'prix'  => 700,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    =>3 ,
                    'hauteur'    => 900,
                    'largeur'  =>500 ,
                    'prix'  => 728,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    =>3 ,
                    'hauteur'    => 1000,
                    'largeur'  =>500 ,
                    'prix'  => 767,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    =>3 ,
                    'hauteur'    => 1100,
                    'largeur'  =>500 ,
                    'prix'  => 806,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    =>3 ,
                    'hauteur'    => 1200,
                    'largeur'  =>500 ,
                    'prix'  => 833,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    =>3 ,
                    'hauteur'    => 1300,
                    'largeur'  =>500 ,
                    'prix'  => 857,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    =>3 ,
                    'hauteur'    => 1400,
                    'largeur'  =>500 ,
                    'prix'  => 891,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    =>3 ,
                    'hauteur'    => 1500,
                    'largeur'  =>500 ,
                    'prix'  => 974,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    =>3 ,
                    'hauteur'    => 1600,
                    'largeur'  =>500 ,
                    'prix'  => 996,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    =>3 ,
                    'hauteur'    => 1700,
                    'largeur'  =>500 ,
                    'prix'  => 1044,
                ],
				[
                    'type'    =>1 ,
                    'couleur'    =>3 ,
                    'hauteur'    => 1800,
                    'largeur'  =>500 ,
                    'prix'  => 1088,
                ],
            /*Larg= 600*/
            [
                'type'    =>1 ,
                'couleur'    =>1 ,
                'hauteur'    => 500,
                'largeur'  =>600 ,
                'prix'  => 439,
            ],
            [
                'type'    =>1 ,
                'couleur'    => 1,
                'hauteur'    =>600 ,
                'largeur'  =>600 ,
                'prix'  => 449,
            ],
            [
                'type'    =>1 ,
                'couleur'    => 1,
                'hauteur'    => 700,
                'largeur'  =>600 ,
                'prix'  => 478,
            ],
            [
                'type'    =>1 ,
                'couleur'    => 1,
                'hauteur'    => 800,
                'largeur'  =>600 ,
                'prix'  => 549,
            ],
            [
                'type'    =>1 ,
                'couleur'    => 1,
                'hauteur'    => 900,
                'largeur'  =>600 ,
                'prix'  => 576,
            ],
            [
                'type'    =>1 ,
                'couleur'    =>1 ,
                'hauteur'    => 1000,
                'largeur'  =>600 ,
                'prix'  => 595,
            ],
            [
                'type'    =>1 ,
                'couleur'    =>1 ,
                'hauteur'    =>1100 ,
                'largeur'  =>600 ,
                'prix'  => 621,
            ],
            [
                'type'    =>1 ,
                'couleur'    =>1 ,
                'hauteur'    => 1200,
                'largeur'  =>600 ,
                'prix'  => 634,
            ],
            [
                'type'    =>1 ,
                'couleur'    =>1 ,
                'hauteur'    => 1300,
                'largeur'  =>600 ,
                'prix'  => 680,
            ],
            [
                'type'    =>1 ,
                'couleur'    =>1 ,
                'hauteur'    => 1400,
                'largeur'  =>600 ,
                'prix'  => 700,
            ],
            [
                'type'    =>1 ,
                'couleur'    =>1 ,
                'hauteur'    => 1500,
                'largeur'  =>600 ,
                'prix'  => 767,
            ],
            [
                'type'    =>1 ,
                'couleur'    =>1 ,
                'hauteur'    => 1600,
                'largeur'  =>600 ,
                'prix'  =>791 ,
            ],
            [
                'type'    =>1 ,
                'couleur'    =>1 ,
                'hauteur'    => 1700,
                'largeur'  =>600 ,
                'prix'  => 813,
            ],
            [
                'type'    =>1 ,
                'couleur'    =>1 ,
                'hauteur'    => 1800,
                'largeur'  =>600 ,
                'prix'  => 840,
            ],
            /* couleur 2*/
            [
                'type'    =>1 ,
                'couleur'    =>2 ,
                'hauteur'    => 500,
                'largeur'  =>600 ,
                'prix'  => 534,
            ],
            [
                'type'    =>1 ,
                'couleur'    => 2,
                'hauteur'    => 600,
                'largeur'  =>600 ,
                'prix'  => 561,
            ],
            [
                'type'    =>1 ,
                'couleur'    =>2 ,
                'hauteur'    => 700,
                'largeur'  =>600 ,
                'prix'  => 576,
            ],
            [
                'type'    =>1 ,
                'couleur'    =>2 ,
                'hauteur'    => 800,
                'largeur'  =>600 ,
                'prix'  => 666,
            ],
            [
                'type'    =>1 ,
                'couleur'    => 2,
                'hauteur'    => 900,
                'largeur'  =>600 ,
                'prix'  => 687,
            ],
            [
                'type'    =>1 ,
                'couleur'    =>2 ,
                'hauteur'    => 1000,
                'largeur'  =>600 ,
                'prix'  => 716,
            ],
            [
                'type'    =>1 ,
                'couleur'    =>2 ,
                'hauteur'    => 1100,
                'largeur'  =>600 ,
                'prix'  => 751,
            ],
            [
                'type'    =>1 ,
                'couleur'    =>2 ,
                'hauteur'    => 1200,
                'largeur'  =>600 ,
                'prix'  => 767,
            ],
            [
                'type'    =>1 ,
                'couleur'    =>2 ,
                'hauteur'    => 1300,
                'largeur'  =>600 ,
                'prix'  => 806,
            ],
            [
                'type'    =>1 ,
                'couleur'    =>2 ,
                'hauteur'    => 1400,
                'largeur'  =>600 ,
                'prix'  => 833,
            ],
            [
                'type'    =>1 ,
                'couleur'    => 2,
                'hauteur'    => 1500,
                'largeur'  =>600 ,
                'prix'  => 906,
            ],
            [
                'type'    =>1 ,
                'couleur'    =>2 ,
                'hauteur'    => 1600,
                'largeur'  =>600 ,
                'prix'  => 930,
            ],
            [
                'type'    =>1 ,
                'couleur'    =>2 ,
                'hauteur'    => 1700,
                'largeur'  =>600 ,
                'prix'  => 957,
            ],
            [
                'type'    =>1 ,
                'couleur'    =>2 ,
                'hauteur'    => 1800,
                'largeur'  =>600 ,
                'prix'  => 989,
            ],
            /* couleur 3*/
            [
                'type'    =>1 ,
                'couleur'    =>3 ,
                'hauteur'    => 500,
                'largeur'  =>600 ,
                'prix'  => 577,
            ],
            [
                'type'    =>1 ,
                'couleur'    =>3 ,
                'hauteur'    => 600,
                'largeur'  =>600 ,
                'prix'  => 621,
            ],
            [
                'type'    =>1 ,
                'couleur'    =>3 ,
                'hauteur'    => 700,
                'largeur'  =>600 ,
                'prix'  => 653,
            ],
            [
                'type'    =>1 ,
                'couleur'    =>3 ,
                'hauteur'    => 800,
                'largeur'  =>600 ,
                'prix'  => 728,
            ],
            [
                'type'    =>1 ,
                'couleur'    =>3 ,
                'hauteur'    => 900,
                'largeur'  =>600 ,
                'prix'  => 767,
            ],
            [
                'type'    =>1 ,
                'couleur'    =>3 ,
                'hauteur'    => 1000,
                'largeur'  =>600 ,
                'prix'  => 806,
            ],
            [
                'type'    =>1 ,
                'couleur'    =>3 ,
                'hauteur'    => 1100,
                'largeur'  =>600 ,
                'prix'  => 833,
            ],
            [
                'type'    =>1 ,
                'couleur'    =>3 ,
                'hauteur'    => 1200,
                'largeur'  =>600 ,
                'prix'  => 857,
            ],
            [
                'type'    =>1 ,
                'couleur'    =>3 ,
                'hauteur'    => 1300,
                'largeur'  =>600 ,
                'prix'  => 906,
            ],
            [
                'type'    =>1 ,
                'couleur'    =>3 ,
                'hauteur'    => 1400,
                'largeur'  =>600 ,
                'prix'  => 938,
            ],
            [
                'type'    =>1 ,
                'couleur'    =>3 ,
                'hauteur'    => 1500,
                'largeur'  =>600 ,
                'prix'  => 1029,
            ],
            [
                'type'    =>1 ,
                'couleur'    =>3 ,
                'hauteur'    => 1600,
                'largeur'  =>600 ,
                'prix'  => 1057,
            ],
            [
                'type'    =>1 ,
                'couleur'    =>3 ,
                'hauteur'    => 1700,
                'largeur'  =>600 ,
                'prix'  => 1098,
            ],
            [
                'type'    =>1 ,
                'couleur'    =>3 ,
                'hauteur'    => 1800,
                'largeur'  =>600 ,
                'prix'  => 1144,
            ],
        /*Larg=700*/
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>700 ,
            'prix'  => 449,
        ],
        [
            'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>700 ,
            'prix'  => 478,
        ],
        [
            'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>700 ,
            'prix'  => 495,
        ],
        [
            'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>700 ,
            'prix'  => 576,
        ],
        [
            'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>700 ,
            'prix'  => 595,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>700 ,
            'prix'  => 621,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>700 ,
            'prix'  => 653,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>700 ,
            'prix'  => 680,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>700 ,
            'prix'  => 736,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>700 ,
            'prix'  => 751,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>700 ,
            'prix'  => 813,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>700 ,
            'prix'  => 840,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>700 ,
            'prix'  => 879,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>700 ,
            'prix'  => 906,
        ],
        /* couleur 2*/
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 500,
            'largeur'  =>700 ,
            'prix'  => 561,
        ],
        [
            'type'    =>1 ,
            'couleur'    => 2,
            'hauteur'    => 600,
            'largeur'  =>700 ,
            'prix'  => 576,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 700,
            'largeur'  =>700 ,
            'prix'  => 607,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 800,
            'largeur'  =>700 ,
            'prix'  => 687,
        ],
        [
            'type'    =>1 ,
            'couleur'    => 2,
            'hauteur'    => 900,
            'largeur'  =>700 ,
            'prix'  => 716,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 1000,
            'largeur'  =>700 ,
            'prix'  => 751,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 1100,
            'largeur'  =>700 ,
            'prix'  => 779,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 1200,
            'largeur'  =>700 ,
            'prix'  => 813,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 1300,
            'largeur'  =>700 ,
            'prix'  => 840,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 1400,
            'largeur'  =>700 ,
            'prix'  => 891,
        ],
        [
            'type'    =>1 ,
            'couleur'    => 2,
            'hauteur'    => 1500,
            'largeur'  =>700 ,
            'prix'  => 957,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 1600,
            'largeur'  =>700 ,
            'prix'  => 989,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 1700,
            'largeur'  =>700 ,
            'prix'  => 1012
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 1800,
            'largeur'  =>700 ,
            'prix'  => 1044,
        ],
        /* couleur 3*/
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 500,
            'largeur'  =>700 ,
            'prix'  => 621,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 600,
            'largeur'  =>700 ,
            'prix'  => 653,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 700,
            'largeur'  =>700 ,
            'prix'  => 680,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 800,
            'largeur'  =>700 ,
            'prix'  => 767,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 900,
            'largeur'  =>700 ,
            'prix'  => 806,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 1000,
            'largeur'  =>700 ,
            'prix'  => 833,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 1100,
            'largeur'  =>700 ,
            'prix'  => 879,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 1200,
            'largeur'  =>700 ,
            'prix'  => 920,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 1300,
            'largeur'  =>700 ,
            'prix'  => 958,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 1400,
            'largeur'  =>700 ,
            'prix'  => 996,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 1500,
            'largeur'  =>700 ,
            'prix'  => 1090,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 1600,
            'largeur'  =>700 ,
            'prix'  => 1112,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 1700,
            'largeur'  =>700 ,
            'prix'  => 1151,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 1800,
            'largeur'  =>700 ,
            'prix'  => 1202,
        ],
        /*larg=800*/

        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>800 ,
            'prix'  => 478,
        ],
        [
            'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>800 ,
            'prix'  => 495,
        ],
        [
            'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>800 ,
            'prix'  => 527,
        ],
        [
            'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>800 ,
            'prix'  => 595,
        ],
        [
            'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>800 ,
            'prix'  => 621,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>800 ,
            'prix'  => 666,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>800 ,
            'prix'  => 687,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>800 ,
            'prix'  => 716,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>800 ,
            'prix'  => 676,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>800 ,
            'prix'  => 791,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>800 ,
            'prix'  => 857,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>800 ,
            'prix'  => 906,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>800 ,
            'prix'  => 938,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>800 ,
            'prix'  => 989,
        ],
        /* couleur 2*/
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 500,
            'largeur'  =>800 ,
            'prix'  => 576,
        ],
        [
            'type'    =>1 ,
            'couleur'    => 2,
            'hauteur'    => 600,
            'largeur'  =>800 ,
            'prix'  => 607,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 700,
            'largeur'  =>800 ,
            'prix'  => 634,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 800,
            'largeur'  =>800 ,
            'prix'  => 716,
        ],
        [
            'type'    =>1 ,
            'couleur'    => 2,
            'hauteur'    => 900,
            'largeur'  =>800 ,
            'prix'  => 751,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 1000,
            'largeur'  =>800 ,
            'prix'  => 791,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 1100,
            'largeur'  =>800 ,
            'prix'  => 813,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 1200,
            'largeur'  =>800 ,
            'prix'  => 857,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 1300,
            'largeur'  =>800 ,
            'prix'  => 906,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 1400,
            'largeur'  =>800 ,
            'prix'  => 930,
        ],
        [
            'type'    =>1 ,
            'couleur'    => 2,
            'hauteur'    => 1500,
            'largeur'  =>800 ,
            'prix'  => 1012,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 1600,
            'largeur'  =>800 ,
            'prix'  =>1044 ,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 1700,
            'largeur'  =>800 ,
            'prix'  => 1071,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 1800,
            'largeur'  =>800 ,
            'prix'  => 1098,
        ],
        /* couleur 3*/
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 500,
            'largeur'  =>800 ,
            'prix'  => 653,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 600,
            'largeur'  =>800 ,
            'prix'  => 680,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 700,
            'largeur'  =>800 ,
            'prix'  => 716,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 800,
            'largeur'  =>800 ,
            'prix'  => 806,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 900,
            'largeur'  =>800 ,
            'prix'  => 833,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 1000,
            'largeur'  =>800 ,
            'prix'  => 879,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 1100,
            'largeur'  =>800 ,
            'prix'  => 930,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 1200,
            'largeur'  =>800 ,
            'prix'  => 972,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 1300,
            'largeur'  =>800 ,
            'prix'  => 1012,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 1400,
            'largeur'  =>800 ,
            'prix'  => 1057,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 1500,
            'largeur'  =>800 ,
            'prix'  => 1141,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 1600,
            'largeur'  =>800 ,
            'prix'  => 1183,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 1700,
            'largeur'  =>800 ,
            'prix'  => 1227,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 1800,
            'largeur'  =>800 ,
            'prix'  => 1263,
        ],
        /*Larg=900*/
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>900 ,
            'prix'  => 495,
        ],
        [
            'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>900 ,
            'prix'  => 527,
        ],
        [
            'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>900 ,
            'prix'  => 549,
        ],
        [
            'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>900 ,
            'prix'  => 621,
        ],
        [
            'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>900 ,
            'prix'  => 666,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>900 ,
            'prix'  => 687,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>900 ,
            'prix'  => 728,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>900 ,
            'prix'  => 779,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>900 ,
            'prix'  => 806,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>900 ,
            'prix'  => 840,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>900 ,
            'prix'  => 920,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>900 ,
            'prix'  => 938,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>900 ,
            'prix'  => 972,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>900 ,
            'prix'  => 1012,
        ],
        /* couleur 2*/
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 500,
            'largeur'  =>900 ,
            'prix'  => 607,
        ],
        [
            'type'    =>1 ,
            'couleur'    => 2,
            'hauteur'    => 600,
            'largeur'  =>900 ,
            'prix'  => 634,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 700,
            'largeur'  =>900 ,
            'prix'  => 666,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 800,
            'largeur'  =>900 ,
            'prix'  => 751,
        ],
        [
            'type'    =>1 ,
            'couleur'    => 2,
            'hauteur'    => 900,
            'largeur'  =>900 ,
            'prix'  => 791,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 1000,
            'largeur'  =>900 ,
            'prix'  => 833,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 1100,
            'largeur'  =>900 ,
            'prix'  => 879,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 1200,
            'largeur'  =>900 ,
            'prix'  => 906,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 1300,
            'largeur'  =>900 ,
            'prix'  => 938,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 1400,
            'largeur'  =>900 ,
            'prix'  => 989,
        ],
        [
            'type'    =>1 ,
            'couleur'    => 2,
            'hauteur'    => 1500,
            'largeur'  =>900 ,
            'prix'  => 1057,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 1600,
            'largeur'  =>900 ,
            'prix'  => 1098,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 1700,
            'largeur'  =>900 ,
            'prix'  => 1144,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 1800,
            'largeur'  =>900 ,
            'prix'  => 1183,
        ],
        /* couleur 3*/
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 500,
            'largeur'  =>900 ,
            'prix'  => 687,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 600,
            'largeur'  =>900 ,
            'prix'  => 716,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 700,
            'largeur'  =>900 ,
            'prix'  =>751 ,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 800,
            'largeur'  =>900 ,
            'prix'  => 833,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 900,
            'largeur'  =>900 ,
            'prix'  => 891,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 1000,
            'largeur'  =>900 ,
            'prix'  => 930,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 1100,
            'largeur'  =>900 ,
            'prix'  => 972,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 1200,
            'largeur'  =>900 ,
            'prix'  => 1035,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 1300,
            'largeur'  =>900 ,
            'prix'  => 1071,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 1400,
            'largeur'  =>900 ,
            'prix'  => 1112,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 1500,
            'largeur'  =>900 ,
            'prix'  => 1223,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 1600,
            'largeur'  =>900 ,
            'prix'  => 1239,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 1700,
            'largeur'  =>900 ,
            'prix'  => 1280,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 1800,
            'largeur'  =>900 ,
            'prix'  => 1323,
        ],
        /*larg=1000*/
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>1000 ,
            'prix'  => 527,
        ],
        [
            'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1000 ,
            'prix'  => 549,
        ],
        [
            'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1000 ,
            'prix'  => 561,
        ],
        [
            'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1000 ,
            'prix'  => 666,
        ],
        [
            'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1000 ,
            'prix'  => 687,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1000 ,
            'prix'  => 728,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1000 ,
            'prix'  => 779,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1000 ,
            'prix'  => 813,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1000 ,
            'prix'  => 840,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1000 ,
            'prix'  => 897,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1000 ,
            'prix'  =>957 ,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1000 ,
            'prix'  => 996,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1000 ,
            'prix'  => 1044,
        ],

        /* couleur 2*/
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 500,
            'largeur'  =>1000 ,
            'prix'  => 634,
        ],
        [
            'type'    =>1 ,
            'couleur'    => 2,
            'hauteur'    => 600,
            'largeur'  =>1000 ,
            'prix'  => 666,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 700,
            'largeur'  =>1000 ,
            'prix'  => 687,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 800,
            'largeur'  =>1000 ,
            'prix'  => 791,
        ],
        [
            'type'    =>1 ,
            'couleur'    => 2,
            'hauteur'    => 900,
            'largeur'  =>1000 ,
            'prix'  => 833,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 1000,
            'largeur'  =>1000 ,
            'prix'  => 879,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 1100,
            'largeur'  =>1000 ,
            'prix'  => 920,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 1200,
            'largeur'  =>1000 ,
            'prix'  => 957,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 1300,
            'largeur'  =>1000 ,
            'prix'  => 996,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 1400,
            'largeur'  =>1000 ,
            'prix'  => 1044,
        ],
        [
            'type'    =>1 ,
            'couleur'    => 2,
            'hauteur'    => 1500,
            'largeur'  =>1000 ,
            'prix'  => 1112,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 1600,
            'largeur'  =>1000 ,
            'prix'  => 1151,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>2 ,
            'hauteur'    => 1700,
            'largeur'  =>1000 ,
            'prix'  => 1202,
        ],

        /* couleur 3*/
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 500,
            'largeur'  =>1000 ,
            'prix'  => 716,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 600,
            'largeur'  =>1000 ,
            'prix'  => 752,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 700,
            'largeur'  =>1000 ,
            'prix'  => 791,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 800,
            'largeur'  =>1000 ,
            'prix'  => 891,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 900,
            'largeur'  =>1000 ,
            'prix'  => 930, //faute
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 1000,
            'largeur'  =>1000 ,
            'prix'  => 989,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 1100,
            'largeur'  =>1000 ,
            'prix'  => 1035,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 1200,
            'largeur'  =>1000 ,
            'prix'  => 1071,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 1300,
            'largeur'  =>1000 ,
            'prix'  => 1122,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 1400,
            'largeur'  =>1000 ,
            'prix'  => 1163,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 1500,
            'largeur'  =>1000 ,
            'prix'  => 1277,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 1600,
            'largeur'  =>1000 ,
            'prix'  => 1294,
        ],
        [
            'type'    =>1 ,
            'couleur'    =>3 ,
            'hauteur'    => 1700,
            'largeur'  =>1000 ,
            'prix'  => 1345,
        ],



            ];

            Modele::insert($modeles);

        }


    }
}
