<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Modele;
use App\Models\Seeders;

class Modeles2F1V_ALU extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $seeder = Modele::where('type',2)->where('genre',2)->count();

        //Check if the seeder exist in the DB
        // fenetre 1V   ALU
        if ($seeder==0) {
            $modeles =
            [

                /*larg= 350*/
                [
                    'genre'    =>2 ,
                    'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 404,
                    'largeur'  =>350 ,
                    'prix'  =>374 ,
                ],
                [
                    'genre'    =>2 ,
                    'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 500,
                    'largeur'  =>350 ,
                    'prix'  =>398 ,
                ],
                [
                    'genre'    =>2 ,
                    'type'    =>2 ,
                    'couleur'    => 1,
                    'hauteur'    =>600 ,
                    'largeur'  =>350 ,
                    'prix'  => 423,
                ],
                [
                    'genre'    =>2 ,
                    'type'    =>2 ,
                    'couleur'    => 1,
                    'hauteur'    => 700,
                    'largeur'  =>350 ,
                    'prix'  => 479,
                ],
                [
                    'genre'    =>2 ,
                    'type'    =>2 ,
                    'couleur'    => 1,
                    'hauteur'    => 800,
                    'largeur'  =>350 ,
                    'prix'  =>550 ,
                ],

                /*larg= 400*/
                [
                    'genre'    =>2 ,
                    'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 404,
                    'largeur'  =>400 ,
                    'prix'  =>378 ,
                ],
                [
                    'genre'    =>2 ,
                    'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 500,
                    'largeur'  =>400 ,
                    'prix'  =>402 ,
                ],
                [
                    'genre'    =>2 ,
                    'type'    =>2 ,
                    'couleur'    => 1,
                    'hauteur'    =>600 ,
                    'largeur'  =>400 ,
                    'prix'  => 427,
                ],
                [
                    'genre'    =>2 ,
                    'type'    =>2 ,
                    'couleur'    => 1,
                    'hauteur'    => 700,
                    'largeur'  =>400 ,
                    'prix'  => 484,
                ],
                [
                    'genre'    =>2 ,
                    'type'    =>2 ,
                    'couleur'    => 1,
                    'hauteur'    => 800,
                    'largeur'  =>400 ,
                    'prix'  =>555 ,
                ],

            /*larg= 500*/
                [
                    'genre'    =>2 ,
                    'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 500,
                    'largeur'  =>500 ,
                    'prix'  =>405 ,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 500,
                    'largeur'  =>500 ,
                    'prix'  =>430 ,
				],
				[
                    'genre'    =>2 ,
					'type'    =>2 ,
                    'couleur'    => 1,
                    'hauteur'    =>600 ,
                    'largeur'  =>500 ,
                    'prix'  => 455,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>2 ,
                    'couleur'    => 1,
                    'hauteur'    => 700,
                    'largeur'  =>500 ,
                    'prix'  => 516,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>2 ,
                    'couleur'    => 1,
                    'hauteur'    => 800,
                    'largeur'  =>500 ,
                    'prix'  => 586,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>2 ,
                    'couleur'    => 1,
                    'hauteur'    => 900,
                    'largeur'  =>500 ,
                    'prix'  => 614,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1000,
                    'largeur'  =>500 ,
                    'prix'  => 641,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    =>1100 ,
                    'largeur'  =>500 ,
                    'prix'  => 669,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1200,
                    'largeur'  =>500 ,
                    'prix'  => 696,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1300,
                    'largeur'  =>500 ,
                    'prix'  => 724,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1400,
                    'largeur'  =>500 ,
                    'prix'  => 751,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1500,
                    'largeur'  =>500 ,
                    'prix'  => 779,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1600,
                    'largeur'  =>500 ,
                    'prix'  => 806,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1700,
                    'largeur'  =>500 ,
                    'prix'  => 834,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1800,
                    'largeur'  =>500 ,
                    'prix'  =>861 ,
                ],
                [
                    'genre'    =>2 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1900,
                    'largeur'  =>500 ,
                    'prix'  =>889 ,
                ],
                [
                    'genre'    =>2 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2000,
                    'largeur'  =>500 ,
                    'prix'  =>916 ,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2100,
                    'largeur'  =>500 ,
                    'prix'  =>947 ,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2200,
                    'largeur'  =>500 ,
                    'prix'  =>975 ,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2300,
                    'largeur'  =>500 ,
                    'prix'  =>1045 ,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2400,
                    'largeur'  =>500 ,
                    'prix'  =>1073 ,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2500,
                    'largeur'  =>500 ,
                    'prix'  =>1099 ,
                ],
             /*Larg= 600*/
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 404,
                'largeur'  =>600 ,
                'prix'  => 432,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 500,
                'largeur'  =>600 ,
                'prix'  => 457,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>2 ,
                'couleur'    => 1,
                'hauteur'    =>600 ,
                'largeur'  =>600 ,
                'prix'  => 483,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>2 ,
                'couleur'    => 1,
                'hauteur'    => 700,
                'largeur'  =>600 ,
                'prix'  => 546,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>2 ,
                'couleur'    => 1,
                'hauteur'    => 800,
                'largeur'  =>600 ,
                'prix'  => 619,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>2 ,
                'couleur'    => 1,
                'hauteur'    => 900,
                'largeur'  =>600 ,
                'prix'  => 647,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 1000,
                'largeur'  =>600 ,
                'prix'  => 675,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    =>1100 ,
                'largeur'  =>600 ,
                'prix'  => 702,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 1200,
                'largeur'  =>600 ,
                'prix'  => 731,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 1300,
                'largeur'  =>600 ,
                'prix'  => 759,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 1400,
                'largeur'  =>600 ,
                'prix'  => 787,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 1500,
                'largeur'  =>600 ,
                'prix'  => 815,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 1600,
                'largeur'  =>600 ,
                'prix'  =>844 ,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 1700,
                'largeur'  =>600 ,
                'prix'  => 871,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 1800,
                'largeur'  =>600 ,
                'prix'  => 899,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 1900,
                'largeur'  =>600 ,
                'prix'  => 927,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 2000,
                'largeur'  =>600 ,
                'prix'  => 956,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 2100,
                'largeur'  =>600 ,
                'prix'  => 988,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 2200,
                'largeur'  =>600 ,
                'prix'  => 1015,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 2300,
                'largeur'  =>600 ,
                'prix'  => 1086,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 2400,
                'largeur'  =>600 ,
                'prix'  => 1114,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 2500,
                'largeur'  =>600 ,
                'prix'  => 1140,
            ],
         /*Larg=700*/
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>700 ,
            'prix'  => 511,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>700 ,
            'prix'  => 578,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>700 ,
            'prix'  => 650,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>700 ,
            'prix'  => 679,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>700 ,
            'prix'  => 708,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>700 ,
            'prix'  => 736,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>700 ,
            'prix'  => 765,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>700 ,
            'prix'  => 794,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>700 ,
            'prix'  => 822,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>700 ,
            'prix'  => 851,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>700 ,
            'prix'  => 880,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>700 ,
            'prix'  => 909,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>700 ,
            'prix'  => 937,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>700 ,
            'prix'  => 966,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>700 ,
            'prix'  => 995,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>700 ,
            'prix'  => 1027,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>700 ,
            'prix'  => 1056,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>700 ,
            'prix'  => 1127,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>700 ,
            'prix'  => 1156,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>700 ,
            'prix'  => 1182,
        ],
        /*larg=800*/
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>800 ,
            'prix'  => 540,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>800 ,
            'prix'  => 609,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>800 ,
            'prix'  => 682,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>800 ,
            'prix'  => 711,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>800 ,
            'prix'  => 741,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>800 ,
            'prix'  => 770,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>800 ,
            'prix'  => 800,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>800 ,
            'prix'  => 828,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>800 ,
            'prix'  => 858,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>800 ,
            'prix'  => 887,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>800 ,
            'prix'  => 917,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>800 ,
            'prix'  => 946,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>800 ,
            'prix'  => 976,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>800 ,
            'prix'  => 1005,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>800 ,
            'prix'  => 1034,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>800 ,
            'prix'  => 1067,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>800 ,
            'prix'  => 1097,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>800 ,
            'prix'  => 1167,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>800 ,
            'prix'  => 1198,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>800 ,
            'prix'  => 1223,
        ],
         /*Larg=900*/
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>900 ,
            'prix'  => 568,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>900 ,
            'prix'  => 684,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>900 ,
            'prix'  => 714,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>900 ,
            'prix'  => 744,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>900 ,
            'prix'  => 774,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>900 ,
            'prix'  => 804,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>900 ,
            'prix'  => 834,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>900 ,
            'prix'  => 864,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>900 ,
            'prix'  => 893,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>900 ,
            'prix'  => 924,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>900 ,
            'prix'  => 954,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>900 ,
            'prix'  => 984,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>900 ,
            'prix'  => 1014,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>900 ,
            'prix'  => 1043,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>900 ,
            'prix'  => 1074,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>900 ,
            'prix'  => 1108,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>900 ,
            'prix'  => 1137,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>900 ,
            'prix'  => 1210,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>900 ,
            'prix'  => 1240,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>900 ,
            'prix'  => 1265,
        ],

        /*larg=1000*/
    /*    [
            'genre'    =>2 ,
 	 	 	'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1000 ,
            'prix'  => 211,
        ],
        [
            'genre'    =>2 ,
 	 	 	'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1000 ,
            'prix'  => 204,
        ],*/
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1000 ,
            'prix'  => 715,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1000 ,
            'prix'  => 746,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1000 ,
            'prix'  => 776,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1000 ,
            'prix'  => 807,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1000 ,
            'prix'  => 837,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1000 ,
            'prix'  => 868,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1000 ,
            'prix'  => 899,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1000 ,
            'prix'  => 929,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1000 ,
            'prix'  =>960 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1000 ,
            'prix'  => 990,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1000 ,
            'prix'  => 1021,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1000 ,
            'prix'  => 1052,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1000 ,
            'prix'  => 1082,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1000 ,
            'prix'  => 1113,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1000 ,
            'prix'  => 1147,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1000 ,
            'prix'  => 1178,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1000 ,
            'prix'  => 1251,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1000 ,
            'prix'  => 1281,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1000 ,
            'prix'  => 1307,
        ],
        /*larg=1100*//*
        [
            'genre'    =>2 ,
 	 	 	'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1100 ,
            'prix'  => 220,
        ],*/
        [
            'genre'    =>2 ,
 	 	 	'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>700 ,
            'largeur'  =>1100 ,
            'prix'  => 746,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1100 ,
            'prix'  => 777,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1100 ,
            'prix'  => 809,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 1000,
            'largeur'  =>1100 ,
            'prix'  => 840,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1100,
            'largeur'  =>1100 ,
            'prix'  => 871,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    =>1200 ,
            'largeur'  =>1100 ,
            'prix'  => 902,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1100 ,
            'prix'  => 933,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1100 ,
            'prix'  => 965,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1100 ,
            'prix'  =>996 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1100 ,
            'prix'  => 1027,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1100 ,
            'prix'  => 1059,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1100 ,
            'prix'  => 1090,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1100 ,
            'prix'  => 1121,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1100 ,
            'prix'  => 1153,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1100 ,
            'prix'  => 1187,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1100 ,
            'prix'  => 1219,
        ],
        [
            'genre'    =>2 ,
 	 	 	'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1100 ,
            'prix'  => 1292,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1100 ,
            'prix'  => 1323,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1100 ,
            'prix'  => 1349,
        ],
        /*larg=1200*/
    /*    [
            'genre'    =>2 ,
 	 	 	'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1200 ,
            'prix'  => 227,
        ],
        [
            'genre'    =>2 ,
 	 	 	'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1200 ,
            'prix'  => 236,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1200 ,
            'prix'  => 234,
        ],*/
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1200 ,
            'prix'  => 809,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1200 ,
            'prix'  => 841,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1200 ,
            'prix'  => 873,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1200 ,
            'prix'  => 905,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1200 ,
            'prix'  => 937,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1200 ,
            'prix'  => 969,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1200 ,
            'prix'  => 1001,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1200 ,
            'prix'  => 1033 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1200 ,
            'prix'  => 1065,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1200 ,
            'prix'  => 1096,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1200 ,
            'prix'  => 1128,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1200 ,
            'prix'  => 1160,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1200 ,
            'prix'  => 1191,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1200 ,
            'prix'  => 1227,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1200 ,
            'prix'  => 1259,
        ],/*
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1200 ,
            'prix'  => 541,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1200 ,
            'prix'  => 553,
        ],*/
        /*larg=1300*/
    /*    [
            'genre'    =>2 ,
 	 	 	'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1300 ,
            'prix'  => 243,
        ],
        [
            'genre'    =>2 ,
 	 	 	'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1300 ,
            'prix'  => 257,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1300 ,
            'prix'  => 243,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1300 ,
            'prix'  => 257,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1300 ,
            'prix'  => 268,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1300 ,
            'prix'  => 279,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1300 ,
            'prix'  => 294,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1300 ,
            'prix'  => 306,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1300 ,
            'prix'  => 316,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1300 ,
            'prix'  => 327,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1300 ,
            'prix'  =>342 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1300 ,
            'prix'  => 354,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1300 ,
            'prix'  => 369,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1300 ,
            'prix'  => 389,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1300 ,
            'prix'  => 437,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1300 ,
            'prix'  => 446,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1300 ,
            'prix'  => 515,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1300 ,
            'prix'  => 545,
        ],
        /*larg=1400*/
    /*    [
            'genre'    =>2 ,
 	 	 	'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1400 ,
            'prix'  => 240,
        ],
        [
            'genre'    =>2 ,
 	 	 	'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1400 ,
            'prix'  => 252,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1400 ,
            'prix'  => 263,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1400 ,
            'prix'  => 282,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1400 ,
            'prix'  => 301,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1400 ,
            'prix'  => 290,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1400 ,
            'prix'  => 301,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1400 ,
            'prix'  => 316,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1400 ,
            'prix'  => 327,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1400 ,
            'prix'  => 342,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1400 ,
            'prix'  =>354 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1400 ,
            'prix'  => 365,
        ],/*
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1400 ,
            'prix'  => 389,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1400 ,
            'prix'  => 423,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1400 ,
            'prix'  => 452,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1400 ,
            'prix'  => 454,
        ],*/
        /*larg=1500*/
    /*    [
            'genre'    =>2 ,
 	 	 	'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1500 ,
            'prix'  => 247,
        ],
        [
            'genre'    =>2 ,
 	 	 	'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1500 ,
            'prix'  => 261,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1500 ,
            'prix'  => 275,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1500 ,
            'prix'  => 292,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1500 ,
            'prix'  => 305,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1500 ,
            'prix'  => 312,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1500 ,
            'prix'  => 327,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1500 ,
            'prix'  => 342,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1500 ,
            'prix'  => 354,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1500 ,
            'prix'  => 369,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1500 ,
            'prix'  =>379 ,
        ],/*
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1500 ,
            'prix'  => 419,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1500 ,
            'prix'  => 430,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1500 ,
            'prix'  => 438,
        ],
*/



            ];

            Modele::insert($modeles);

        }


    }
}
