<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Modele;
use App\Models\Seeders;

class Modeles4VSeeder extends Seeder  //4V
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $seeder = Modele::where('type',11)->count();
        // fenetre 4V  pvc
        //Check if the seeder exist in the DB
        if ($seeder==0) {
            $modeles =
            [


        /*Larg=1800*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>1800 ,
            'prix'  => 448,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1800 ,
            'prix'  => 471,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1800 ,
            'prix'  => 492,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1800 ,
            'prix'  => 503,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1800 ,
            'prix'  => 524,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1800 ,
            'prix'  => 558,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1800 ,
            'prix'  => 579,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1800 ,
            'prix'  => 599,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1800 ,
            'prix'  => 626,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1800 ,
            'prix'  => 654,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1800 ,
            'prix'  => 684,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1800 ,
            'prix'  => 712,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1800 ,
            'prix'  => 718,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1800 ,
            'prix'  => 784,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1800 ,
            'prix'  => 803,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1800 ,
            'prix'  => 833,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1800 ,
            'prix'  => 854,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1800 ,
            'prix'  => 882,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1800 ,
            'prix'  => 910,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1800 ,
            'prix'  => 945,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1800 ,
            'prix'  => 956,
        ],
        /*larg=1900*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1900 ,
            'prix'  => 455,//ici
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1900 ,
            'prix'  => 475,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1900 ,
            'prix'  => 496,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1900 ,
            'prix'  => 512,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1900 ,
            'prix'  => 531,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1900 ,
            'prix'  => 563,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1900 ,
            'prix'  => 585,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1900 ,
            'prix'  => 611,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1900 ,
            'prix'  => 638,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1900 ,
            'prix'  => 666,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1900 ,
            'prix'  =>697 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1900 ,
            'prix'  => 725,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1900 ,
            'prix'  => 760,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1900 ,
            'prix'  => 799,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1900 ,
            'prix'  => 818,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1900 ,
            'prix'  => 848,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1900 ,
            'prix'  => 870,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1900 ,
            'prix'  => 898,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1900 ,
            'prix'  => 925,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1900 ,
            'prix'  => 965,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1900 ,
            'prix'  => 992,
        ],
        /*larg=2000*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>2000 ,
            'prix'  => 460,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>2000 ,
            'prix'  => 486,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2000 ,
            'prix'  => 503,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2000 ,
            'prix'  => 516,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2000 ,
            'prix'  => 534,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2000 ,
            'prix'  => 572,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2000 ,
            'prix'  => 595,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2000 ,
            'prix'  => 618,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2000 ,
            'prix'  => 649,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2000 ,
            'prix'  => 676,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2000 ,
            'prix'  => 712,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2000 ,
            'prix'  => 737,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2000 ,
            'prix'  => 776,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2000 ,
            'prix'  => 815,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2000 ,
            'prix'  => 835,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2000 ,
            'prix'  => 862,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>2000 ,
            'prix'  => 890,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2000 ,
            'prix'  => 914,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>2000 ,
            'prix'  => 952,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>2000 ,
            'prix'  => 984,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>2000 ,
            'prix'  => 1012,
        ],
        /*larg=2100*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>2100 ,
            'prix'  => 469,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 600,
            'largeur'  =>2100 ,
            'prix'  => 488,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2100 ,
            'prix'  => 509,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2100 ,
            'prix'  => 524,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 900,
            'largeur'  =>2100 ,
            'prix'  => 547,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    =>1000 ,
            'largeur'  =>2100 ,
            'prix'  => 579,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1100,
            'largeur'  =>2100 ,
            'prix'  => 552,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2100 ,
            'prix'  => 630,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2100 ,
            'prix'  => 661,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2100 ,
            'prix'  =>689 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2100 ,
            'prix'  => 726,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2100 ,
            'prix'  => 756,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2100 ,
            'prix'  => 787,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2100 ,
            'prix'  => 833,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2100 ,
            'prix'  => 851,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2100 ,
            'prix'  => 878,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>2100 ,
            'prix'  => 904,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2100 ,
            'prix'  => 933,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>2100 ,
            'prix'  => 965,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>2100 ,
            'prix'  => 1001,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>2100 ,
            'prix'  => 1028,
        ],

        /*larg=2200*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>2200 ,
            'prix'  => 471,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>2200 ,
            'prix'  => 496,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2200 ,
            'prix'  => 516,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2200 ,
            'prix'  => 527,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2200 ,
            'prix'  => 551,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2200 ,
            'prix'  => 585,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2200 ,
            'prix'  => 614,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2200 ,
            'prix'  => 642,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2200 ,
            'prix'  => 673,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2200 ,
            'prix'  => 705,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2200 ,
            'prix'  =>737 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2200 ,
            'prix'  => 767,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2200 ,
            'prix'  => 803,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2200 ,
            'prix'  => 843,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2200 ,
            'prix'  => 867,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2200 ,
            'prix'  => 894,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>2200 ,
            'prix'  => 921,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2200 ,
            'prix'  => 954,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>2200 ,
            'prix'  => 984,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>2200 ,
            'prix'  => 1019,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>2200 ,
            'prix'  => 1047,
        ],

        /*larg=2300*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>2300 ,
            'prix'  => 479,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>2300 ,
            'prix'  => 500,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2300 ,
            'prix'  => 521,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2300 ,
            'prix'  => 535,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2300 ,
            'prix'  => 558,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2300 ,
            'prix'  => 596,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2300 ,
            'prix'  => 626,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2300 ,
            'prix'  => 654,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2300 ,
            'prix'  => 685,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2300 ,
            'prix'  => 717,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2300 ,
            'prix'  =>756 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2300 ,
            'prix'  => 785,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2300 ,
            'prix'  => 818,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2300 ,
            'prix'  => 858,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2300 ,
            'prix'  => 882,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2300 ,
            'prix'  => 910,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>2300 ,
            'prix'  => 937,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2300 ,
            'prix'  => 974,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>2300 ,
            'prix'  => 1001,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>2300 ,
            'prix'  => 1039,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>2300 ,
            'prix'  => 1068,
        ],

        /*larg=2400*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>2400 ,
            'prix'  => 486,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>2400 ,
            'prix'  => 509,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2400 ,
            'prix'  => 527,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2400 ,
            'prix'  => 543,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2400 ,
            'prix'  => 564,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2400 ,
            'prix'  => 608,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2400 ,
            'prix'  => 635,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2400 ,
            'prix'  => 667,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2400 ,
            'prix'  => 697,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2400 ,
            'prix'  => 728,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2400 ,
            'prix'  =>767 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2400 ,
            'prix'  => 794,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2400 ,
            'prix'  => 833,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2400 ,
            'prix'  => 873,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2400 ,
            'prix'  => 894,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2400 ,
            'prix'  => 925,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>2400 ,
            'prix'  => 958,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2400 ,
            'prix'  => 988,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>2400 ,
            'prix'  => 1019,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>2400 ,
            'prix'  => 1055,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>2400 ,
            'prix'  => 1086,
        ],

        /*larg=2500*/

        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>2500 ,
            'prix'  => 512,//
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2500 ,
            'prix'  => 532,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2500 ,
            'prix'  => 551,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2500 ,
            'prix'  => 575,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2500 ,
            'prix'  => 619,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2500 ,
            'prix'  => 646,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2500 ,
            'prix'  => 676,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2500 ,
            'prix'  => 708,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2500 ,
            'prix'  => 745,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2500 ,
            'prix'  => 780,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2500 ,
            'prix'  => 810,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2500 ,
            'prix'  => 848,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2500 ,
            'prix'  => 890,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2500 ,
            'prix'  =>910 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2500 ,
            'prix'  =>945 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>2500 ,
            'prix'  => 977,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2500 ,
            'prix'  => 1005,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>2500 ,
            'prix'  => 1037,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>2500 ,
            'prix'  => 1076,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>2500 ,
            'prix'  => 1103,
        ],
        /*larg=2600*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 600,
            'largeur'  =>2600 ,
            'prix'  => 521,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2600 ,
            'prix'  => 543,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 800,
            'largeur'  =>2600 ,
            'prix'  => 555,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    =>900 ,
            'largeur'  =>2600 ,
            'prix'  => 585,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    =>1000 ,
            'largeur'  =>2600 ,
            'prix'  => 626,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1100,
            'largeur'  =>2600 ,
            'prix'  => 657,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2600 ,
            'prix'  => 689,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2600 ,
            'prix'  => 723,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2600 ,
            'prix'  => 756,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2600 ,
            'prix'  => 794,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2600 ,
            'prix'  => 823,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2600 ,
            'prix'  => 858,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2600 ,
            'prix'  => 901,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2600 ,
            'prix'  => 925,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2600 ,
            'prix'  => 960,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>2600 ,
            'prix'  => 992,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2600 ,
            'prix'  => 1019,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2600 ,
            'prix'  => 1055,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2600 ,
            'prix'  => 1092,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2600 ,
            'prix'  => 1122,
        ],
        /*larg=2700*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 600,
            'largeur'  =>2700 ,
            'prix'  => 527,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2700 ,
            'prix'  => 551,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2700 ,
            'prix'  => 562,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2700 ,
            'prix'  => 596,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2700 ,
            'prix'  => 638,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2700 ,
            'prix'  => 669,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2700 ,
            'prix'  => 701,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2700 ,
            'prix'  => 732,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2700 ,
            'prix'  => 773,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2700 ,
            'prix'  =>808 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2700 ,
            'prix'  => 839,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2700 ,
            'prix'  => 873,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2700 ,
            'prix'  => 919,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2700 ,
            'prix'  => 945,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2700 ,
            'prix'  => 977,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>2700 ,
            'prix'  => 1008,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2700 ,
            'prix'  => 1039,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>2700 ,
            'prix'  => 1071
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>2700 ,
            'prix'  => 1110,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>2700 ,
            'prix'  => 1146,
        ],
        /*larg=2800*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2800 ,
            'prix'  => 555,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1700 ,
            'prix'  => 575,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2800 ,
            'prix'  => 608,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2800 ,
            'prix'  => 650,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2800 ,
            'prix'  => 680,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2800 ,
            'prix'  => 712,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2800 ,
            'prix'  => 748,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2800 ,
            'prix'  => 785,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2800 ,
            'prix'  =>818 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2800 ,
            'prix'  => 854,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2800 ,
            'prix'  => 890,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2800 ,
            'prix'  => 933,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2800 ,
            'prix'  => 960,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2800 ,
            'prix'  => 992,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>2800 ,
            'prix'  => 1023,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2800 ,
            'prix'  => 1055,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>2800 ,
            'prix'  => 1092,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>2800 ,
            'prix'  => 1131,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>2800 ,
            'prix'  => 1167,
        ],
        /*larg=2900*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2900 ,
            'prix'  => 562,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2900 ,
            'prix'  => 581,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2900 ,
            'prix'  => 614,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2900 ,
            'prix'  => 657,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2900 ,
            'prix'  => 692,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2900 ,
            'prix'  => 726,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2900 ,
            'prix'  => 760,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2900 ,
            'prix'  => 794,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2900 ,
            'prix'  =>835 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2900 ,
            'prix'  => 867,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2900 ,
            'prix'  => 904,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2900 ,
            'prix'  => 954,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2900 ,
            'prix'  => 977,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2900 ,
            'prix'  => 1008,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>2900 ,
            'prix'  => 1039,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2900 ,
            'prix'  => 1076,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>2900 ,
            'prix'  => 1106,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>2900 ,
            'prix'  => 1149,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>2900 ,
            'prix'  => 1187,
        ],
        /*larg=3000*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>3000 ,
            'prix'  => 564,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>3000 ,
            'prix'  => 590,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>3000 ,
            'prix'  => 626,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>3000 ,
            'prix'  => 669,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>3000 ,
            'prix'  => 701,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>3000 ,
            'prix'  => 737,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>3000 ,
            'prix'  => 773,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>3000 ,
            'prix'  => 730,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>3000 ,
            'prix'  =>808 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>3000 ,
            'prix'  => 848,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>3000 ,
            'prix'  => 878,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>3000 ,
            'prix'  => 919,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>3000 ,
            'prix'  => 965,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>3000 ,
            'prix'  => 992,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>3000 ,
            'prix'  => 1023,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>3000 ,
            'prix'  => 1062,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>3000 ,
            'prix'  => 1092,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>3000 ,
            'prix'  => 1125,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>3000 ,
            'prix'  => 1171,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>3000 ,
            'prix'  => 1201,
        ],
        /*larg=3100*/

        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>3100 ,
            'prix'  => 575,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>3100 ,
            'prix'  => 603,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>3100 ,
            'prix'  => 635,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>3100 ,
            'prix'  => 680,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>3100 ,
            'prix'  => 712,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>3100 ,
            'prix'  => 752,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>3100 ,
            'prix'  => 785,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>3100 ,
            'prix'  => 823,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>3100 ,
            'prix'  =>858 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>3100 ,
            'prix'  => 894,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>3100 ,
            'prix'  => 933,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>3100 ,
            'prix'  => 982,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>3100 ,
            'prix'  => 1008,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>3100 ,
            'prix'  => 1039,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>3100 ,
            'prix'  => 1076,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>3100 ,
            'prix'  => 1106,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>3100 ,
            'prix'  => 1146,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>3100 ,
            'prix'  => 1189,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>3100 ,
            'prix'  => 1222,
        ],
        /*larg=3200*/

        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>3200 ,
            'prix'  => 581,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>3200 ,
            'prix'  => 612,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>3200 ,
            'prix'  => 646,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>3200 ,
            'prix'  => 689,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>3200 ,
            'prix'  => 726,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>3200 ,
            'prix'  => 763,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>3200 ,
            'prix'  => 794,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>3200 ,
            'prix'  => 835,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>3200 ,
            'prix'  =>837 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>3200 ,
            'prix'  => 910,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>3200 ,
            'prix'  => 952,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>3200 ,
            'prix'  => 996,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>3200 ,
            'prix'  => 1023,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>3200 ,
            'prix'  => 1055,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>3200 ,
            'prix'  => 1092,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>3200 ,
            'prix'  => 1125,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>3200 ,
            'prix'  => 1167,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>3200 ,
            'prix'  => 1206,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>3200 ,
            'prix'  => 1240,
        ],
        /*larg=3300*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>3300 ,
            'prix'  => 590,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>3300 ,
            'prix'  => 619,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>3300 ,
            'prix'  => 654,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>3300 ,
            'prix'  => 701,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>3300 ,
            'prix'  =>737 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>3300 ,
            'prix'  => 776 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>3300 ,
            'prix'  => 810 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>3300 ,
            'prix'  => 848 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>3300 ,
            'prix'  =>887 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>3300 ,
            'prix'  => 921,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>3300 ,
            'prix'  => 965,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>3300 ,
            'prix'  => 1012,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>3300 ,
            'prix'  => 1039,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>3300 ,
            'prix'  => 1076,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>3300 ,
            'prix'  => 1106,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>3300 ,
            'prix'  => 1146,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>3300 ,
            'prix'  => 1182,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>3300 ,
            'prix'  => 1225,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>3300 ,
            'prix'  => 1259,
        ],

        /*larg=3400*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>3400 ,
            'prix'  => 608,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>3400 ,
            'prix'  => 635,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>3400 ,
            'prix'  => 669,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>3400 ,
            'prix'  => 717,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>3400 ,
            'prix'  => 756,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>3400 ,
            'prix'  => 790,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>3400 ,
            'prix'  => 826,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>3400 ,
            'prix'  => 862,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>3400 ,
            'prix'  =>904 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>3400 ,
            'prix'  =>945 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>3400 ,
            'prix'  =>984 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>3400 ,
            'prix'  =>1033 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>3400 ,
            'prix'  =>1062 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>3400 ,
            'prix'  =>1097 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>3400 ,
            'prix'  =>1131 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>3400 ,
            'prix'  =>1167 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>3400 ,
            'prix'  =>1206 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>3400 ,
            'prix'  =>1250 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>3400 ,
            'prix'  =>1285 ,
        ],
         /*larg=3500*/
         [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>3500 ,
            'prix'  => 619,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>3500 ,
            'prix'  => 650,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>3500 ,
            'prix'  => 685,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>3500 ,
            'prix'  => 732,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>3500 ,
            'prix'  => 773,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>3500 ,
            'prix'  => 808,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>3500 ,
            'prix'  => 843,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>3500 ,
            'prix'  => 882,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>3500 ,
            'prix'  =>921 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>3500 ,
            'prix'  =>965 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>3500 ,
            'prix'  =>1005 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>3500 ,
            'prix'  =>1051 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>3500 ,
            'prix'  =>1079 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>3500 ,
            'prix'  =>1114 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>3500 ,
            'prix'  =>1154 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>3500 ,
            'prix'  =>1189 ,
        ],
        /*larg=3600*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>3600 ,
            'prix'  => 626,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>3600 ,
            'prix'  => 657,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>3600 ,
            'prix'  => 692,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>3600 ,
            'prix'  => 745,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>3600 ,
            'prix'  => 785,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>3600 ,
            'prix'  => 818,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>3600 ,
            'prix'  => 854,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>3600 ,
            'prix'  => 894,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>3600 ,
            'prix'  =>937 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>3600 ,
            'prix'  =>977 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>3600 ,
            'prix'  =>1016 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>3600 ,
            'prix'  =>1068 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>3600 ,
            'prix'  =>1097 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>3600 ,
            'prix'  =>1131 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>3600 ,
            'prix'  =>1171 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>3600 ,
            'prix'  =>1210 ,
        ],
        /*larg=3700*/
		[
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>3700 ,
            'prix'  => 638,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>3700 ,
            'prix'  => 667,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>3700 ,
            'prix'  => 705,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>3700 ,
            'prix'  => 756,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>3700 ,
            'prix'  => 790,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>3700 ,
            'prix'  => 833,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>3700 ,
            'prix'  => 867,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>3700 ,
            'prix'  => 904,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>3700 ,
            'prix'  =>954 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>3700 ,
            'prix'  =>988 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>3700 ,
            'prix'  =>1033 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>11 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>3700 ,
            'prix'  =>1083 ,
        ],
    ];

            Modele::insert($modeles);

        }


    }
}
