<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Modele;
use App\Models\Seeders;

class ModelesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $seeder = Modele::where('type', 1)->count();

        //Check if the seeder exist in the DB
        // fenetre à soufflet
        if ($seeder == 0) {
            $modeles =
                [
                    /*larg= 374*/
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 344,
                        'largeur'  => 374,
                        'prix'  => 366,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 400,
                        'largeur'  => 374,
                        'prix'  => 369,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 500,
                        'largeur'  => 374,
                        'prix'  => 393,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 600,
                        'largeur'  => 374,
                        'prix'  => 420,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 700,
                        'largeur'  => 374,
                        'prix'  => 444,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 800,
                        'largeur'  => 374,
                        'prix'  => 468,
                    ],
                    /*larg= 400*/
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 344,
                        'largeur'  => 400,
                        'prix'  => 368,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 400,
                        'largeur'  => 400,
                        'prix'  => 371,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 500,
                        'largeur'  => 400,
                        'prix'  => 395,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 600,
                        'largeur'  => 400,
                        'prix'  => 422,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 700,
                        'largeur'  => 400,
                        'prix'  => 446,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 800,
                        'largeur'  => 400,
                        'prix'  => 470,
                    ],
                    /*larg= 500*/
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 344,
                        'largeur'  => 500,
                        'prix'  => 395,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 400,
                        'largeur'  => 500,
                        'prix'  => 398,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 500,
                        'largeur'  => 500,
                        'prix'  => 422,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 600,
                        'largeur'  => 500,
                        'prix'  => 450,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 700,
                        'largeur'  => 500,
                        'prix'  => 474,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 800,
                        'largeur'  => 500,
                        'prix'  => 498,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 900,
                        'largeur'  => 500,
                        'prix'  => 523,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1000,
                        'largeur'  => 500,
                        'prix'  => 547,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1100,
                        'largeur'  => 500,
                        'prix'  => 572,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1200,
                        'largeur'  => 500,
                        'prix'  => 597,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1300,
                        'largeur'  => 500,
                        'prix'  => 621,
                    ],
                    /*
                    [
                    'genre'    =>1 ,
					'type'    =>1 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1500,
                    'largeur'  =>500 ,
                    'prix'  => 239,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>1 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1600,
                    'largeur'  =>500 ,
                    'prix'  => 246,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>1 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1700,
                    'largeur'  =>500 ,
                    'prix'  => 276,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>1 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1800,
                    'largeur'  =>500 ,
                    'prix'  =>286 ,
                ],*/

                    /*Larg= 600*/
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 344,
                        'largeur'  => 600,
                        'prix'  => 421,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 400,
                        'largeur'  => 600,
                        'prix'  => 425,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 500,
                        'largeur'  => 600,
                        'prix'  => 449,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 600,
                        'largeur'  => 600,
                        'prix'  => 478,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 700,
                        'largeur'  => 600,
                        'prix'  => 503,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 800,
                        'largeur'  => 600,
                        'prix'  => 528,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 900,
                        'largeur'  => 600,
                        'prix'  => 553,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1000,
                        'largeur'  => 600,
                        'prix'  => 578,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1100,
                        'largeur'  => 600,
                        'prix'  => 604,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1200,
                        'largeur'  => 600,
                        'prix'  => 629,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1300,
                        'largeur'  => 600,
                        'prix'  => 654,
                    ],

                    /*        [
                'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
                'couleur'    =>1 ,
                'hauteur'    => 1500,
                'largeur'  =>600 ,
                'prix'  => 251,
            ],
            [
                'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
                'couleur'    =>1 ,
                'hauteur'    => 1600,
                'largeur'  =>600 ,
                'prix'  =>259 ,
            ],
            [
                'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
                'couleur'    =>1 ,
                'hauteur'    => 1700,
                'largeur'  =>600 ,
                'prix'  => 290,
            ],
            [
                'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
                'couleur'    =>1 ,
                'hauteur'    => 1800,
                'largeur'  =>600 ,
                'prix'  => 301,
            ],*/
                    /*Larg=700*/
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 500,
                        'largeur'  => 700,
                        'prix'  => 476,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 600,
                        'largeur'  => 700,
                        'prix'  => 505,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 700,
                        'largeur'  => 700,
                        'prix'  => 531,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 800,
                        'largeur'  => 700,
                        'prix'  => 557,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 900,
                        'largeur'  => 700,
                        'prix'  => 583,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1000,
                        'largeur'  => 700,
                        'prix'  => 609,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1100,
                        'largeur'  => 700,
                        'prix'  => 635,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1200,
                        'largeur'  => 700,
                        'prix'  => 660,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1300,
                        'largeur'  => 700,
                        'prix'  => 686,
                    ],
/*
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>700 ,
            'prix'  => 265,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>700 ,
            'prix'  => 293,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>700 ,
            'prix'  => 303,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>700 ,
            'prix'  => 314,
        ],*/
                    /*larg=800*/
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 500,
                        'largeur'  => 800,
                        'prix'  => 507,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 600,
                        'largeur'  => 800,
                        'prix'  => 533,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 700,
                        'largeur'  => 800,
                        'prix'  => 560,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 800,
                        'largeur'  => 800,
                        'prix'  => 586,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 900,
                        'largeur'  => 800,
                        'prix'  => 612,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1000,
                        'largeur'  => 800,
                        'prix'  => 639,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1100,
                        'largeur'  => 800,
                        'prix'  => 666,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1200,
                        'largeur'  => 800,
                        'prix'  => 691,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1300,
                        'largeur'  => 800,
                        'prix'  => 718,
                    ],
                    /*
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>800 ,
            'prix'  => 288,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>800 ,
            'prix'  => 321,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>800 ,
            'prix'  => 332,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>800 ,
            'prix'  => 340,
        ],*/
                    /*Larg=900*/
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 500,
                        'largeur'  => 900,
                        'prix'  => 534,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 600,
                        'largeur'  => 900,
                        'prix'  => 562,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 700,
                        'largeur'  => 900,
                        'prix'  => 588,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 800,
                        'largeur'  => 900,
                        'prix'  => 616,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 900,
                        'largeur'  => 900,
                        'prix'  => 643,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1000,
                        'largeur'  => 900,
                        'prix'  => 669,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1100,
                        'largeur'  => 900,
                        'prix'  => 697,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1200,
                        'largeur'  => 900,
                        'prix'  => 723,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1300,
                        'largeur'  => 900,
                        'prix'  => 751,
                    ],
                    /*
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>900 ,
            'prix'  => 301,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>900 ,
            'prix'  => 332,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>900 ,
            'prix'  => 343,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>900 ,
            'prix'  => 354,
        ],*/
                    /*larg=1000*/
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 500,
                        'largeur'  => 1000,
                        'prix'  => 558,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 600,
                        'largeur'  => 1000,
                        'prix'  => 590,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 700,
                        'largeur'  => 1000,
                        'prix'  => 617,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 800,
                        'largeur'  => 1000,
                        'prix'  => 645,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 900,
                        'largeur'  => 1000,
                        'prix'  => 673,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1000,
                        'largeur'  => 1000,
                        'prix'  => 700,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1100,
                        'largeur'  => 1000,
                        'prix'  => 728,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1200,
                        'largeur'  => 1000,
                        'prix'  => 755,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1300,
                        'largeur'  => 1000,
                        'prix'  => 783,
                    ],
                    /*
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1000 ,
            'prix'  =>334 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1000 ,
            'prix'  => 347,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1000 ,
            'prix'  => 360,
        ],*/
                    /*larg=1100*/
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 500,
                        'largeur'  => 1100,
                        'prix'  => 586,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 600,
                        'largeur'  => 1100,
                        'prix'  => 617,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 700,
                        'largeur'  => 1100,
                        'prix'  => 646,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 800,
                        'largeur'  => 1100,
                        'prix'  => 674,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 900,
                        'largeur'  => 1100,
                        'prix'  => 702,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1000,
                        'largeur'  => 1100,
                        'prix'  => 730,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1100,
                        'largeur'  => 1100,
                        'prix'  => 759,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1200,
                        'largeur'  => 1100,
                        'prix'  => 787,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1300,
                        'largeur'  => 1100,
                        'prix'  => 815,
                    ],
/*
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1100 ,
            'prix'  =>347 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1100 ,
            'prix'  => 360,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1100 ,
            'prix'  => 374,
        ],*/
                    /*larg=1200*/
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 500,
                        'largeur'  => 1200,
                        'prix'  => 613,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 600,
                        'largeur'  => 1200,
                        'prix'  => 645,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 700,
                        'largeur'  => 1200,
                        'prix'  => 674,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 800,
                        'largeur'  => 1200,
                        'prix'  => 703,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 900,
                        'largeur'  => 1200,
                        'prix'  => 732,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1000,
                        'largeur'  => 1200,
                        'prix'  => 761,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1100,
                        'largeur'  => 1200,
                        'prix'  => 790,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1200,
                        'largeur'  => 1200,
                        'prix'  => 819,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1300,
                        'largeur'  => 1200,
                        'prix'  => 848,
                    ],
                    /*
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1200 ,
            'prix'  =>362 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1200 ,
            'prix'  => 374,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1200 ,
            'prix'  => 374,
        ],*/
                    /*larg=1300*/
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 500,
                        'largeur'  => 1300,
                        'prix'  => 640,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 600,
                        'largeur'  => 1300,
                        'prix'  => 674,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 700,
                        'largeur'  => 1300,
                        'prix'  => 703,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 800,
                        'largeur'  => 1300,
                        'prix'  => 733,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 900,
                        'largeur'  => 1300,
                        'prix'  => 762,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1000,
                        'largeur'  => 1300,
                        'prix'  => 792,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1100,
                        'largeur'  => 1300,
                        'prix'  => 821,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1200,
                        'largeur'  => 1300,
                        'prix'  => 851,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1300,
                        'largeur'  => 1300,
                        'prix'  => 880,
                    ],
/*
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1300 ,
            'prix'  =>374 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1300 ,
            'prix'  => 383,
        ],*/
                    /*larg=1400*/
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 500,
                        'largeur'  => 1400,
                        'prix'  => 668,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 600,
                        'largeur'  => 1400,
                        'prix'  => 702,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 700,
                        'largeur'  => 1400,
                        'prix'  => 732,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 800,
                        'largeur'  => 1400,
                        'prix'  => 762,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 900,
                        'largeur'  => 1400,
                        'prix'  => 792,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1000,
                        'largeur'  => 1400,
                        'prix'  => 822,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1100,
                        'largeur'  => 1400,
                        'prix'  => 852,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1200,
                        'largeur'  => 1400,
                        'prix'  => 882,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1300,
                        'largeur'  => 1400,
                        'prix'  => 913,
                    ],
                    /*
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1400 ,
            'prix'  =>388 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1400 ,
            'prix'  => 399,
        ],*/
                    /*larg=1500*/
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 500,
                        'largeur'  => 1500,
                        'prix'  => 715,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 600,
                        'largeur'  => 1500,
                        'prix'  => 730,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 700,
                        'largeur'  => 1500,
                        'prix'  => 760,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 800,
                        'largeur'  => 1500,
                        'prix'  => 791,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 900,
                        'largeur'  => 1500,
                        'prix'  => 821,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1000,
                        'largeur'  => 1500,
                        'prix'  => 852,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1100,
                        'largeur'  => 1500,
                        'prix'  => 883,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1200,
                        'largeur'  => 1500,
                        'prix'  => 913,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1300,
                        'largeur'  => 1500,
                        'prix'  => 945,
                    ],/*
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1500 ,
            'prix'  =>407 ,
        ],*/
                    /*larg=1600*/
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 500,
                        'largeur'  => 1600,
                        'prix'  => 723,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 600,
                        'largeur'  => 1600,
                        'prix'  => 758,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 700,
                        'largeur'  => 1600,
                        'prix'  => 789,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 800,
                        'largeur'  => 1600,
                        'prix'  => 820,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 900,
                        'largeur'  => 1600,
                        'prix'  => 852,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1000,
                        'largeur'  => 1600,
                        'prix'  => 883,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1100,
                        'largeur'  => 1600,
                        'prix'  => 914,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1200,
                        'largeur'  => 1600,
                        'prix'  => 945,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1300,
                        'largeur'  => 1600,
                        'prix'  => 977,
                    ],

                    /*larg=1700*/
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 500,
                        'largeur'  => 1700,
                        'prix'  => 750,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 600,
                        'largeur'  => 1700,
                        'prix'  => 786,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 700,
                        'largeur'  => 1700,
                        'prix'  => 817,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 800,
                        'largeur'  => 1700,
                        'prix'  => 850,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 900,
                        'largeur'  => 1700,
                        'prix'  => 881,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1000,
                        'largeur'  => 1700,
                        'prix'  => 913,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1100,
                        'largeur'  => 1700,
                        'prix'  => 946,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1200,
                        'largeur'  => 1700,
                        'prix'  => 977,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1300,
                        'largeur'  => 1700,
                        'prix'  => 1010,
                    ],
                    /*larg=1800*/
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 500,
                        'largeur'  => 1800,
                        'prix'  => 778,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 600,
                        'largeur'  => 1800,
                        'prix'  => 814,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 700,
                        'largeur'  => 1800,
                        'prix'  => 846,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 800,
                        'largeur'  => 1800,
                        'prix'  => 879,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 900,
                        'largeur'  => 1800,
                        'prix'  => 911,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1000,
                        'largeur'  => 1800,
                        'prix'  => 944,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1100,
                        'largeur'  => 1800,
                        'prix'  => 977,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1200,
                        'largeur'  => 1800,
                        'prix'  => 1009,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1300,
                        'largeur'  => 1800,
                        'prix'  => 1042,
                    ],
                    /*larg=1900*/
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 500,
                        'largeur'  => 1900,
                        'prix'  => 809,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 600,
                        'largeur'  => 1900,
                        'prix'  => 842,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 700,
                        'largeur'  => 1900,
                        'prix'  => 875,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 800,
                        'largeur'  => 1900,
                        'prix'  => 908,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 900,
                        'largeur'  => 1900,
                        'prix'  => 941,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1000,
                        'largeur'  => 1900,
                        'prix'  => 975,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1100,
                        'largeur'  => 1900,
                        'prix'  => 1008,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1200,
                        'largeur'  => 1900,
                        'prix'  => 1041,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1300,
                        'largeur'  => 1900,
                        'prix'  => 1074,
                    ],
                    /*larg=2000*/
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 500,
                        'largeur'  => 2000,
                        'prix'  => 836,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 600,
                        'largeur'  => 2000,
                        'prix'  => 870,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 700,
                        'largeur'  => 2000,
                        'prix'  => 903,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 800,
                        'largeur'  => 2000,
                        'prix'  => 937,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 900,
                        'largeur'  => 2000,
                        'prix'  => 971,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1000,
                        'largeur'  => 2000,
                        'prix'  => 1005,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1100,
                        'largeur'  => 2000,
                        'prix'  => 1039,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1200,
                        'largeur'  => 2000,
                        'prix'  => 1072,
                    ],
                    [
                        'genre'    => 1,
                        'type'    => 1,
                        'couleur'    => 1,
                        'hauteur'    => 1300,
                        'largeur'  => 2000,
                        'prix'  => 1107,
                    ],

                ];

            Modele::insert($modeles);
        }
    }
}
