<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Modele;
use App\Models\Seeders;

class Modeles4Seeder extends Seeder  //3V
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $seeder = Modele::where('type',4)->count();
        // fenetre 3V  pvc
        //Check if the seeder exist in the DB
        if ($seeder==0) {
            $modeles =
            [
            /*larg= 1200*/
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 500,
                    'largeur'  =>1200 ,
                    'prix'  => 359,
				],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    => 1,
                    'hauteur'    =>600 ,
                    'largeur'  =>1200 ,
                    'prix'  => 375,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    => 1,
                    'hauteur'    => 700,
                    'largeur'  =>1200 ,
                    'prix'  => 393,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    => 1,
                    'hauteur'    => 800,
                    'largeur'  =>1200 ,
                    'prix'  => 411,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    => 1,
                    'hauteur'    => 900,
                    'largeur'  =>1200 ,
                    'prix'  => 426,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1000,
                    'largeur'  =>1200 ,
                    'prix'  => 445,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    =>1100 ,
                    'largeur'  =>1200 ,
                    'prix'  => 461,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1200,
                    'largeur'  =>1200 ,
                    'prix'  => 478,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1300,
                    'largeur'  =>1200 ,
                    'prix'  => 496,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1400,
                    'largeur'  =>1200 ,
                    'prix'  => 512,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1500,
                    'largeur'  =>1200 ,
                    'prix'  => 530 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1600,
                    'largeur'  =>1200 ,
                    'prix'  => 544 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1700,
                    'largeur'  =>1200 ,
                    'prix'  => 572 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1800,
                    'largeur'  =>1200 ,
                    'prix'  => 585,
                ],
                [
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1900,
                    'largeur'  =>1200 ,
                    'prix'  => 612 ,
                ],
                [
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2000,
                    'largeur'  =>1200 ,
                    'prix'  => 626,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2100,
                    'largeur'  =>1200 ,
                    'prix'  => 646,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2200,
                    'largeur'  =>1200 ,
                    'prix'  => 665,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2300,
                    'largeur'  =>1200 ,
                    'prix'  => 695,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2400,
                    'largeur'  =>1200 ,
                    'prix'  => 711,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2500,
                    'largeur'  =>1200 ,
                    'prix'  =>737 ,
                ],
                /*larg= 1300*/
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 500,
                    'largeur'  =>1300 ,
                    'prix'  => 365,
				],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    => 1,
                    'hauteur'    =>600 ,
                    'largeur'  =>1300 ,
                    'prix'  => 381,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    => 1,
                    'hauteur'    => 700,
                    'largeur'  =>1300 ,
                    'prix'  => 395,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    => 1,
                    'hauteur'    => 800,
                    'largeur'  =>1300 ,
                    'prix'  => 417,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    => 1,
                    'hauteur'    => 900,
                    'largeur'  =>1300 ,
                    'prix'  => 431,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1000,
                    'largeur'  =>1300 ,
                    'prix'  => 452,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    =>1100 ,
                    'largeur'  =>1300 ,
                    'prix'  => 467,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1200,
                    'largeur'  =>1300 ,
                    'prix'  => 486,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1300,
                    'largeur'  =>1300 ,
                    'prix'  => 500,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1400,
                    'largeur'  =>1300 ,
                    'prix'  => 519,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1500,
                    'largeur'  =>1300 ,
                    'prix'  => 534 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1600,
                    'largeur'  =>1300 ,
                    'prix'  => 553 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1700,
                    'largeur'  =>1300 ,
                    'prix'  => 579 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1800,
                    'largeur'  =>1300 ,
                    'prix'  => 597,
                ],
                [
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1900,
                    'largeur'  =>1300 ,
                    'prix'  => 626 ,
                ],
                [
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2000,
                    'largeur'  =>1300 ,
                    'prix'  => 646,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2100,
                    'largeur'  =>1300 ,
                    'prix'  => 665,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2200,
                    'largeur'  =>1300 ,
                    'prix'  => 684,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2300,
                    'largeur'  =>1300 ,
                    'prix'  => 711,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2400,
                    'largeur'  =>1300 ,
                    'prix'  => 730,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2500,
                    'largeur'  =>1300 ,
                    'prix'  =>761 ,
                ],
            /*larg= 1400*/
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 500,
                    'largeur'  =>1400 ,
                    'prix'  => 371,
				],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    => 1,
                    'hauteur'    =>600 ,
                    'largeur'  =>1400 ,
                    'prix'  => 390,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    => 1,
                    'hauteur'    => 700,
                    'largeur'  =>1400 ,
                    'prix'  => 402,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    => 1,
                    'hauteur'    => 800,
                    'largeur'  =>1400 ,
                    'prix'  => 423,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    => 1,
                    'hauteur'    => 900,
                    'largeur'  =>1400 ,
                    'prix'  => 436,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1000,
                    'largeur'  =>1400 ,
                    'prix'  => 458,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    =>1100 ,
                    'largeur'  =>1400 ,
                    'prix'  => 474,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1200,
                    'largeur'  =>1400 ,
                    'prix'  => 493,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1300,
                    'largeur'  =>1400 ,
                    'prix'  => 509,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1400,
                    'largeur'  =>1400 ,
                    'prix'  => 526,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1500,
                    'largeur'  =>1400 ,
                    'prix'  => 541 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1600,
                    'largeur'  =>1400 ,
                    'prix'  => 560 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1700,
                    'largeur'  =>1400 ,
                    'prix'  => 591 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1800,
                    'largeur'  =>1400 ,
                    'prix'  => 612,
                ],
                [
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1900,
                    'largeur'  =>1400 ,
                    'prix'  => 642 ,
                ],
                [
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2000,
                    'largeur'  =>1400 ,
                    'prix'  => 656,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2100,
                    'largeur'  =>1400 ,
                    'prix'  => 679,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2200,
                    'largeur'  =>1400 ,
                    'prix'  => 699,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2300,
                    'largeur'  =>1400 ,
                    'prix'  => 728,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2400,
                    'largeur'  =>1400 ,
                    'prix'  => 749,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2500,
                    'largeur'  =>1400 ,
                    'prix'  =>776 ,
                ],

            /*Larg= 1500*/
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    =>1 ,
                'hauteur'    => 500,
                'largeur'  =>1500 ,
                'prix'  => 376,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    => 1,
                'hauteur'    =>600 ,
                'largeur'  =>1500 ,
                'prix'  => 376,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    => 1,
                'hauteur'    => 700,
                'largeur'  =>1500 ,
                'prix'  => 376,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    => 1,
                'hauteur'    => 800,
                'largeur'  =>1500 ,
                'prix'  => 429,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    => 1,
                'hauteur'    => 900,
                'largeur'  =>1500 ,
                'prix'  => 444,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    =>1 ,
                'hauteur'    => 1000,
                'largeur'  =>1500 ,
                'prix'  => 468,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    =>1 ,
                'hauteur'    =>1100 ,
                'largeur'  =>1500 ,
                'prix'  => 482,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    =>1 ,
                'hauteur'    => 1200,
                'largeur'  =>1500 ,
                'prix'  => 496,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    =>1 ,
                'hauteur'    => 1300,
                'largeur'  =>1500 ,
                'prix'  => 514,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    =>1 ,
                'hauteur'    => 1400,
                'largeur'  =>1500 ,
                'prix'  => 530,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    =>1 ,
                'hauteur'    => 1500,
                'largeur'  =>1500 ,
                'prix'  => 553,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    =>1 ,
                'hauteur'    => 1600,
                'largeur'  =>1500 ,
                'prix'  =>572 ,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    =>1 ,
                'hauteur'    => 1700,
                'largeur'  =>1500 ,
                'prix'  => 605,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    =>1 ,
                'hauteur'    => 1800,
                'largeur'  =>1500 ,
                'prix'  => 622,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    =>1 ,
                'hauteur'    => 1900,
                'largeur'  =>1500 ,
                'prix'  => 656,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    =>1 ,
                'hauteur'    => 2000,
                'largeur'  =>1500 ,
                'prix'  => 671,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    =>1 ,
                'hauteur'    => 2100,
                'largeur'  =>1500 ,
                'prix'  => 695,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    =>1 ,
                'hauteur'    => 2200,
                'largeur'  =>1500 ,
                'prix'  => 717,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    =>1 ,
                'hauteur'    => 2300,
                'largeur'  =>1500 ,
                'prix'  => 742,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    =>1 ,
                'hauteur'    => 2400,
                'largeur'  =>1500 ,
                'prix'  => 746,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    =>1 ,
                'hauteur'    => 2500,
                'largeur'  =>1500 ,
                'prix'  => 793,
            ],
        /*Larg=1600*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>1600 ,
            'prix'  => 387,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1600 ,
            'prix'  => 403,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1600 ,
            'prix'  => 417,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1600 ,
            'prix'  => 437,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1600 ,
            'prix'  => 453,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1600 ,
            'prix'  => 474,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1600 ,
            'prix'  => 488,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1600 ,
            'prix'  => 509,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1600 ,
            'prix'  => 523,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1600 ,
            'prix'  => 544,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1600 ,
            'prix'  => 567,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1600 ,
            'prix'  => 591,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1600 ,
            'prix'  => 622,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1600 ,
            'prix'  => 642,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1600 ,
            'prix'  => 676,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1600 ,
            'prix'  => 695,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1600 ,
            'prix'  => 711,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1600 ,
            'prix'  => 735,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1600 ,
            'prix'  => 767,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1600 ,
            'prix'  => 787,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1600 ,
            'prix'  => 817,
        ],

        /*larg=1700*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>1700 ,
            'prix'  => 394,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1700 ,
            'prix'  => 406,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1700 ,
            'prix'  => 423,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1700 ,
            'prix'  => 444,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1700 ,
            'prix'  => 458,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1700 ,
            'prix'  => 478,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1700 ,
            'prix'  => 493,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1700 ,
            'prix'  => 512,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1700 ,
            'prix'  => 534,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1700 ,
            'prix'  => 560,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1700 ,
            'prix'  => 579,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1700 ,
            'prix'  => 601,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1700 ,
            'prix'  => 635,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1700 ,
            'prix'  => 656,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1700 ,
            'prix'  => 690,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1700 ,
            'prix'  => 707,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1700 ,
            'prix'  => 730,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1700 ,
            'prix'  => 749,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1700 ,
            'prix'  => 785,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1700 ,
            'prix'  => 807,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1700 ,
            'prix'  => 835,
        ],

        /*Larg=1800*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>1800 ,
            'prix'  => 399,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1800 ,
            'prix'  => 415,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1800 ,
            'prix'  => 429,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1800 ,
            'prix'  => 448,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1800 ,
            'prix'  => 468,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1800 ,
            'prix'  => 486,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1800 ,
            'prix'  => 500,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1800 ,
            'prix'  => 523,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1800 ,
            'prix'  => 544,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1800 ,
            'prix'  => 572,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1800 ,
            'prix'  => 591,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1800 ,
            'prix'  => 612,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1800 ,
            'prix'  => 650,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1800 ,
            'prix'  => 671,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1800 ,
            'prix'  => 705,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1800 ,
            'prix'  => 726,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1800 ,
            'prix'  => 746,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1800 ,
            'prix'  => 767,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1800 ,
            'prix'  => 798,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1800 ,
            'prix'  => 819,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1800 ,
            'prix'  => 851,
        ],
        /*larg=1900*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1900 ,
            'prix'  => 403,//ici
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1900 ,
            'prix'  => 423,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1900 ,
            'prix'  => 437,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1900 ,
            'prix'  => 455,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1900 ,
            'prix'  => 471,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1900 ,
            'prix'  => 488,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1900 ,
            'prix'  => 512,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1900 ,
            'prix'  => 534,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1900 ,
            'prix'  => 560,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1900 ,
            'prix'  => 581,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1900 ,
            'prix'  =>605 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1900 ,
            'prix'  => 626,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1900 ,
            'prix'  => 665,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1900 ,
            'prix'  => 686,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1900 ,
            'prix'  => 721,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1900 ,
            'prix'  => 738,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1900 ,
            'prix'  => 761,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1900 ,
            'prix'  => 787,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1900 ,
            'prix'  => 817,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1900 ,
            'prix'  => 844,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1900 ,
            'prix'  => 873,
        ],
        /*larg=2000*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>2000 ,
            'prix'  => 411,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>2000 ,
            'prix'  => 427,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2000 ,
            'prix'  => 441,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2000 ,
            'prix'  => 461,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2000 ,
            'prix'  => 478,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2000 ,
            'prix'  => 496,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2000 ,
            'prix'  => 523,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2000 ,
            'prix'  => 544,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2000 ,
            'prix'  => 572,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2000 ,
            'prix'  => 597,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2000 ,
            'prix'  => 615,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2000 ,
            'prix'  => 642,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2000 ,
            'prix'  => 679,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2000 ,
            'prix'  => 700,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2000 ,
            'prix'  => 735,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2000 ,
            'prix'  => 753,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>2000 ,
            'prix'  => 780,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2000 ,
            'prix'  => 803,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>2000 ,
            'prix'  => 835,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>2000 ,
            'prix'  => 858,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>2000 ,
            'prix'  => 889,
        ],
        /*larg=2100*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>2100 ,
            'prix'  => 441,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2100 ,
            'prix'  => 455,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2100 ,
            'prix'  => 474,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2100 ,
            'prix'  => 493,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2100 ,
            'prix'  => 514,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2100 ,
            'prix'  => 541,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2100 ,
            'prix'  => 562,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2100 ,
            'prix'  => 591,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2100 ,
            'prix'  => 615,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2100 ,
            'prix'  =>639 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2100 ,
            'prix'  => 665,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2100 ,
            'prix'  => 699,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2100 ,
            'prix'  => 726,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2100 ,
            'prix'  => 759,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2100 ,
            'prix'  => 776,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>2100 ,
            'prix'  => 803,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2100 ,
            'prix'  => 823,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>2100 ,
            'prix'  => 858,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>2100 ,
            'prix'  => 883,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>2100 ,
            'prix'  => 914,
        ],

        /*larg=2200*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>2200 ,
            'prix'  => 448,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2200 ,
            'prix'  => 461,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2200 ,
            'prix'  => 482,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2200 ,
            'prix'  => 496,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2200 ,
            'prix'  => 526,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2200 ,
            'prix'  => 553,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2200 ,
            'prix'  => 579,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2200 ,
            'prix'  => 601,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2200 ,
            'prix'  => 630,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2200 ,
            'prix'  =>654 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2200 ,
            'prix'  => 679,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2200 ,
            'prix'  => 711,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2200 ,
            'prix'  => 738,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2200 ,
            'prix'  => 787,//vide ici
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2200 ,
            'prix'  => 793,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>2200 ,
            'prix'  => 819,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2200 ,
            'prix'  => 844,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>2200 ,
            'prix'  => 881,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>2200 ,
            'prix'  => 902,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>2200 ,
            'prix'  => 933,
        ],

        /*larg=2300*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>2300 ,
            'prix'  => 453,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2300 ,
            'prix'  => 468,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2300 ,
            'prix'  => 488,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2300 ,
            'prix'  => 509,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2300 ,
            'prix'  => 538,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2300 ,
            'prix'  => 562,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2300 ,
            'prix'  => 591,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2300 ,
            'prix'  => 612,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2300 ,
            'prix'  => 642,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2300 ,
            'prix'  =>669 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2300 ,
            'prix'  => 690,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2300 ,
            'prix'  => 728,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2300 ,
            'prix'  => 753,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2300 ,
            'prix'  => 787,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2300 ,
            'prix'  => 810,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>2300 ,
            'prix'  => 835,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2300 ,
            'prix'  => 858,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>2300 ,
            'prix'  => 895,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>2300 ,
            'prix'  => 923,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>2300 ,
            'prix'  => 953,
        ],

        /*larg=2400*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>2400 ,
            'prix'  => 458,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2400 ,
            'prix'  => 474,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2400 ,
            'prix'  => 493,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2400 ,
            'prix'  => 514,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2400 ,
            'prix'  => 551,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2400 ,
            'prix'  => 572,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2400 ,
            'prix'  => 601,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2400 ,
            'prix'  => 626,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2400 ,
            'prix'  => 654,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2400 ,
            'prix'  =>679 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2400 ,
            'prix'  => 705,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2400 ,
            'prix'  => 738,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2400 ,
            'prix'  => 764,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2400 ,
            'prix'  => 803,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2400 ,
            'prix'  => 823,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>2400 ,
            'prix'  => 851,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2400 ,
            'prix'  => 876,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>2400 ,
            'prix'  => 910,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>2400 ,
            'prix'  => 935,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>2400 ,
            'prix'  => 970,
        ],

        /*larg=2500*/

        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>2500 ,
            'prix'  => 468,//
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2500 ,
            'prix'  => 482,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2500 ,
            'prix'  => 500,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2500 ,
            'prix'  => 526,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2500 ,
            'prix'  => 556,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2500 ,
            'prix'  => 585,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2500 ,
            'prix'  => 612,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2500 ,
            'prix'  => 639,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2500 ,
            'prix'  => 669,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2500 ,
            'prix'  => 695,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2500 ,
            'prix'  => 721,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2500 ,
            'prix'  => 759,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2500 ,
            'prix'  => 785,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2500 ,
            'prix'  =>817 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2500 ,
            'prix'  =>840 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>2500 ,
            'prix'  => 869,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2500 ,
            'prix'  => 895,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>2500 ,
            'prix'  => 930,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>2500 ,
            'prix'  => 958,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>2500 ,
            'prix'  => 988,
        ],
        /*larg=2600*/// here

        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2600 ,
            'prix'  => 486,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2600 ,
            'prix'  => 509,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 900,
            'largeur'  =>2600 ,
            'prix'  => 538,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1000 ,
            'largeur'  =>2600 ,
            'prix'  => 567,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2600 ,
            'prix'  => 594,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2600 ,
            'prix'  => 622,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2600 ,
            'prix'  => 650,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2600 ,
            'prix'  => 679,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2600 ,
            'prix'  => 705,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2600 ,
            'prix'  => 730,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2600 ,
            'prix'  => 767,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2600 ,
            'prix'  => 793,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2600 ,
            'prix'  => 833,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2600 ,
            'prix'  => 853,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>2600 ,
            'prix'  => 883,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2600 ,
            'prix'  => 910,
        ],/*
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2600 ,
            'prix'  => 1127,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2600 ,
            'prix'  => 1156,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2600 ,
            'prix'  => 1191,
        ],*/
        /*larg=2700*/

        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2700 ,
            'prix'  => 496,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2700 ,
            'prix'  => 523,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2700 ,
            'prix'  => 551,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2700 ,
            'prix'  => 581,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2700 ,
            'prix'  => 609,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2700 ,
            'prix'  => 639,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2700 ,
            'prix'  => 665,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2700 ,
            'prix'  => 695,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2700 ,
            'prix'  =>721 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2700 ,
            'prix'  => 749,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2700 ,
            'prix'  => 787,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2700 ,
            'prix'  => 815,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2700 ,
            'prix'  => 851,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2700 ,
            'prix'  => 873,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>2700 ,
            'prix'  => 902,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2700 ,
            'prix'  => 930,
        ],/*
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>2700 ,
            'prix'  => 1148,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>2700 ,
            'prix'  => 1179,
        ],*/
        /*larg=2800*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2800 ,
            'prix'  => 503,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1700 ,
            'prix'  => 534,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2800 ,
            'prix'  => 560,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2800 ,
            'prix'  => 594,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2800 ,
            'prix'  => 619,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2800 ,
            'prix'  => 650,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2800 ,
            'prix'  => 679,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2800 ,
            'prix'  => 707,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2800 ,
            'prix'  =>735 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2800 ,
            'prix'  => 764,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2800 ,
            'prix'  => 803,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2800 ,
            'prix'  => 826,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2800 ,
            'prix'  => 869,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2800 ,
            'prix'  => 892,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>2800 ,
            'prix'  => 923,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2800 ,
            'prix'  => 948,
        ],/*
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>2800 ,
            'prix'  => 1168,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>2800 ,
            'prix'  => 1194,
        ],*/
        /*larg=2900*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2900 ,
            'prix'  => 509,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2900 ,
            'prix'  => 541,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2900 ,
            'prix'  => 572,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2900 ,
            'prix'  => 601,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2900 ,
            'prix'  => 630,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2900 ,
            'prix'  => 659,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2900 ,
            'prix'  => 690,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2900 ,
            'prix'  => 721,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2900 ,
            'prix'  =>749 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2900 ,
            'prix'  => 776,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2900 ,
            'prix'  => 817,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2900 ,
            'prix'  => 844,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2900 ,
            'prix'  => 881,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2900 ,
            'prix'  => 907,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>2900 ,
            'prix'  => 935,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2900 ,
            'prix'  => 961,
        ],/*
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>2900 ,
            'prix'  => 1183,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>2900 ,
            'prix'  => 1213,
        ],*/
        /*larg=3000*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>3000 ,
            'prix'  => 519,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>3000 ,
            'prix'  => 551,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>3000 ,
            'prix'  => 579,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>3000 ,
            'prix'  => 612,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>3000 ,
            'prix'  => 642,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>3000 ,
            'prix'  => 671,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>3000 ,
            'prix'  => 702,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>3000 ,
            'prix'  => 730,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>3000 ,
            'prix'  =>761 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>3000 ,
            'prix'  => 790,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>3000 ,
            'prix'  => 826,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>3000 ,
            'prix'  => 858,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>3000 ,
            'prix'  => 895,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>3000 ,
            'prix'  => 923,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>3000 ,
            'prix'  => 953,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>3000 ,
            'prix'  => 977,
        ],/*
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>3000 ,
            'prix'  => 1196,
        ],*/
        /*larg=3100*/

        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>3100 ,
            'prix'  => 526,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>3100 ,
            'prix'  => 560,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>3100 ,
            'prix'  => 591,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>3100 ,
            'prix'  => 622,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>3100 ,
            'prix'  => 654,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>3100 ,
            'prix'  => 684,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>3100 ,
            'prix'  => 711,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>3100 ,
            'prix'  => 746,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>3100 ,
            'prix'  =>776 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>3100 ,
            'prix'  => 807,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>3100 ,
            'prix'  => 844,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>3100 ,
            'prix'  => 873,
        ],
        /*larg=3200*/

        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>3200 ,
            'prix'  => 538,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>3200 ,
            'prix'  => 572,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>3200 ,
            'prix'  => 601,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>3200 ,
            'prix'  => 635,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>3200 ,
            'prix'  => 665,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>3200 ,
            'prix'  => 695,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>3200 ,
            'prix'  => 726,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>3200 ,
            'prix'  => 759,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>3200 ,
            'prix'  =>787 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>3200 ,
            'prix'  => 817,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>3200 ,
            'prix'  => 858,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>3200 ,
            'prix'  => 889,
        ],
        /*larg=3300*/

        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>3300 ,
            'prix'  => 579,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>3300 ,
            'prix'  => 609,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>3300 ,
            'prix'  => 646,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>3300 ,
            'prix'  =>676 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>3300 ,
            'prix'  => 705 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>3300 ,
            'prix'  => 735 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>3300 ,
            'prix'  => 767 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>3300 ,
            'prix'  =>798 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>3300 ,
            'prix'  => 833,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>3300 ,
            'prix'  => 869,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>3300 ,
            'prix'  => 902,
        ],

        /*larg=3400*/

        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>3400 ,
            'prix'  => 591,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>3400 ,
            'prix'  => 619,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>3400 ,
            'prix'  => 656,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>3400 ,
            'prix'  => 686,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>3400 ,
            'prix'  => 721,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>3400 ,
            'prix'  => 749,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>3400 ,
            'prix'  => 785,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>3400 ,
            'prix'  =>815 ,
        ],
         /*larg=3500*/

        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>3500 ,
            'prix'  => 601,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>3500 ,
            'prix'  => 630,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>3500 ,
            'prix'  => 669,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>3500 ,
            'prix'  => 699,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>3500 ,
            'prix'  => 730,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>3500 ,
            'prix'  => 761,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>3500 ,
            'prix'  => 793,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>3500 ,
            'prix'  =>826 ,
        ],

        /*larg=3600*//*
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>3600 ,
            'prix'  => 764,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>3600 ,
            'prix'  => 774,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>3600 ,
            'prix'  => 812,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>3600 ,
            'prix'  => 841,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>3600 ,
            'prix'  => 875,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>3600 ,
            'prix'  => 901,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>3600 ,
            'prix'  => 934,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>3600 ,
            'prix'  =>966 ,
        ],*/
    ];

            Modele::insert($modeles);

        }


    }
}
