<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Modele;
use App\Models\Seeders;

class Modeles6Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $seeder = Modele::where('type',6)->count();

        //Check if the seeder exist in the DB
        if ($seeder==0) {
            $modeles =
            [

            /*Larg= 1200*/
            [
                'genre'    =>1 ,
				'type'    =>6 ,
                'couleur'    =>1 ,
                'hauteur'    => 2000,
                'largeur'  =>1200 ,
                'prix'  => 2419,
            ],
            [
                'genre'    =>1 ,
				'type'    =>6 ,
                'couleur'    => 1,
                'hauteur'    =>2100 ,
                'largeur'  =>1200 ,
                'prix'  => 2494,
            ],
            [
                'genre'    =>1 ,
				'type'    =>6 ,
                'couleur'    => 1,
                'hauteur'    => 2200,
                'largeur'  =>1200 ,
                'prix'  => 2557,
            ],
            [
                'genre'    =>1 ,
				'type'    =>6 ,
                'couleur'    => 1,
                'hauteur'    => 2300,
                'largeur'  =>1200 ,
                'prix'  => 2669,
            ],
            [
                'genre'    =>1 ,
				'type'    =>6 ,
                'couleur'    => 1,
                'hauteur'    => 2400,
                'largeur'  =>1200 ,
                'prix'  => 2696,
            ],
            [
                'genre'    =>1 ,
				'type'    =>6 ,
                'couleur'    =>1 ,
                'hauteur'    => 2500,
                'largeur'  =>1200 ,
                'prix'  => 2768,
            ],
            /* couleur 2*/
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>6 ,
                'couleur'    =>2 ,
                'hauteur'    => 2000,
                'largeur'  =>1200 ,
                'prix'  => 2696,
            ],
            [
                'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
                'couleur'    => 2,
                'hauteur'    => 2100,
                'largeur'  =>1200 ,
                'prix'  => 2785,
            ],
            [
                'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
                'couleur'    =>2 ,
                'hauteur'    => 2200,
                'largeur'  =>1200 ,
                'prix'  => 2868,
            ],
            [
                'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
                'couleur'    =>2 ,
                'hauteur'    => 2300,
                'largeur'  =>1200 ,
                'prix'  => 2972,
            ],
            [
                'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
                'couleur'    => 2,
                'hauteur'    => 2400,
                'largeur'  =>1200 ,
                'prix'  => 3058,
            ],
            [
                'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
                'couleur'    =>2 ,
                'hauteur'    => 2500,
                'largeur'  =>1200 ,
                'prix'  => 3103,
            ],

            /* couleur 3*/
            [
                'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
                'couleur'    =>3 ,
                'hauteur'    => 2000,
                'largeur'  =>1200 ,
                'prix'  => 2985,
            ],
            [
                'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
                'couleur'    =>3 ,
                'hauteur'    => 2100,
                'largeur'  =>1200 ,
                'prix'  => 3070,
            ],
            [
                'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
                'couleur'    =>3 ,
                'hauteur'    => 2200,
                'largeur'  =>1200 ,
                'prix'  => 3181,
            ],
            [
                'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
                'couleur'    =>3 ,
                'hauteur'    => 2300,
                'largeur'  =>1200 ,
                'prix'  => 3291,
            ],
            [
                'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
                'couleur'    =>3 ,
                'hauteur'    => 2400,
                'largeur'  =>1200 ,
                'prix'  => 3375,
            ],
            [
                'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
                'couleur'    =>3 ,
                'hauteur'    => 2500,
                'largeur'  =>1200 ,
                'prix'  => 3429,
            ],

        /*Larg=1300*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1300 ,
            'prix'  => 2494,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    =>2100 ,
            'largeur'  =>1300 ,
            'prix'  => 2569,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 2200,
            'largeur'  =>1300 ,
            'prix'  => 2644,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 2300,
            'largeur'  =>1300 ,
            'prix'  => 2747,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 2400,
            'largeur'  =>1300 ,
            'prix'  => 2785,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1300 ,
            'prix'  => 2861,
        ],

        /* couleur 2*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>2 ,
            'hauteur'    => 2000,
            'largeur'  =>1300 ,
            'prix'  => 2785,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 2,
            'hauteur'    => 2100,
            'largeur'  =>1300 ,
            'prix'  => 2868,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>2 ,
            'hauteur'    => 2200,
            'largeur'  =>1300 ,
            'prix'  => 2939,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>2 ,
            'hauteur'    => 2300,
            'largeur'  =>1300 ,
            'prix'  => 3058,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 2,
            'hauteur'    => 2400,
            'largeur'  =>1300 ,
            'prix'  => 3150,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>2 ,
            'hauteur'    => 2500,
            'largeur'  =>1300 ,
            'prix'  => 3186,
        ],

        /* couleur 3*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2000,
            'largeur'  =>1300 ,
            'prix'  => 3070,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2100,
            'largeur'  =>1300 ,
            'prix'  => 3157,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2200,
            'largeur'  =>1300 ,
            'prix'  => 3257,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2300,
            'largeur'  =>1300 ,
            'prix'  => 3386,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2400,
            'largeur'  =>1300 ,
            'prix'  => 3480,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2500,
            'largeur'  =>1300 ,
            'prix'  => 3528,
        ],

        /*larg=1400*/

        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1400 ,
            'prix'  => 2569,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    =>2100 ,
            'largeur'  =>1400 ,
            'prix'  => 2644,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 2200,
            'largeur'  =>1400 ,
            'prix'  => 2715,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 2300,
            'largeur'  =>1400 ,
            'prix'  => 2829,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 2400,
            'largeur'  =>1400 ,
            'prix'  => 2868,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1400 ,
            'prix'  => 2939,
        ],

        /* couleur 2*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>2 ,
            'hauteur'    => 2000,
            'largeur'  =>1400 ,
            'prix'  => 2909,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 2,
            'hauteur'    => 2100,
            'largeur'  =>1400 ,
            'prix'  => 2992,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>2 ,
            'hauteur'    => 2200,
            'largeur'  =>1400 ,
            'prix'  => 3089,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>2 ,
            'hauteur'    => 2300,
            'largeur'  =>1400 ,
            'prix'  => 3196,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 2,
            'hauteur'    => 2400,
            'largeur'  =>1400 ,
            'prix'  => 3291,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>2 ,
            'hauteur'    => 2500,
            'largeur'  =>1400 ,
            'prix'  => 3335,
        ],

        /* couleur 3*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2000,
            'largeur'  =>1400 ,
            'prix'  => 3210,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2100,
            'largeur'  =>1400 ,
            'prix'  => 3303,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2200,
            'largeur'  =>1400 ,
            'prix'  => 3402,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2300,
            'largeur'  =>1400 ,
            'prix'  => 3528,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2400,
            'largeur'  =>1400 ,
            'prix'  => 3621,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2500,
            'largeur'  =>1400 ,
            'prix'  => 3681,
        ],

        /*Larg=1500*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1500 ,
            'prix'  => 2644,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    =>2100 ,
            'largeur'  =>1500 ,
            'prix'  => 2715,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 2200,
            'largeur'  =>1500 ,
            'prix'  => 2798,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 2300,
            'largeur'  =>1500 ,
            'prix'  => 2909,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 2400,
            'largeur'  =>1500 ,
            'prix'  => 2939,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1500 ,
            'prix'  => 3038,
        ],

        /* couleur 2*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>2 ,
            'hauteur'    => 2000,
            'largeur'  =>1500 ,
            'prix'  => 2992,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 2,
            'hauteur'    => 2100,
            'largeur'  =>1500 ,
            'prix'  => 3089,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>2 ,
            'hauteur'    => 2200,
            'largeur'  =>1500 ,
            'prix'  => 3181,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>2 ,
            'hauteur'    => 2300,
            'largeur'  =>1500 ,
            'prix'  => 3291,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 2,
            'hauteur'    => 2400,
            'largeur'  =>1500 ,
            'prix'  => 3375,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>2 ,
            'hauteur'    => 2500,
            'largeur'  =>1500 ,
            'prix'  => 3429,
        ],

        /* couleur 3*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2000,
            'largeur'  =>1500 ,
            'prix'  => 3291,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2100,
            'largeur'  =>1500 ,
            'prix'  => 3386,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2200,
            'largeur'  =>1500 ,
            'prix'  =>3494 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2300,
            'largeur'  =>1500 ,
            'prix'  => 3621,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2400,
            'largeur'  =>1500 ,
            'prix'  => 3718,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2500,
            'largeur'  =>1500 ,
            'prix'  => 3759,
        ],

        /*larg=1600*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1600 ,
            'prix'  => 2715,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    =>2100 ,
            'largeur'  =>1600 ,
            'prix'  => 2798,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 2200,
            'largeur'  =>1600 ,
            'prix'  => 2885,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 2300,
            'largeur'  =>1600 ,
            'prix'  => 2992,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 2400,
            'largeur'  =>1600 ,
            'prix'  => 3038,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1600 ,
            'prix'  => 3118,
        ],

        /* couleur 2*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>2 ,
            'hauteur'    => 2000,
            'largeur'  =>1600 ,
            'prix'  => 3046,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 2,
            'hauteur'    => 2100,
            'largeur'  =>1600 ,
            'prix'  => 3150,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>2 ,
            'hauteur'    => 2200,
            'largeur'  =>1600 ,
            'prix'  => 3235,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>2 ,
            'hauteur'    => 2300,
            'largeur'  =>1600 ,
            'prix'  => 3358,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 2,
            'hauteur'    => 2400,
            'largeur'  =>1600 ,
            'prix'  => 3446,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>2 ,
            'hauteur'    => 2500,
            'largeur'  =>1600 ,
            'prix'  => 3499,
        ],

        /* couleur 3*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2000,
            'largeur'  =>1600 ,
            'prix'  => 3344,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2100,
            'largeur'  =>1600 ,
            'prix'  => 3460,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2200,
            'largeur'  =>1600 ,
            'prix'  => 3558,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2300,
            'largeur'  =>1600 ,
            'prix'  => 3686,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2400,
            'largeur'  =>1600 ,
            'prix'  => 3791,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2500,
            'largeur'  =>1600 ,
            'prix'  => 3842,
        ],


        /*larg=1700*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1700 ,
            'prix'  => 2798,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    =>2100 ,
            'largeur'  =>1700 ,
            'prix'  => 2868,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 2200,
            'largeur'  =>1700 ,
            'prix'  => 2965,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 2300,
            'largeur'  =>1700 ,
            'prix'  => 3070,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 2400,
            'largeur'  =>1700 ,
            'prix'  => 3118,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 2500,
            'largeur'  =>1700 ,
            'prix'  => 3196,
        ],
        /* couleur 2*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>2 ,
            'hauteur'    => 2000,
            'largeur'  =>1700 ,
            'prix'  => 3133,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 2,
            'hauteur'    => 2100,
            'largeur'  =>1700 ,
            'prix'  => 3222,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>2 ,
            'hauteur'    => 2200,
            'largeur'  =>1700 ,
            'prix'  => 3324,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>2 ,
            'hauteur'    => 2300,
            'largeur'  =>1700 ,
            'prix'  => 3446,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 2,
            'hauteur'    => 2400,
            'largeur'  =>1700 ,
            'prix'  => 3539,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 2,
            'hauteur'    => 2500,
            'largeur'  =>1700 ,
            'prix'  => 3590,
        ],
        /* couleur 3*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2000,
            'largeur'  =>1700 ,
            'prix'  => 3434,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2100,
            'largeur'  =>1700 ,
            'prix'  => 3553,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2200,
            'largeur'  =>1700 ,
            'prix'  => 3652,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2300,
            'largeur'  =>1700 ,
            'prix'  => 3791,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2400,
            'largeur'  =>1700 ,
            'prix'  => 3885,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2500,
            'largeur'  =>1700 ,
            'prix'  => 3947,
        ],
        /*larg=1800*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1800 ,
            'prix'  => 2893,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    =>2100 ,
            'largeur'  =>1800 ,
            'prix'  => 2985,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 2200,
            'largeur'  =>1800 ,
            'prix'  => 3070,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 2300,
            'largeur'  =>1800 ,
            'prix'  => 3196,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 2400,
            'largeur'  =>1800 ,
            'prix'  => 3235,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 2400,
            'largeur'  =>1800 ,
            'prix'  => 3324,
        ],
        /* couleur 2*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>2 ,
            'hauteur'    => 2000,
            'largeur'  =>1800 ,
            'prix'  => 3210,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 2,
            'hauteur'    => 2100,
            'largeur'  =>1800 ,
            'prix'  => 3308,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>2 ,
            'hauteur'    => 2200,
            'largeur'  =>1800 ,
            'prix'  => 3415,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>2 ,
            'hauteur'    => 2300,
            'largeur'  =>1800 ,
            'prix'  => 3539,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 2,
            'hauteur'    => 2400,
            'largeur'  =>1800 ,
            'prix'  => 3638,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 2,
            'hauteur'    => 2500,
            'largeur'  =>1800 ,
            'prix'  => 3686,
        ],
        /* couleur 3*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2000,
            'largeur'  =>1800 ,
            'prix'  => 3528,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2100,
            'largeur'  =>1800 ,
            'prix'  => 3638,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2200,
            'largeur'  =>1800 ,
            'prix'  => 3745,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2300,
            'largeur'  =>1800 ,
            'prix'  => 3873,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2400,
            'largeur'  =>1800 ,
            'prix'  => 3992,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2500,
            'largeur'  =>1800 ,
            'prix'  => 4043,
        ],
        /*larg=1900*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1900 ,
            'prix'  => 2972,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    =>2100 ,
            'largeur'  =>1900 ,
            'prix'  => 3058,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 2200,
            'largeur'  =>1900 ,
            'prix'  => 3150,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 2300,
            'largeur'  =>1900 ,
            'prix'  => 3271,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 2400,
            'largeur'  =>1900 ,
            'prix'  => 3324,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 2500,
            'largeur'  =>1900 ,
            'prix'  => 3415,
        ],
        /* couleur 2*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>2 ,
            'hauteur'    => 2000,
            'largeur'  =>1900 ,
            'prix'  => 3303,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 2,
            'hauteur'    => 2100,
            'largeur'  =>1900 ,
            'prix'  => 3402,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>2 ,
            'hauteur'    => 2200,
            'largeur'  =>1900 ,
            'prix'  => 3499,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>2 ,
            'hauteur'    => 2300,
            'largeur'  =>1900 ,
            'prix'  => 3621,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 2,
            'hauteur'    => 2400,
            'largeur'  =>1900 ,
            'prix'  => 3730,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 2,
            'hauteur'    => 2500,
            'largeur'  =>1900 ,
            'prix'  => 3772,
        ],
        /* couleur 3*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2000,
            'largeur'  =>1900 ,
            'prix'  => 3614,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2100,
            'largeur'  =>1900 ,
            'prix'  => 3730,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2200,
            'largeur'  =>1900 ,
            'prix'  => 3842,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2300,
            'largeur'  =>1900 ,
            'prix'  => 3978,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2400,
            'largeur'  =>1900 ,
            'prix'  => 4082,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2500,
            'largeur'  =>1900 ,
            'prix'  => 4141,
        ],

       /*larg=2000*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2000 ,
            'prix'  => 3046,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    =>2100 ,
            'largeur'  =>2000 ,
            'prix'  => 3150,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 2200,
            'largeur'  =>2000 ,
            'prix'  => 3235,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 2300,
            'largeur'  =>2000 ,
            'prix'  => 3358,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 2400,
            'largeur'  =>2000 ,
            'prix'  => 3402,
        ],

        /* couleur 2*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>2 ,
            'hauteur'    => 2000,
            'largeur'  =>2000 ,
            'prix'  => 3375,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 2,
            'hauteur'    => 2100,
            'largeur'  =>2000 ,
            'prix'  => 3480,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>2 ,
            'hauteur'    => 2200,
            'largeur'  =>2000 ,
            'prix'  => 3573,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>2 ,
            'hauteur'    => 2300,
            'largeur'  =>2000 ,
            'prix'  => 3718,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 2,
            'hauteur'    => 2400,
            'largeur'  =>2000 ,
            'prix'  => 3820,
        ],

        /* couleur 3*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2000,
            'largeur'  =>2000 ,
            'prix'  => 3709,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2100,
            'largeur'  =>2000 ,
            'prix'  => 3820,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2200,
            'largeur'  =>2000 ,
            'prix'  => 3930,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2300,
            'largeur'  =>2000 ,
            'prix'  => 4066,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2400,
            'largeur'  =>2000 ,
            'prix'  => 4180,
        ],

       /*larg=2100*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2100 ,
            'prix'  => 3118,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    =>2100 ,
            'largeur'  =>2100 ,
            'prix'  => 3222,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 2200,
            'largeur'  =>2100 ,
            'prix'  => 3308,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 2300,
            'largeur'  =>2100 ,
            'prix'  => 3434,
        ],
        /* couleur 2*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>2 ,
            'hauteur'    => 2000,
            'largeur'  =>2100 ,
            'prix'  => 3446,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 2,
            'hauteur'    => 2100,
            'largeur'  =>2100 ,
            'prix'  => 3558,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>2 ,
            'hauteur'    => 2200,
            'largeur'  =>2100 ,
            'prix'  => 3660,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>2 ,
            'hauteur'    => 2300,
            'largeur'  =>2100 ,
            'prix'  => 3805,
        ],

        /* couleur 3*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2000,
            'largeur'  =>2100 ,
            'prix'  => 3791,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2100,
            'largeur'  =>2100 ,
            'prix'  => 3898,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2200,
            'largeur'  =>2100 ,
            'prix'  => 4010,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2300,
            'largeur'  =>2100 ,
            'prix'  => 4163,
        ],

       /*larg=2200*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2200 ,
            'prix'  => 3157,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    =>2100 ,
            'largeur'  =>2200 ,
            'prix'  => 3257,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 2200,
            'largeur'  =>2200 ,
            'prix'  => 334,
        ],

        /* couleur 2*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>2 ,
            'hauteur'    => 2000,
            'largeur'  =>2200 ,
            'prix'  => 3499,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 2,
            'hauteur'    => 2100,
            'largeur'  =>2200 ,
            'prix'  => 3604,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>2 ,
            'hauteur'    => 2200,
            'largeur'  =>2200 ,
            'prix'  => 3718,
        ],
        /* couleur 3*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2000,
            'largeur'  =>2200 ,
            'prix'  => 3864,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2100,
            'largeur'  =>2200 ,
            'prix'  => 3992,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>3 ,
            'hauteur'    => 2200,
            'largeur'  =>2200 ,
            'prix'  => 4106,
        ],
             ];

            Modele::insert($modeles);

        }


    }
}
