<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Modele;
use App\Models\Seeders;

class Modeles2Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $seeder = Modele::where('type',2)->count();

        //Check if the seeder exist in the DB
        if ($seeder==0) {
            $modeles =
            [
            /*larg= 500*/
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 500,
                    'largeur'  =>500 ,
                    'prix'  =>491 ,
				],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    => 1,
                    'hauteur'    =>600 ,
                    'largeur'  =>500 ,
                    'prix'  => 522,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    => 1,
                    'hauteur'    => 700,
                    'largeur'  =>500 ,
                    'prix'  => 530,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    => 1,
                    'hauteur'    => 800,
                    'largeur'  =>500 ,
                    'prix'  =>556 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    => 1,
                    'hauteur'    => 900,
                    'largeur'  =>500 ,
                    'prix'  => 593,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1000,
                    'largeur'  =>500 ,
                    'prix'  => 615,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    =>1100 ,
                    'largeur'  =>500 ,
                    'prix'  =>648 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1200,
                    'largeur'  =>500 ,
                    'prix'  => 668,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1300,
                    'largeur'  =>500 ,
                    'prix'  => 685,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1400,
                    'largeur'  =>500 ,
                    'prix'  => 714,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1500,
                    'largeur'  =>500 ,
                    'prix'  => 734,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1600,
                    'largeur'  =>500 ,
                    'prix'  => 777,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1700,
                    'largeur'  =>500 ,
                    'prix'  => 808,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1800,
                    'largeur'  =>500 ,
                    'prix'  =>835 ,
                ],
                [
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1900,
                    'largeur'  =>500 ,
                    'prix'  =>882 ,
                ],
                [
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2000,
                    'largeur'  =>500 ,
                    'prix'  =>913 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2100,
                    'largeur'  =>500 ,
                    'prix'  =>932 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2200,
                    'largeur'  =>500 ,
                    'prix'  =>962 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2300,
                    'largeur'  =>500 ,
                    'prix'  =>1005 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2400,
                    'largeur'  =>500 ,
                    'prix'  =>1035 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2500,
                    'largeur'  =>500 ,
                    'prix'  =>1076 ,
                ],
                /* couleur 2*/
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>2 ,
                    'hauteur'    => 500,
                    'largeur'  =>500 ,
                    'prix'  => 530,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    => 2,
                    'hauteur'    => 600,
                    'largeur'  =>500 ,
                    'prix'  => 556,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>2 ,
                    'hauteur'    => 700,
                    'largeur'  =>500 ,
                    'prix'  => 593,
                ],
				[
                    'genre'    =>1 ,
 	 	 	 	 	 'type'    =>2 ,
                    'couleur'    =>2 ,
                    'hauteur'    => 800,
                    'largeur'  =>500 ,
                    'prix'  => 615,
                ],
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    => 2,
                    'hauteur'    => 900,
                    'largeur'  =>500 ,
                    'prix'  => 648,
                ],
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    =>2 ,
                    'hauteur'    => 1000,
                    'largeur'  =>500 ,
                    'prix'  =>668 ,
                ],
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    =>2 ,
                    'hauteur'    => 1100,
                    'largeur'  =>500 ,
                    'prix'  => 699,
                ],
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    =>2 ,
                    'hauteur'    => 1200,
                    'largeur'  =>500 ,
                    'prix'  => 724,
                ],
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    =>2 ,
                    'hauteur'    => 1300,
                    'largeur'  =>500 ,
                    'prix'  => 755,
                ],
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    =>2 ,
                    'hauteur'    => 1400,
                    'largeur'  =>500 ,
                    'prix'  => 787,
                ],
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    => 2,
                    'hauteur'    => 1500,
                    'largeur'  =>500,
                    'prix'  =>808,
                ],
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    =>2 ,
                    'hauteur'    => 1600,
                    'largeur'  =>500 ,
                    'prix'  => 835,
                ],
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    =>2 ,
                    'hauteur'    => 1700,
                    'largeur'  =>500 ,
                    'prix'  =>899 ,
                ],
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    =>2 ,
                    'hauteur'    => 1800,
                    'largeur'  =>500 ,
                    'prix'  => 923,
                ],
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    =>2 ,
                    'hauteur'    => 1900,
                    'largeur'  =>500 ,
                    'prix'  => 978,
                ],
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    =>2 ,
                    'hauteur'    => 2000,
                    'largeur'  =>500 ,
                    'prix'  => 1005,
                ],
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    =>2 ,
                    'hauteur'    => 2100,
                    'largeur'  =>500 ,
                    'prix'  => 1035,
                ],
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    =>2 ,
                    'hauteur'    => 2200,
                    'largeur'  =>500 ,
                    'prix'  => 1059,
                ],
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    =>2 ,
                    'hauteur'    => 2300,
                    'largeur'  =>500 ,
                    'prix'  => 1112,
                ],
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    =>2 ,
                    'hauteur'    => 2400,
                    'largeur'  =>500 ,
                    'prix'  => 1148,
                ],
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    =>2 ,
                    'hauteur'    => 2500,
                    'largeur'  =>500 ,
                    'prix'  => 1202,
                ],
                /* couleur 3*/
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    =>3 ,
                    'hauteur'    => 500,
                    'largeur'  =>500 ,
                    'prix'  => 570,
                ],
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    =>3 ,
                    'hauteur'    => 600,
                    'largeur'  =>500 ,
                    'prix'  => 615,
                ],
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    =>3 ,
                    'hauteur'    => 700,
                    'largeur'  =>500 ,
                    'prix'  => 648,
                ],
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    =>3 ,
                    'hauteur'    => 800,
                    'largeur'  =>500 ,
                    'prix'  => 685,
                ],
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    =>3 ,
                    'hauteur'    => 900,
                    'largeur'  =>500 ,
                    'prix'  => 714,
                ],
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    =>3 ,
                    'hauteur'    => 1000,
                    'largeur'  =>500 ,
                    'prix'  => 755,
                ],
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    =>3 ,
                    'hauteur'    => 1100,
                    'largeur'  =>500 ,
                    'prix'  => 787,
                ],
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    =>3 ,
                    'hauteur'    => 1200,
                    'largeur'  =>500 ,
                    'prix'  => 821,
                ],
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    =>3 ,
                    'hauteur'    => 1300,
                    'largeur'  =>500 ,
                    'prix'  => 843,
                ],
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    =>3 ,
                    'hauteur'    => 1400,
                    'largeur'  =>500 ,
                    'prix'  => 899,
                ],
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    =>3 ,
                    'hauteur'    => 1500,
                    'largeur'  =>500 ,
                    'prix'  => 923,
                ],
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    =>3 ,
                    'hauteur'    => 1600,
                    'largeur'  =>500 ,
                    'prix'  => 962,
                ],
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    =>3 ,
                    'hauteur'    => 1700,
                    'largeur'  =>500 ,
                    'prix'  => 1023,
                ],
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    =>3 ,
                    'hauteur'    => 1800,
                    'largeur'  =>500 ,
                    'prix'  => 1046,
                ],
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    =>3 ,
                    'hauteur'    => 1900,
                    'largeur'  =>500 ,
                    'prix'  => 1112,
                ],
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    =>3 ,
                    'hauteur'    => 2000,
                    'largeur'  =>500 ,
                    'prix'  => 1148,
                ],
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    =>3 ,
                    'hauteur'    => 2100,
                    'largeur'  =>500 ,
                    'prix'  => 1183,
                ],
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    =>3 ,
                    'hauteur'    => 2200,
                    'largeur'  =>500 ,
                    'prix'  => 1216,
                ],
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    =>3 ,
                    'hauteur'    => 2300,
                    'largeur'  =>500 ,
                    'prix'  => 1263,
                ],
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    =>3 ,
                    'hauteur'    => 2400,
                    'largeur'  =>500 ,
                    'prix'  => 1319,
                ],
				[
                    'genre'    =>1 ,
 	 	 	        'type'    =>2 ,
                    'couleur'    =>3 ,
                    'hauteur'    => 2500,
                    'largeur'  =>500 ,
                    'prix'  => 1367,
                ],

            /*Larg= 600*/
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 500,
                'largeur'  =>600 ,
                'prix'  => 522,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    => 1,
                'hauteur'    =>600 ,
                'largeur'  =>600 ,
                'prix'  => 547,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    => 1,
                'hauteur'    => 700,
                'largeur'  =>600 ,
                'prix'  => 556,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    => 1,
                'hauteur'    => 800,
                'largeur'  =>600 ,
                'prix'  => 593,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    => 1,
                'hauteur'    => 900,
                'largeur'  =>600 ,
                'prix'  => 615,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 1000,
                'largeur'  =>600 ,
                'prix'  => 648,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    =>1100 ,
                'largeur'  =>600 ,
                'prix'  => 668,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 1200,
                'largeur'  =>600 ,
                'prix'  => 699,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 1300,
                'largeur'  =>600 ,
                'prix'  => 724,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 1400,
                'largeur'  =>600 ,
                'prix'  => 755,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 1500,
                'largeur'  =>600 ,
                'prix'  => 787,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 1600,
                'largeur'  =>600 ,
                'prix'  =>808 ,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 1700,
                'largeur'  =>600 ,
                'prix'  => 870,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 1800,
                'largeur'  =>600 ,
                'prix'  => 899,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 1900,
                'largeur'  =>600 ,
                'prix'  => 949,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 2000,
                'largeur'  =>600 ,
                'prix'  => 962,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 2100,
                'largeur'  =>600 ,
                'prix'  => 1005,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 2200,
                'largeur'  =>600 ,
                'prix'  => 1035,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 2300,
                'largeur'  =>600 ,
                'prix'  => 1076,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 2400,
                'largeur'  =>600 ,
                'prix'  => 1102,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 2500,
                'largeur'  =>600 ,
                'prix'  => 1148,
            ],
            /* couleur 2*/
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>2 ,
                'hauteur'    => 500,
                'largeur'  =>600 ,
                'prix'  => 556,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    => 2,
                'hauteur'    => 600,
                'largeur'  =>600 ,
                'prix'  => 593,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>2 ,
                'hauteur'    => 700,
                'largeur'  =>600 ,
                'prix'  => 615,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>2 ,
                'hauteur'    => 800,
                'largeur'  =>600 ,
                'prix'  => 648,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    => 2,
                'hauteur'    => 900,
                'largeur'  =>600 ,
                'prix'  => 668,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>2 ,
                'hauteur'    => 1000,
                'largeur'  =>600 ,
                'prix'  => 699,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>2 ,
                'hauteur'    => 1100,
                'largeur'  =>600 ,
                'prix'  => 724,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>2 ,
                'hauteur'    => 1200,
                'largeur'  =>600 ,
                'prix'  => 755,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>2 ,
                'hauteur'    => 1300,
                'largeur'  =>600 ,
                'prix'  => 794,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>2 ,
                'hauteur'    => 1400,
                'largeur'  =>600 ,
                'prix'  => 821,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    => 2,
                'hauteur'    => 1500,
                'largeur'  =>600 ,
                'prix'  => 870,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>2 ,
                'hauteur'    => 1600,
                'largeur'  =>600 ,
                'prix'  => 899,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>2 ,
                'hauteur'    => 1700,
                'largeur'  =>600 ,
                'prix'  => 949,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>2 ,
                'hauteur'    => 1800,
                'largeur'  =>600 ,
                'prix'  => 991,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>2 ,
                'hauteur'    => 1900,
                'largeur'  =>600 ,
                'prix'  => 1046,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>2 ,
                'hauteur'    => 2000,
                'largeur'  =>600 ,
                'prix'  => 1059,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>2 ,
                'hauteur'    => 2100,
                'largeur'  =>600 ,
                'prix'  => 1102,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>2 ,
                'hauteur'    => 2200,
                'largeur'  =>600 ,
                'prix'  => 1129,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>2 ,
                'hauteur'    => 2300,
                'largeur'  =>600 ,
                'prix'  => 1183,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>2 ,
                'hauteur'    => 2400,
                'largeur'  =>600 ,
                'prix'  => 1216,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>2 ,
                'hauteur'    => 2500,
                'largeur'  =>600 ,
                'prix'  => 1263,
            ],
            /* couleur 3*/
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>3 ,
                'hauteur'    => 500,
                'largeur'  =>600 ,
                'prix'  => 615,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>3 ,
                'hauteur'    => 600,
                'largeur'  =>600 ,
                'prix'  => 648,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>3 ,
                'hauteur'    => 700,
                'largeur'  =>600 ,
                'prix'  => 685,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>3 ,
                'hauteur'    => 800,
                'largeur'  =>600 ,
                'prix'  => 714,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>3 ,
                'hauteur'    => 900,
                'largeur'  =>600 ,
                'prix'  => 755,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>3 ,
                'hauteur'    => 1000,
                'largeur'  =>600 ,
                'prix'  => 794,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>3 ,
                'hauteur'    => 1100,
                'largeur'  =>600 ,
                'prix'  => 821,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>3 ,
                'hauteur'    => 1200,
                'largeur'  =>600 ,
                'prix'  => 843,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>3 ,
                'hauteur'    => 1300,
                'largeur'  =>600 ,
                'prix'  => 899,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>3 ,
                'hauteur'    => 1400,
                'largeur'  =>600 ,
                'prix'  => 932,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>3 ,
                'hauteur'    => 1500,
                'largeur'  =>600 ,
                'prix'  => 978,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>3 ,
                'hauteur'    => 1600,
                'largeur'  =>600 ,
                'prix'  => 1023,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>3 ,
                'hauteur'    => 1700,
                'largeur'  =>600 ,
                'prix'  => 1076,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>3 ,
                'hauteur'    => 1800,
                'largeur'  =>600 ,
                'prix'  => 1112,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>3 ,
                'hauteur'    => 1900,
                'largeur'  =>600 ,
                'prix'  => 1183,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>3 ,
                'hauteur'    => 2000,
                'largeur'  =>600 ,
                'prix'  => 1216,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>3 ,
                'hauteur'    => 2100,
                'largeur'  =>600 ,
                'prix'  => 1255,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>3 ,
                'hauteur'    => 2200,
                'largeur'  =>600 ,
                'prix'  => 1294,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>3 ,
                'hauteur'    => 2300,
                'largeur'  =>600 ,
                'prix'  => 1353,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>3 ,
                'hauteur'    => 2400,
                'largeur'  =>600 ,
                'prix'  => 1392,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>3 ,
                'hauteur'    => 2500,
                'largeur'  =>600 ,
                'prix'  => 1455,
            ],
        /*Larg=700*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>700 ,
            'prix'  => 547,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>700 ,
            'prix'  => 556,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>700 ,
            'prix'  => 593,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>700 ,
            'prix'  => 615,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>700 ,
            'prix'  => 648,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>700 ,
            'prix'  => 668,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>700 ,
            'prix'  => 699,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>700 ,
            'prix'  => 734,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>700 ,
            'prix'  => 777,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>700 ,
            'prix'  => 794,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>700 ,
            'prix'  => 835,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>700 ,
            'prix'  => 870,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>700 ,
            'prix'  => 923,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>700 ,
            'prix'  => 949,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>700 ,
            'prix'  => 949,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>700 ,
            'prix'  => 1005,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>700 ,
            'prix'  => 1035,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>700 ,
            'prix'  => 1091,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>700 ,
            'prix'  => 1148,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>700 ,
            'prix'  => 1176,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>700 ,
            'prix'  => 1216,
        ],
        /* couleur 2*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 500,
            'largeur'  =>700 ,
            'prix'  => 593,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 2,
            'hauteur'    => 600,
            'largeur'  =>700 ,
            'prix'  => 615,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 700,
            'largeur'  =>700 ,
            'prix'  => 648,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 800,
            'largeur'  =>700 ,
            'prix'  => 668,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 2,
            'hauteur'    => 900,
            'largeur'  =>700 ,
            'prix'  => 699,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 1000,
            'largeur'  =>700 ,
            'prix'  => 724,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 1100,
            'largeur'  =>700 ,
            'prix'  => 777,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 1200,
            'largeur'  =>700 ,
            'prix'  => 808,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 1300,
            'largeur'  =>700 ,
            'prix'  => 835,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 1400,
            'largeur'  =>700 ,
            'prix'  => 882,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 2,
            'hauteur'    => 1500,
            'largeur'  =>700 ,
            'prix'  => 913,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 1600,
            'largeur'  =>700 ,
            'prix'  => 949,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 1700,
            'largeur'  =>700 ,
            'prix'  => 1005
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 1800,
            'largeur'  =>700 ,
            'prix'  => 1046,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 1900,
            'largeur'  =>700 ,
            'prix'  => 1102,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 2000,
            'largeur'  =>700 ,
            'prix'  => 1129,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 2100,
            'largeur'  =>700 ,
            'prix'  => 1154,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 2200,
            'largeur'  =>700 ,
            'prix'  => 1202,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 2300,
            'largeur'  =>700 ,
            'prix'  => 1255,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 2400,
            'largeur'  =>700 ,
            'prix'  => 1280,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 2500,
            'largeur'  =>700 ,
            'prix'  => 1345,
        ],
        /* couleur 3*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 500,
            'largeur'  =>700 ,
            'prix'  => 648,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 600,
            'largeur'  =>700 ,
            'prix'  => 685,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 700,
            'largeur'  =>700 ,
            'prix'  => 714,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 800,
            'largeur'  =>700 ,
            'prix'  => 755,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 900,
            'largeur'  =>700 ,
            'prix'  => 787,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1000,
            'largeur'  =>700 ,
            'prix'  => 821,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1100,
            'largeur'  =>700 ,
            'prix'  => 870,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1200,
            'largeur'  =>700 ,
            'prix'  => 913,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1300,
            'largeur'  =>700 ,
            'prix'  => 949,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1400,
            'largeur'  =>700 ,
            'prix'  => 991,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1500,
            'largeur'  =>700 ,
            'prix'  => 1035,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1600,
            'largeur'  =>700 ,
            'prix'  => 1076,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1700,
            'largeur'  =>700 ,
            'prix'  => 1148,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1800,
            'largeur'  =>700 ,
            'prix'  => 1183,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1900,
            'largeur'  =>700 ,
            'prix'  => 1241,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 2000,
            'largeur'  =>700 ,
            'prix'  => 1280,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 2100,
            'largeur'  =>700 ,
            'prix'  => 1333,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 2200,
            'largeur'  =>700 ,
            'prix'  => 1367,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 2300,
            'largeur'  =>700 ,
            'prix'  => 1425,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 2400,
            'largeur'  =>700 ,
            'prix'  => 1464,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 2500,
            'largeur'  =>700 ,
            'prix'  => 1520,
        ],
        /*larg=800*/

        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>800 ,
            'prix'  => 554,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>800 ,
            'prix'  => 605,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>800 ,
            'prix'  => 632,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>800 ,
            'prix'  => 655,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>800 ,
            'prix'  => 685,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>800 ,
            'prix'  => 724,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>800 ,
            'prix'  => 755,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>800 ,
            'prix'  => 794,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>800 ,
            'prix'  => 821,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>800 ,
            'prix'  => 870,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>800 ,
            'prix'  => 899,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>800 ,
            'prix'  => 932,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>800 ,
            'prix'  => 991,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>800 ,
            'prix'  => 1023,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>800 ,
            'prix'  => 1076,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>800 ,
            'prix'  => 1102,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>800 ,
            'prix'  => 1129,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>800 ,
            'prix'  => 1176,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>800 ,
            'prix'  => 1216,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>800 ,
            'prix'  => 1255,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>800 ,
            'prix'  => 1294,
        ],
        /* couleur 2*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 500,
            'largeur'  =>800 ,
            'prix'  => 600,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 2,
            'hauteur'    => 600,
            'largeur'  =>800 ,
            'prix'  => 658,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 700,
            'largeur'  =>800 ,
            'prix'  => 685,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 800,
            'largeur'  =>800 ,
            'prix'  => 714,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 2,
            'hauteur'    => 900,
            'largeur'  =>800 ,
            'prix'  => 734,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 1000,
            'largeur'  =>800 ,
            'prix'  => 787,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 1100,
            'largeur'  =>800 ,
            'prix'  => 821,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 1200,
            'largeur'  =>800 ,
            'prix'  => 870,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 1300,
            'largeur'  =>800 ,
            'prix'  => 913,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 1400,
            'largeur'  =>800 ,
            'prix'  => 949,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 2,
            'hauteur'    => 1500,
            'largeur'  =>800 ,
            'prix'  => 991,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 1600,
            'largeur'  =>800 ,
            'prix'  =>1023 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 1700,
            'largeur'  =>800 ,
            'prix'  => 1076,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 1800,
            'largeur'  =>800 ,
            'prix'  => 1112,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 1900,
            'largeur'  =>800 ,
            'prix'  => 1176,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 2000,
            'largeur'  =>800 ,
            'prix'  => 1202,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 2100,
            'largeur'  =>800 ,
            'prix'  => 1241,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 2200,
            'largeur'  =>800 ,
            'prix'  => 1280,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 2300,
            'largeur'  =>800 ,
            'prix'  => 1345,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 2400,
            'largeur'  =>800 ,
            'prix'  => 1379,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 2500,
            'largeur'  =>800 ,
            'prix'  => 1425,
        ],
        /* couleur 3*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 500,
            'largeur'  =>800 ,
            'prix'  => 655,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 600,
            'largeur'  =>800 ,
            'prix'  => 724,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 700,
            'largeur'  =>800 ,
            'prix'  => 755,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 800,
            'largeur'  =>800 ,
            'prix'  => 794,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 900,
            'largeur'  =>800 ,
            'prix'  => 833,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1000,
            'largeur'  =>800 ,
            'prix'  => 835,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1100,
            'largeur'  =>800 ,
            'prix'  => 899,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1200,
            'largeur'  =>800 ,
            'prix'  => 932,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1300,
            'largeur'  =>800 ,
            'prix'  => 978,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1400,
            'largeur'  =>800 ,
            'prix'  => 1023,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1500,
            'largeur'  =>800 ,
            'prix'  => 1112,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1600,
            'largeur'  =>800 ,
            'prix'  => 1154,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1700,
            'largeur'  =>800 ,
            'prix'  => 1216,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1800,
            'largeur'  =>800 ,
            'prix'  => 1263,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1900,
            'largeur'  =>800 ,
            'prix'  => 1333,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 2000,
            'largeur'  =>800 ,
            'prix'  => 1367,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 2100,
            'largeur'  =>800 ,
            'prix'  => 1411,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 2200,
            'largeur'  =>800 ,
            'prix'  => 1455,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 2300,
            'largeur'  =>800 ,
            'prix'  => 1520,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 2400,
            'largeur'  =>800 ,
            'prix'  => 1564,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 2500,
            'largeur'  =>800 ,
            'prix'  => 1618,
        ],
        /*Larg=900*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>900 ,
            'prix'  => 570,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>900 ,
            'prix'  => 615,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>900 ,
            'prix'  => 648,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>900 ,
            'prix'  => 685,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>900 ,
            'prix'  => 714,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>900 ,
            'prix'  => 755,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>900 ,
            'prix'  => 794,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>900 ,
            'prix'  => 835,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>900 ,
            'prix'  => 870,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>900 ,
            'prix'  => 913,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>900 ,
            'prix'  => 949,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>900 ,
            'prix'  => 978,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>900 ,
            'prix'  => 1035,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>900 ,
            'prix'  => 1076,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>900 ,
            'prix'  => 1129,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>900 ,
            'prix'  => 1154,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>900 ,
            'prix'  => 1202,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>900 ,
            'prix'  => 1229,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>900 ,
            'prix'  => 1280,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>900 ,
            'prix'  => 1333,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>900 ,
            'prix'  => 1367,
        ],
        /* couleur 2*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 500,
            'largeur'  =>900 ,
            'prix'  => 615,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 2,
            'hauteur'    => 600,
            'largeur'  =>900 ,
            'prix'  => 668,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 700,
            'largeur'  =>900 ,
            'prix'  => 714,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 800,
            'largeur'  =>900 ,
            'prix'  => 734,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 2,
            'hauteur'    => 900,
            'largeur'  =>900 ,
            'prix'  => 787,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 1000,
            'largeur'  =>900 ,
            'prix'  => 835,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 1100,
            'largeur'  =>900 ,
            'prix'  => 870,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 1200,
            'largeur'  =>900 ,
            'prix'  => 913,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 1300,
            'largeur'  =>900 ,
            'prix'  => 949,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 1400,
            'largeur'  =>900 ,
            'prix'  => 991,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 2,
            'hauteur'    => 1500,
            'largeur'  =>900 ,
            'prix'  => 1035,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 1600,
            'largeur'  =>900 ,
            'prix'  => 1076,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 1700,
            'largeur'  =>900 ,
            'prix'  => 1129,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 1800,
            'largeur'  =>900 ,
            'prix'  => 1176,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 1900,
            'largeur'  =>900 ,
            'prix'  => 1234,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 2000,
            'largeur'  =>900 ,
            'prix'  => 1263,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 2100,
            'largeur'  =>900 ,
            'prix'  => 1319,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 2200,
            'largeur'  =>900 ,
            'prix'  => 1353,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 2300,
            'largeur'  =>900 ,
            'prix'  => 1411,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 2400,
            'largeur'  =>900 ,
            'prix'  => 1455,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 2500,
            'largeur'  =>900 ,
            'prix'  => 1508,
        ],
        /* couleur 3*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 500,
            'largeur'  =>900 ,
            'prix'  => 685,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 600,
            'largeur'  =>900 ,
            'prix'  => 728,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 700,
            'largeur'  =>900 ,
            'prix'  =>794 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 800,
            'largeur'  =>900 ,
            'prix'  => 835,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 900,
            'largeur'  =>900 ,
            'prix'  => 882,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1000,
            'largeur'  =>900 ,
            'prix'  => 932,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1100,
            'largeur'  =>900 ,
            'prix'  => 978,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1200,
            'largeur'  =>900 ,
            'prix'  => 1035,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1300,
            'largeur'  =>900 ,
            'prix'  => 1076,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1400,
            'largeur'  =>900 ,
            'prix'  => 1129,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1500,
            'largeur'  =>900 ,
            'prix'  => 1176,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1600,
            'largeur'  =>900 ,
            'prix'  => 1216,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1700,
            'largeur'  =>900 ,
            'prix'  => 1280,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1800,
            'largeur'  =>900 ,
            'prix'  => 1333,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1900,
            'largeur'  =>900 ,
            'prix'  => 1392,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 2000,
            'largeur'  =>900 ,
            'prix'  => 1431,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 2100,
            'largeur'  =>900 ,
            'prix'  => 1477,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 2200,
            'largeur'  =>900 ,
            'prix'  => 1520,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 2300,
            'largeur'  =>900 ,
            'prix'  => 1588,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 2400,
            'largeur'  =>900 ,
            'prix'  => 1632,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 2500,
            'largeur'  =>900 ,
            'prix'  => 1692,
        ],
        /*larg=1000*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1000 ,
            'prix'  => 648,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1000 ,
            'prix'  => 668,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1000 ,
            'prix'  => 724,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1000 ,
            'prix'  => 755,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1000 ,
            'prix'  => 808,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1000 ,
            'prix'  => 835,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1000 ,
            'prix'  => 882,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1000 ,
            'prix'  => 923,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1000 ,
            'prix'  => 962,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1000 ,
            'prix'  =>1005 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1000 ,
            'prix'  => 1046,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1000 ,
            'prix'  => 1102,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1000 ,
            'prix'  => 1129,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1000 ,
            'prix'  => 1183,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1000 ,
            'prix'  => 1229,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1000 ,
            'prix'  => 1255,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1000 ,
            'prix'  => 1294,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1000 ,
            'prix'  => 1353,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1000 ,
            'prix'  => 1392,
        ],
        /* couleur 2*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 2,
            'hauteur'    => 600,
            'largeur'  =>1000 ,
            'prix'  => 685,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 700,
            'largeur'  =>1000 ,
            'prix'  => 734,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 800,
            'largeur'  =>1000 ,
            'prix'  => 787,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 2,
            'hauteur'    => 900,
            'largeur'  =>1000 ,
            'prix'  => 821,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 1000,
            'largeur'  =>1000 ,
            'prix'  => 882,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 1100,
            'largeur'  =>1000 ,
            'prix'  => 923,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 1200,
            'largeur'  =>1000 ,
            'prix'  => 962,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 1300,
            'largeur'  =>1000 ,
            'prix'  => 1005,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 1400,
            'largeur'  =>1000 ,
            'prix'  => 1059,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 2,
            'hauteur'    => 1500,
            'largeur'  =>1000 ,
            'prix'  => 1102,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 1600,
            'largeur'  =>1000 ,
            'prix'  => 1148,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 1700,
            'largeur'  =>1000 ,
            'prix'  => 1202,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 1800,
            'largeur'  =>1000 ,
            'prix'  => 1241,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 1900,
            'largeur'  =>1000 ,
            'prix'  => 1294,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 2000,
            'largeur'  =>1000 ,
            'prix'  => 1345,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 2100,
            'largeur'  =>1000 ,
            'prix'  => 1379,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 2200,
            'largeur'  =>1000 ,
            'prix'  => 1425,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 2300,
            'largeur'  =>1000 ,
            'prix'  => 1477,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>2 ,
            'hauteur'    => 2400,
            'largeur'  =>1000 ,
            'prix'  => 1520,
        ],
        /* couleur 3*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 600,
            'largeur'  =>1000 ,
            'prix'  => 755,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 700,
            'largeur'  =>1000 ,
            'prix'  => 838,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 800,
            'largeur'  =>1000 ,
            'prix'  => 899,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 900,
            'largeur'  =>1000 ,
            'prix'  => 932,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1000,
            'largeur'  =>1000 ,
            'prix'  => 991,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1100,
            'largeur'  =>1000 ,
            'prix'  => 1035,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1200,
            'largeur'  =>1000 ,
            'prix'  => 1091,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1300,
            'largeur'  =>1000 ,
            'prix'  => 1148,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1400,
            'largeur'  =>1000 ,
            'prix'  => 1183,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1500,
            'largeur'  =>1000 ,
            'prix'  => 1241,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1600,
            'largeur'  =>1000 ,
            'prix'  => 1280,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1700,
            'largeur'  =>1000 ,
            'prix'  => 1353,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1800,
            'largeur'  =>1000 ,
            'prix'  => 1392,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 1900,
            'largeur'  =>1000 ,
            'prix'  => 1464,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 2000,
            'largeur'  =>1000 ,
            'prix'  => 1508,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 2100,
            'largeur'  =>1000 ,
            'prix'  => 1564,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 2200,
            'largeur'  =>1000 ,
            'prix'  => 1610,
        ],
         [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 2300,
            'largeur'  =>1000 ,
            'prix'  => 1678,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>3 ,
            'hauteur'    => 2400,
            'largeur'  =>1000 ,
            'prix'  => 1715,
        ],


            ];

            Modele::insert($modeles);

        }


    }
}
