<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Modele;
use App\Models\Seeders;

class Modeles9Seeder extends Seeder  //coulissant 2
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $seeder = Modele::where('type',9)->where('genre',2)->count();
        //ALU
        //Check if the seeder exist in the DB
        if ($seeder==0) {
            $modeles =
            [

         /*Larg=700*/
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>700 ,
            'prix'  => 895,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>700 ,
            'prix'  => 924,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>700 ,
            'prix'  => 953,
        ],

        /*larg=800*/
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>800 ,
            'prix'  => 920,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>800 ,
            'prix'  => 950,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>800 ,
            'prix'  => 979,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>800 ,
            'prix'  => 1001,
        ],
          /*Larg=900*/
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>900 ,
            'prix'  => 946,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>900 ,
            'prix'  => 976,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>900 ,
            'prix'  => 1004,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>900 ,
            'prix'  => 1030,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1000 ,
            'prix'  => 1061,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1100 ,
            'prix'  => 1094,
        ],
        /*larg=1000*/
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1000 ,
            'prix'  => 971,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1000 ,
            'prix'  => 1001,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1000 ,
            'prix'  => 1029,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1000 ,
            'prix'  => 1059,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1000 ,
            'prix'  => 1089,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1000 ,
            'prix'  => 1121,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1000 ,
            'prix'  => 1150,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1000 ,
            'prix'  => 1180,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1000 ,
            'prix'  => 1209,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1000 ,
            'prix'  => 2140,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1000 ,
            'prix'  => 1382,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1000 ,
            'prix'  => 1414,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1000 ,
            'prix'  => 1447,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1000 ,
            'prix'  => 1482,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1000 ,
            'prix'  => 1493,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1000 ,
            'prix'  => 1525,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1000 ,
            'prix'  => 1557,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1000 ,
            'prix'  => 1628,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1000 ,
            'prix'  => 1736,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1000 ,
            'prix'  => 1772,
        ],
        /*larg=1100*/
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1100 ,
            'prix'  => 997,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1100 ,
            'prix'  => 1026,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1100 ,
            'prix'  => 1055,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1100 ,
            'prix'  => 1088,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1100 ,
            'prix'  => 1117,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1100 ,
            'prix'  => 1148,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1100 ,
            'prix'  => 1179,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1100 ,
            'prix'  => 1209,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1100 ,
            'prix'  => 1241,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1100 ,
            'prix'  => 1270,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1100 ,
            'prix'  => 1414,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1100 ,
            'prix'  => 1448,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1100 ,
            'prix'  => 1482,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1100 ,
            'prix'  => 1516,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1100 ,
            'prix'  => 1525,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1100 ,
            'prix'  => 1560,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1100 ,
            'prix'  => 1593,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1100 ,
            'prix'  => 1664,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1100 ,
            'prix'  => 1774,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1100 ,
            'prix'  => 1811,
        ],
        /*larg=1200*/
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1200 ,
            'prix'  => 1022,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1200 ,
            'prix'  => 1051,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1200 ,
            'prix'  => 1085,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1200 ,
            'prix'  => 1114,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1200 ,
            'prix'  => 1144,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1200 ,
            'prix'  => 1177,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1200 ,
            'prix'  => 1207,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1200 ,
            'prix'  => 1239,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1200 ,
            'prix'  => 1270,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1200 ,
            'prix'  =>1301 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1200 ,
            'prix'  =>1447 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1200 ,
            'prix'  =>1483 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1200 ,
            'prix'  =>1515 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1200 ,
            'prix'  =>1552 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1200 ,
            'prix'  =>1561 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1200 ,
            'prix'  =>1596 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1200 ,
            'prix'  =>1627 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1200 ,
            'prix'  =>1700 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1200 ,
            'prix'  =>1813 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1200 ,
            'prix'  =>1849 ,
        ],

        /*larg=1300*/
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1300 ,
            'prix'  => 1046,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1300 ,
            'prix'  => 1079,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1300 ,
            'prix'  => 1108,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1300 ,
            'prix'  => 1141,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1300 ,
            'prix'  => 1173,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1300 ,
            'prix'  => 1206,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1300 ,
            'prix'  => 1236,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1300 ,
            'prix'  => 1268,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1300 ,
            'prix'  => 1300,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1300 ,
            'prix'  =>1332 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1300 ,
            'prix'  => 1481,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1300 ,
            'prix'  => 1514,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1300 ,
            'prix'  => 1549,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1300 ,
            'prix'  => 1584,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1300 ,
            'prix'  => 1594,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1300 ,
            'prix'  => 1628,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1300 ,
            'prix'  => 1665,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1300 ,
            'prix'  => 1735,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1300 ,
            'prix'  => 1851,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1300 ,
            'prix'  => 1888,
        ],
        /*larg=1400*/
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1400 ,
            'prix'  => 1072,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1400 ,
            'prix'  => 1104
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1400 ,
            'prix'  => 1137,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1400 ,
            'prix'  => 1168,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1400 ,
            'prix'  => 1200,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1400 ,
            'prix'  => 1232,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1400 ,
            'prix'  => 1267,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1400 ,
            'prix'  => 1298,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1400 ,
            'prix'  => 1329,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1400 ,
            'prix'  =>1363 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1400 ,
            'prix'  => 1512,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1400 ,
            'prix'  => 1547,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1400 ,
            'prix'  => 1583,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1400 ,
            'prix'  => 1618,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1400 ,
            'prix'  => 1630,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1400 ,
            'prix'  => 1666,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1400 ,
            'prix'  => 1698,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1400 ,
            'prix'  => 1772,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1400 ,
            'prix'  => 1890,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1400 ,
            'prix'  => 1927,
        ],
        /*larg=1500*/
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1500 ,
            'prix'  => 1099,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1500 ,
            'prix'  => 1130,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1500 ,
            'prix'  => 1163,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1500 ,
            'prix'  => 1196,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1500 ,
            'prix'  => 1228,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1500 ,
            'prix'  => 1262,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1500 ,
            'prix'  => 1293,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1500 ,
            'prix'  => 1327,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1500 ,
            'prix'  => 1360,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1500 ,
            'prix'  =>1393 ,
        ],

        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    =>1600 ,
            'largeur'  =>1500 ,
            'prix'  => 1545,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    => 1700,
            'largeur'  =>1500 ,
            'prix'  => 1581,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    => 1800,
            'largeur'  =>1500 ,
            'prix'  => 1618,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    => 1900,
            'largeur'  =>1500 ,
            'prix'  => 1654,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1500 ,
            'prix'  => 1665,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    =>2100 ,
            'largeur'  =>1500 ,
            'prix'  => 1698,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1500 ,
            'prix'  => 1736,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1500 ,
            'prix'  => 1811,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1500 ,
            'prix'  => 1927,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1500 ,
            'prix'  =>1969 ,
        ],
       /*larg=1600*/
       [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    =>600 ,
        'largeur'  =>1600 ,
        'prix'  => 1123,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 700,
        'largeur'  =>1600 ,
        'prix'  => 1157,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 800,
        'largeur'  =>1600 ,
        'prix'  => 1190,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 900,
        'largeur'  =>1600 ,
        'prix'  => 1223,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1000,
        'largeur'  =>1600 ,
        'prix'  => 1258,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    =>1100 ,
        'largeur'  =>1600 ,
        'prix'  => 1290,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1200,
        'largeur'  =>1600 ,
        'prix'  => 1323,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1300,
        'largeur'  =>1600 ,
        'prix'  => 1359,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1400,
        'largeur'  =>1600 ,
        'prix'  => 1391,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1500,
        'largeur'  =>1600 ,
        'prix'  =>1426 ,
    ],

    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    =>1600 ,
        'largeur'  =>1600 ,
        'prix'  => 1577,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 1700,
        'largeur'  =>1600 ,
        'prix'  => 1613,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 1800,
        'largeur'  =>1600 ,
        'prix'  => 1651,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 1900,
        'largeur'  =>1600 ,
        'prix'  => 1687,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2000,
        'largeur'  =>1600 ,
        'prix'  => 1698,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    =>2100 ,
        'largeur'  =>1600 ,
        'prix'  => 1737,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2200,
        'largeur'  =>1600 ,
        'prix'  => 1771,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2300,
        'largeur'  =>1600 ,
        'prix'  => 1845,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2400,
        'largeur'  =>1600 ,
        'prix'  => 1969,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2500,
        'largeur'  =>1600 ,
        'prix'  =>2005 ,
    ],
           /*larg=1700*/
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1700 ,
            'prix'  => 1148,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1700 ,
            'prix'  => 1183,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1700 ,
            'prix'  => 1217,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1700 ,
            'prix'  => 1250,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1700 ,
            'prix'  => 1284,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1700 ,
            'prix'  => 1319,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1700 ,
            'prix'  => 1353,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1700 ,
            'prix'  => 1385,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1700 ,
            'prix'  => 1421,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1700 ,
            'prix'  =>1454 ,
        ],

        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    =>1600 ,
            'largeur'  =>1700 ,
            'prix'  => 1610,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    => 1700,
            'largeur'  =>1700 ,
            'prix'  => 1648,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    => 1800,
            'largeur'  =>1700 ,
            'prix'  => 1684,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    => 1,
            'hauteur'    => 1900,
            'largeur'  =>1700 ,
            'prix'  => 1721,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1700 ,
            'prix'  => 1734,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    =>2100 ,
            'largeur'  =>1700 ,
            'prix'  => 1771,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1700 ,
            'prix'  => 1805,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1700 ,
            'prix'  => 1881,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1700 ,
            'prix'  => 2005,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>9 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1700 ,
            'prix'  =>2045 ,
        ],
       /*larg=1800*/
       [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    =>600 ,
        'largeur'  =>1800 ,
        'prix'  => 1173,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 700,
        'largeur'  =>1800 ,
        'prix'  => 1208,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 800,
        'largeur'  =>1800 ,
        'prix'  => 1241,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 900,
        'largeur'  =>1800 ,
        'prix'  => 1278,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1000,
        'largeur'  =>1800 ,
        'prix'  => 1313,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    =>1100 ,
        'largeur'  =>1800 ,
        'prix'  => 1347,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1200,
        'largeur'  =>1800 ,
        'prix'  => 1381,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1300,
        'largeur'  =>1800 ,
        'prix'  => 1415,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1400,
        'largeur'  =>1800 ,
        'prix'  => 1452,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1500,
        'largeur'  =>1800 ,
        'prix'  =>1486 ,
    ],

    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    =>1600 ,
        'largeur'  =>1800 ,
        'prix'  => 1618,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 1700,
        'largeur'  =>1800 ,
        'prix'  => 1656,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 1800,
        'largeur'  =>1800 ,
        'prix'  => 1694,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 1900,
        'largeur'  =>1800 ,
        'prix'  => 1729,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2000,
        'largeur'  =>1800 ,
        'prix'  => 1729,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    =>2100 ,
        'largeur'  =>1800 ,
        'prix'  => 1765,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2200,
        'largeur'  =>1800 ,
        'prix'  => 1801,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2300,
        'largeur'  =>1800 ,
        'prix'  => 1917,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2400,
        'largeur'  =>1800 ,
        'prix'  => 2044,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2500,
        'largeur'  =>1800 ,
        'prix'  =>2085 ,
    ],
       /*larg=1900*/
       [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    =>600 ,
        'largeur'  =>1900 ,
        'prix'  => 1199,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 700,
        'largeur'  =>1900 ,
        'prix'  => 1234,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 800,
        'largeur'  =>1900 ,
        'prix'  => 1270,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 900,
        'largeur'  =>1900 ,
        'prix'  => 1305,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1000,
        'largeur'  =>1900 ,
        'prix'  => 1340,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    =>1100 ,
        'largeur'  =>1900 ,
        'prix'  => 1375,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1200,
        'largeur'  =>1900 ,
        'prix'  => 1411,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1300,
        'largeur'  =>1900 ,
        'prix'  => 1446,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1400,
        'largeur'  =>1900 ,
        'prix'  => 1481,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1500,
        'largeur'  =>1900 ,
        'prix'  =>1516 ,
    ],

    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    =>1600 ,
        'largeur'  =>1900 ,
        'prix'  => 1650,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 1700,
        'largeur'  =>1900 ,
        'prix'  => 1690,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 1800,
        'largeur'  =>1900 ,
        'prix'  => 1728,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 1900,
        'largeur'  =>1900 ,
        'prix'  => 1764,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2000,
        'largeur'  =>1900 ,
        'prix'  => 1764,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    =>2100 ,
        'largeur'  =>1900 ,
        'prix'  => 1799,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2200,
        'largeur'  =>1900 ,
        'prix'  => 1834,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2300,
        'largeur'  =>1900 ,
        'prix'  => 1953,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2400,
        'largeur'  =>1900 ,
        'prix'  => 2082,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2500,
        'largeur'  =>1900 ,
        'prix'  =>2125 ,
    ],
       /*larg=2000*/
       [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    =>600 ,
        'largeur'  =>2000 ,
        'prix'  => 1225,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 700,
        'largeur'  =>2000 ,
        'prix'  => 1260,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 800,
        'largeur'  =>2000 ,
        'prix'  => 1298,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 900,
        'largeur'  =>2000 ,
        'prix'  => 1331,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1000,
        'largeur'  =>2000 ,
        'prix'  => 1367,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    =>1100 ,
        'largeur'  =>2000 ,
        'prix'  => 1403,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1200,
        'largeur'  =>2000 ,
        'prix'  => 1441,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1300,
        'largeur'  =>2000 ,
        'prix'  => 1476,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1400,
        'largeur'  =>2000 ,
        'prix'  => 1509,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1500,
        'largeur'  =>2000 ,
        'prix'  =>1547 ,
    ],

    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    =>1600 ,
        'largeur'  =>2000 ,
        'prix'  => 1683,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 1700,
        'largeur'  =>2000 ,
        'prix'  => 1722,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 1800,
        'largeur'  =>2000 ,
        'prix'  => 1760,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 1900,
        'largeur'  =>2000 ,
        'prix'  => 1798,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2000,
        'largeur'  =>2000 ,
        'prix'  => 1797,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    =>2100 ,
        'largeur'  =>2000 ,
        'prix'  =>1834 ,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2200,
        'largeur'  =>2000 ,
        'prix'  => 1872,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2300,
        'largeur'  =>2000 ,
        'prix'  => 1991,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2400,
        'largeur'  =>2000 ,
        'prix'  => 2120,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2500,
        'largeur'  =>2000 ,
        'prix'  =>2161 ,
    ],
       /*larg=2100*/
       [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    =>600 ,
        'largeur'  =>2100 ,
        'prix'  => 1249,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 700,
        'largeur'  =>2100 ,
        'prix'  => 1287,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 800,
        'largeur'  =>2100 ,
        'prix'  => 1323,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 900,
        'largeur'  =>2100 ,
        'prix'  => 1360,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1000,
        'largeur'  =>2100 ,
        'prix'  => 1396,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    =>1100 ,
        'largeur'  =>2100 ,
        'prix'  => 1431,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1200,
        'largeur'  =>2100 ,
        'prix'  => 1468,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1300,
        'largeur'  =>2100 ,
        'prix'  => 1504,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1400,
        'largeur'  =>2100 ,
        'prix'  => 1541,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1500,
        'largeur'  =>2100 ,
        'prix'  =>1577 ,
    ],

    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    =>1600 ,
        'largeur'  =>2100 ,
        'prix'  => 1714,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 1700,
        'largeur'  =>2100 ,
        'prix'  => 1755,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 1800,
        'largeur'  =>2100 ,
        'prix'  => 1793,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 1900,
        'largeur'  =>2100 ,
        'prix'  => 1831,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2000,
        'largeur'  =>2100 ,
        'prix'  => 1830,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    =>2100 ,
        'largeur'  =>2100 ,
        'prix'  => 1868,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2200,
        'largeur'  =>2100 ,
        'prix'  => 1906,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2300,
        'largeur'  =>2100 ,
        'prix'  => 2026,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2400,
        'largeur'  =>2100 ,
        'prix'  => 2159,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2500,
        'largeur'  =>2100 ,
        'prix'  =>2201 ,
    ],
       /*larg=2200*/
       [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    =>600 ,
        'largeur'  =>2200 ,
        'prix'  => 1275,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 700,
        'largeur'  =>2200 ,
        'prix'  => 1313,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 800,
        'largeur'  =>2200 ,
        'prix'  => 1349,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 900,
        'largeur'  =>2200 ,
        'prix'  => 1387,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1000,
        'largeur'  =>2200 ,
        'prix'  => 1423,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    =>1100 ,
        'largeur'  =>2200 ,
        'prix'  => 1460,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1200,
        'largeur'  =>2200 ,
        'prix'  => 1498,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1300,
        'largeur'  =>2200 ,
        'prix'  => 1534,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1400,
        'largeur'  =>2200 ,
        'prix'  => 1570,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1500,
        'largeur'  =>2200 ,
        'prix'  =>1609 ,
    ],

    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    =>1600 ,
        'largeur'  =>2200 ,
        'prix'  => 1746,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 1700,
        'largeur'  =>2200 ,
        'prix'  => 1787,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 1800,
        'largeur'  =>2200 ,
        'prix'  => 1826,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 1900,
        'largeur'  =>2200 ,
        'prix'  => 1865,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2000,
        'largeur'  =>2200 ,
        'prix'  => 1863,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    =>2100 ,
        'largeur'  =>2200 ,
        'prix'  => 1901,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2200,
        'largeur'  =>2200 ,
        'prix'  => 1941,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2300,
        'largeur'  =>2200 ,
        'prix'  => 2063,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2400,
        'largeur'  =>2200 ,
        'prix'  => 2198,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2500,
        'largeur'  =>2200 ,
        'prix'  =>2242 ,
    ],
       /*larg=2300*/
       [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    =>600 ,
        'largeur'  =>2300 ,
        'prix'  => 1302,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 700,
        'largeur'  =>2300 ,
        'prix'  => 1339,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 800,
        'largeur'  =>2300 ,
        'prix'  => 1376,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 900,
        'largeur'  =>2300 ,
        'prix'  => 1414,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1000,
        'largeur'  =>2300 ,
        'prix'  => 1452,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    =>1100 ,
        'largeur'  =>2300 ,
        'prix'  => 1488,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1200,
        'largeur'  =>2300 ,
        'prix'  => 1526,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1300,
        'largeur'  =>2300 ,
        'prix'  => 1564,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1400,
        'largeur'  =>2300 ,
        'prix'  => 1602,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1500,
        'largeur'  =>2300 ,
        'prix'  =>1638 ,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    =>1600 ,
        'largeur'  =>2300 ,
        'prix'  => 1779,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 1700,
        'largeur'  =>2300 ,
        'prix'  => 1819,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 1800,
        'largeur'  =>2300 ,
        'prix'  => 1860,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 1900,
        'largeur'  =>2300 ,
        'prix'  => 1901,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2000,
        'largeur'  =>2300 ,
        'prix'  => 1939,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    =>2100 ,
        'largeur'  =>2300 ,
        'prix'  => 1978,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2200,
        'largeur'  =>2300 ,
        'prix'  => 2021,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2300,
        'largeur'  =>2300 ,
        'prix'  => 2098,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2400,
        'largeur'  =>2300 ,
        'prix'  => 2234,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2500,
        'largeur'  =>2300 ,
        'prix'  =>2278 ,
    ],
       /*larg=2400*/
       [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    =>600 ,
        'largeur'  =>2400 ,
        'prix'  => 1326,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 700,
        'largeur'  =>2400 ,
        'prix'  => 1364,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 800,
        'largeur'  =>2400 ,
        'prix'  => 1404,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 900,
        'largeur'  =>2400 ,
        'prix'  => 1441,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1000,
        'largeur'  =>2400 ,
        'prix'  => 1479,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    =>1100 ,
        'largeur'  =>2400 ,
        'prix'  => 1516,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1200,
        'largeur'  =>2400 ,
        'prix'  => 1555,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1300,
        'largeur'  =>2400 ,
        'prix'  => 1594,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1400,
        'largeur'  =>2400 ,
        'prix'  => 1632,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1500,
        'largeur'  =>2400 ,
        'prix'  =>1670 ,
    ],

    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    =>1600 ,
        'largeur'  =>2400 ,
        'prix'  => 1811,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 1700,
        'largeur'  =>2400 ,
        'prix'  => 1853,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 1800,
        'largeur'  =>2400 ,
        'prix'  => 1892,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 1900,
        'largeur'  =>2400 ,
        'prix'  => 1934,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2000,
        'largeur'  =>2400 ,
        'prix'  => 1975,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    =>2100 ,
        'largeur'  =>2400 ,
        'prix'  => 2017,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2200,
        'largeur'  =>2400 ,
        'prix'  => 2055,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2300,
        'largeur'  =>2400 ,
        'prix'  => 2135,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2400,
        'largeur'  =>2400 ,
        'prix'  => 2274,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2500,
        'largeur'  =>2400 ,
        'prix'  =>2318 ,
    ],
       /*larg=2500*/
       [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    =>600 ,
        'largeur'  =>2500 ,
        'prix'  => 1352,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 700,
        'largeur'  =>2500 ,
        'prix'  => 1393,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 800,
        'largeur'  =>2500 ,
        'prix'  => 1429,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 900,
        'largeur'  =>2500 ,
        'prix'  => 1469,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1000,
        'largeur'  =>2500 ,
        'prix'  => 1507,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    =>1100 ,
        'largeur'  =>2500 ,
        'prix'  => 1546,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1200,
        'largeur'  =>2500 ,
        'prix'  => 1584,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1300,
        'largeur'  =>2500 ,
        'prix'  => 1625,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1400,
        'largeur'  =>2500 ,
        'prix'  => 1663,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 1500,
        'largeur'  =>2500 ,
        'prix'  =>1701 ,
    ],

    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    =>1600 ,
        'largeur'  =>2500 ,
        'prix'  => 1843,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 1700,
        'largeur'  =>2500 ,
        'prix'  => 1884,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 1800,
        'largeur'  =>2500 ,
        'prix'  => 1926,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    => 1,
        'hauteur'    => 1900,
        'largeur'  =>2500 ,
        'prix'  => 1968,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2000,
        'largeur'  =>2500 ,
        'prix'  => 2010,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    =>2100 ,
        'largeur'  =>2500 ,
        'prix'  => 2050,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2200,
        'largeur'  =>2500 ,
        'prix'  => 2092,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2300,
        'largeur'  =>2500 ,
        'prix'  => 2172,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2400,
        'largeur'  =>2500 ,
        'prix'  => 2313,
    ],
    [
        'genre'    =>2 ,
            'type'    =>9 ,
        'couleur'    =>1 ,
        'hauteur'    => 2500,
        'largeur'  =>2500 ,
        'prix'  =>2358 ,
    ],

			];

            Modele::insert($modeles);

        }


    }
}
