<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Modele;
use App\Models\Seeders;

class Modeles6PF1V_ALU extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $seeder = Modele::where('type',6)->where('genre',2)->count();

        //Check if the seeder exist in the DB
        //Porte fenetre 1V   //PVC
        if ($seeder==0) {
            $modeles =
            [
            /*larg= 380*/
				[
                    'genre'    =>2 ,
					'type'    =>6 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 420,
                    'largeur'  =>380 ,
                    'prix'  =>356 ,
				],
                [
                    'genre'    =>2 ,
					'type'    =>6 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 500,
                    'largeur'  =>380 ,
                    'prix'  =>370 ,
				],
                [
                    'genre'    =>2 ,
					'type'    =>6 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 600,
                    'largeur'  =>380 ,
                    'prix'  =>385 ,
				],
                [
                    'genre'    =>2 ,
					'type'    =>6 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 700,
                    'largeur'  =>380 ,
                    'prix'  =>400 ,
				],
                [
                    'genre'    =>2 ,
					'type'    =>6 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 800,
                    'largeur'  =>380 ,
                    'prix'  =>415 ,
				],
            /*larg= 400*/
				[
                    'genre'    =>2 ,
					'type'    =>6 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 420,
                    'largeur'  =>400 ,
                    'prix'  =>356 ,
				],
                [
                    'genre'    =>2 ,
					'type'    =>6 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 500,
                    'largeur'  =>400 ,
                    'prix'  =>370 ,
				],
                [
                    'genre'    =>2 ,
					'type'    =>6 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 600,
                    'largeur'  =>400 ,
                    'prix'  =>385 ,
				],
                [
                    'genre'    =>2 ,
					'type'    =>6 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 700,
                    'largeur'  =>400 ,
                    'prix'  =>400 ,
				],
                [
                    'genre'    =>2 ,
					'type'    =>6 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 800,
                    'largeur'  =>400 ,
                    'prix'  =>415 ,
				],
            /*larg= 500*/
                [
                    'genre'    =>2 ,
                    'type'    =>6 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 420,
                    'largeur'  =>500 ,
                    'prix'  =>371 ,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>6 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 500,
                    'largeur'  =>500 ,
                    'prix'  =>386 ,
				],
				[
                    'genre'    =>2 ,
					'type'    =>6 ,
                    'couleur'    => 1,
                    'hauteur'    =>600 ,
                    'largeur'  =>500 ,
                    'prix'  => 401,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>6 ,
                    'couleur'    => 1,
                    'hauteur'    => 700,
                    'largeur'  =>500 ,
                    'prix'  => 416,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>6 ,
                    'couleur'    => 1,
                    'hauteur'    => 800,
                    'largeur'  =>500 ,
                    'prix'  =>432 ,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>6 ,
                    'couleur'    => 1,
                    'hauteur'    => 900,
                    'largeur'  =>500 ,
                    'prix'  => 447,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>6 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1000,
                    'largeur'  =>500 ,
                    'prix'  => 462,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>6 ,
                    'couleur'    =>1 ,
                    'hauteur'    =>1100 ,
                    'largeur'  =>500 ,
                    'prix'  =>477 ,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>6 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1200,
                    'largeur'  =>500 ,
                    'prix'  => 490,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>6 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1300,
                    'largeur'  =>500 ,
                    'prix'  => 507,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>6 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1400,
                    'largeur'  =>500 ,
                    'prix'  => 522,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>6 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1500,
                    'largeur'  =>500 ,
                    'prix'  => 537,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>6 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1600,
                    'largeur'  =>500 ,
                    'prix'  => 552,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>6 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1700,
                    'largeur'  =>500 ,
                    'prix'  => 568,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>6 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1800,
                    'largeur'  =>500 ,
                    'prix'  =>582 ,
                ],
                [
                    'genre'    =>2 ,
					'type'    =>6 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1900,
                    'largeur'  =>500 ,
                    'prix'  =>598 ,
                ],
                [
                    'genre'    =>2 ,
					'type'    =>6 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2000,
                    'largeur'  =>500 ,
                    'prix'  =>613 ,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>6 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2100,
                    'largeur'  =>500 ,
                    'prix'  =>628 ,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>6 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2200,
                    'largeur'  =>500 ,
                    'prix'  =>643 ,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>6 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2300,
                    'largeur'  =>500 ,
                    'prix'  =>658 ,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>6 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2400,
                    'largeur'  =>500 ,
                    'prix'  =>673 ,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>6 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2500,
                    'largeur'  =>500 ,
                    'prix'  =>689 ,
                ],
                [
                    'genre'    =>2 ,
					'type'    =>6 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2600,
                    'largeur'  =>500 ,
                    'prix'  =>703 ,
                ],
                [
                    'genre'    =>2 ,
					'type'    =>6 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2700,
                    'largeur'  =>500 ,
                    'prix'  =>719 ,
                ],
                [
                    'genre'    =>2 ,
					'type'    =>6 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2800,
                    'largeur'  =>500 ,
                    'prix'  =>734 ,
                ],
             /*Larg= 600*/
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>6 ,
                'couleur'    =>1 ,
                'hauteur'    => 420,
                'largeur'  =>600 ,
                'prix'  => 386,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>6 ,
                'couleur'    =>1 ,
                'hauteur'    => 500,
                'largeur'  =>600 ,
                'prix'  => 402,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>6 ,
                'couleur'    => 1,
                'hauteur'    =>600 ,
                'largeur'  =>600 ,
                'prix'  => 417,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>6 ,
                'couleur'    => 1,
                'hauteur'    => 700,
                'largeur'  =>600 ,
                'prix'  => 433,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>6 ,
                'couleur'    => 1,
                'hauteur'    => 800,
                'largeur'  =>600 ,
                'prix'  => 448,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>6 ,
                'couleur'    => 1,
                'hauteur'    => 900,
                'largeur'  =>600 ,
                'prix'  => 464,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>6 ,
                'couleur'    =>1 ,
                'hauteur'    => 1000,
                'largeur'  =>600 ,
                'prix'  => 479,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>6 ,
                'couleur'    =>1 ,
                'hauteur'    =>1100 ,
                'largeur'  =>600 ,
                'prix'  => 495,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>6 ,
                'couleur'    =>1 ,
                'hauteur'    => 1200,
                'largeur'  =>600 ,
                'prix'  => 511,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>6 ,
                'couleur'    =>1 ,
                'hauteur'    => 1300,
                'largeur'  =>600 ,
                'prix'  => 526,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>6 ,
                'couleur'    =>1 ,
                'hauteur'    => 1400,
                'largeur'  =>600 ,
                'prix'  => 541,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>6 ,
                'couleur'    =>1 ,
                'hauteur'    => 1500,
                'largeur'  =>600 ,
                'prix'  => 557,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>6 ,
                'couleur'    =>1 ,
                'hauteur'    => 1600,
                'largeur'  =>600 ,
                'prix'  =>572 ,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>6 ,
                'couleur'    =>1 ,
                'hauteur'    => 1700,
                'largeur'  =>600 ,
                'prix'  => 588,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>6 ,
                'couleur'    =>1 ,
                'hauteur'    => 1800,
                'largeur'  =>600 ,
                'prix'  => 603,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>6 ,
                'couleur'    =>1 ,
                'hauteur'    => 1900,
                'largeur'  =>600 ,
                'prix'  => 619,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>6 ,
                'couleur'    =>1 ,
                'hauteur'    => 2000,
                'largeur'  =>600 ,
                'prix'  => 634,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>6 ,
                'couleur'    =>1 ,
                'hauteur'    => 2100,
                'largeur'  =>600 ,
                'prix'  => 650,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>6 ,
                'couleur'    =>1 ,
                'hauteur'    => 2200,
                'largeur'  =>600 ,
                'prix'  => 666,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>6 ,
                'couleur'    =>1 ,
                'hauteur'    => 2300,
                'largeur'  =>600 ,
                'prix'  => 681,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>6 ,
                'couleur'    =>1 ,
                'hauteur'    => 2400,
                'largeur'  =>600 ,
                'prix'  => 696,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>6 ,
                'couleur'    =>1 ,
                'hauteur'    => 2500,
                'largeur'  =>600 ,
                'prix'  => 712,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>6 ,
                'couleur'    =>1 ,
                'hauteur'    => 2600,
                'largeur'  =>600 ,
                'prix'  => 727,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>6 ,
                'couleur'    =>1 ,
                'hauteur'    => 2700,
                'largeur'  =>600 ,
                'prix'  => 743,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>6 ,
                'couleur'    =>1 ,
                'hauteur'    => 2800,
                'largeur'  =>600 ,
                'prix'  => 758,
            ],
         /*Larg=700*/
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>700 ,
            'prix'  => 417,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>700 ,
            'prix'  => 434,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>700 ,
            'prix'  => 449,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>700 ,
            'prix'  => 465,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>700 ,
            'prix'  => 481,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>700 ,
            'prix'  => 497,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>700 ,
            'prix'  => 513,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>700 ,
            'prix'  => 529,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>700 ,
            'prix'  => 545,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>700 ,
            'prix'  => 561,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>700 ,
            'prix'  => 576,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>700 ,
            'prix'  => 592,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>700 ,
            'prix'  => 608,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>700 ,
            'prix'  => 624,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>700 ,
            'prix'  => 640,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>700 ,
            'prix'  => 656,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>700 ,
            'prix'  => 672,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>700 ,
            'prix'  => 688,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>700 ,
            'prix'  => 704,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>700 ,
            'prix'  => 720,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>700 ,
            'prix'  => 735,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>700 ,
            'prix'  => 751,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>700 ,
            'prix'  => 767,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2800,
            'largeur'  =>700 ,
            'prix'  => 783,
        ],
        /*larg=800*/
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>800 ,
            'prix'  => 433,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>800 ,
            'prix'  => 449,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>800 ,
            'prix'  => 466,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>800 ,
            'prix'  => 482,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>800 ,
            'prix'  => 498,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>800 ,
            'prix'  => 515,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>800 ,
            'prix'  => 531,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>800 ,
            'prix'  => 547,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>800 ,
            'prix'  => 564,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>800 ,
            'prix'  => 580,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>800 ,
            'prix'  => 596,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>800 ,
            'prix'  => 613,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>800 ,
            'prix'  => 628,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>800 ,
            'prix'  => 645,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>800 ,
            'prix'  => 661,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>800 ,
            'prix'  => 677,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>800 ,
            'prix'  => 694,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>800 ,
            'prix'  => 710,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>800 ,
            'prix'  => 726,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>800 ,
            'prix'  => 743,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>800 ,
            'prix'  => 759,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2600,
            'largeur'  =>800 ,
            'prix'  => 775,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2700,
            'largeur'  =>800 ,
            'prix'  => 792,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2800,
            'largeur'  =>800 ,
            'prix'  => 808,
        ],
         /*Larg=900*/
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>900 ,
            'prix'  => 449,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>900 ,
            'prix'  => 465,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>900 ,
            'prix'  => 482,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>900 ,
            'prix'  => 499,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>900 ,
            'prix'  => 516,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>900 ,
            'prix'  => 532,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>900 ,
            'prix'  => 549,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>900 ,
            'prix'  => 566,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>900 ,
            'prix'  => 582,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>900 ,
            'prix'  => 599,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>900 ,
            'prix'  => 616,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>900 ,
            'prix'  => 632,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>900 ,
            'prix'  => 649,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>900 ,
            'prix'  => 666,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>900 ,
            'prix'  => 682,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>900 ,
            'prix'  => 699,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>900 ,
            'prix'  => 716,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>900 ,
            'prix'  => 732,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>900 ,
            'prix'  => 749,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>900 ,
            'prix'  => 766,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>900 ,
            'prix'  => 782,
        ],

        /*larg=1000*/
    /*    [
            'genre'    =>2 ,
 	 	 	'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1000 ,
            'prix'  => 211,
        ],*/
        [
            'genre'    =>2 ,
 	 	 	'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1000 ,
            'prix'  => 481,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1000 ,
            'prix'  => 498,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1000 ,
            'prix'  => 516,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1000 ,
            'prix'  => 532,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1000 ,
            'prix'  => 550,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1000 ,
            'prix'  => 567,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1000 ,
            'prix'  => 584,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1000 ,
            'prix'  => 601,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1000 ,
            'prix'  => 618,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1000 ,
            'prix'  =>635 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1000 ,
            'prix'  => 652,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1000 ,
            'prix'  => 669,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1000 ,
            'prix'  => 687,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1000 ,
            'prix'  => 703,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1000 ,
            'prix'  => 721,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1000 ,
            'prix'  => 738,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1000 ,
            'prix'  => 755,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1000 ,
            'prix'  => 772,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1000 ,
            'prix'  => 789,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1000 ,
            'prix'  => 806,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1000 ,
            'prix'  => 823,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1000 ,
            'prix'  => 840,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1000 ,
            'prix'  => 857,
        ],
        /*larg=1100*//*
        [
            'genre'    =>2 ,
 	 	 	'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1100 ,
            'prix'  => 220,
        ],*/
        [
            'genre'    =>2 ,
 	 	 	'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1100 ,
            'prix'  => 497,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1100 ,
            'prix'  => 515,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1100 ,
            'prix'  => 532,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1100 ,
            'prix'  => 550,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1100 ,
            'prix'  => 657,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1100 ,
            'prix'  => 585,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1100 ,
            'prix'  => 602,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1100 ,
            'prix'  => 620,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1100 ,
            'prix'  => 637,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1100 ,
            'prix'  =>655 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1100 ,
            'prix'  => 672,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1100 ,
            'prix'  => 690,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1100 ,
            'prix'  => 707,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1100 ,
            'prix'  => 725,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1100 ,
            'prix'  => 742,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1100 ,
            'prix'  => 759,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1100 ,
            'prix'  => 777,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1100 ,
            'prix'  => 795,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1100 ,
            'prix'  => 812,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1100 ,
            'prix'  => 829,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2600,
            'largeur'  =>1100 ,
            'prix'  => 847,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2700,
            'largeur'  =>1100 ,
            'prix'  => 864,
        ],
        /*larg=1200*/
    /*    [
            'genre'    =>2 ,
 	 	 	'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1200 ,
            'prix'  => 227,
        ],
        [
            'genre'    =>2 ,
 	 	 	'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1200 ,
            'prix'  => 236,
        ],*/
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1200 ,
            'prix'  => 531,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1200 ,
            'prix'  => 549,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1200 ,
            'prix'  => 567,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1200 ,
            'prix'  => 585,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1200 ,
            'prix'  => 603,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1200 ,
            'prix'  => 621,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1200 ,
            'prix'  => 639,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1200 ,
            'prix'  => 656,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1200 ,
            'prix'  =>674 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1200 ,
            'prix'  => 692,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1200 ,
            'prix'  => 710,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1200 ,
            'prix'  => 728,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1200 ,
            'prix'  => 746,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1200 ,
            'prix'  => 764,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1200 ,
            'prix'  => 781,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1200 ,
            'prix'  => 799,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1200 ,
            'prix'  => 817,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1200 ,
            'prix'  => 835,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1200 ,
            'prix'  => 853,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2600,
            'largeur'  =>1200 ,
            'prix'  => 871,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2700,
            'largeur'  =>1200 ,
            'prix'  => 889,
        ],
        /*larg=1300*/
    /*    [
            'genre'    =>2 ,
 	 	 	'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1300 ,
            'prix'  => 243,
        ],
        [
            'genre'    =>2 ,
 	 	 	'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1300 ,
            'prix'  => 257,
        ],*/
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1300 ,
            'prix'  => 548,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1300 ,
            'prix'  => 566,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1300 ,
            'prix'  => 585,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1300 ,
            'prix'  => 602,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1300 ,
            'prix'  => 621,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1300 ,
            'prix'  => 639,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1300 ,
            'prix'  => 657,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1300 ,
            'prix'  => 676,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1300 ,
            'prix'  =>694 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1300 ,
            'prix'  => 712,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1300 ,
            'prix'  => 730,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1300 ,
            'prix'  => 749,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1300 ,
            'prix'  => 767,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1300 ,
            'prix'  => 785,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1300 ,
            'prix'  => 803,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1300 ,
            'prix'  => 822,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1300 ,
            'prix'  => 840,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1300 ,
            'prix'  => 858,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1300 ,
            'prix'  => 877,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2600,
            'largeur'  =>1300 ,
            'prix'  => 895,
        ],
        /*larg=1400*/
    /*    [
            'genre'    =>2 ,
 	 	 	'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1400 ,
            'prix'  => 240,
        ],
        [
            'genre'    =>2 ,
 	 	 	'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1400 ,
            'prix'  => 252,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1400 ,
            'prix'  => 263,
        ],*/
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1400 ,
            'prix'  => 583,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1400 ,
            'prix'  => 601,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1400 ,
            'prix'  => 620,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1400 ,
            'prix'  => 639,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1400 ,
            'prix'  => 657,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1400 ,
            'prix'  => 676,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1400 ,
            'prix'  => 695,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1400 ,
            'prix'  =>714 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1400 ,
            'prix'  => 732,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1400 ,
            'prix'  => 751,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1400 ,
            'prix'  => 770,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1400 ,
            'prix'  => 788,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1400 ,
            'prix'  => 807,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1400 ,
            'prix'  => 825,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1400 ,
            'prix'  => 844,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1400 ,
            'prix'  => 863,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1400 ,
            'prix'  => 881,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1400 ,
            'prix'  => 900,
        ],
        /*larg=1500*/
    /*    [
            'genre'    =>2 ,
 	 	 	'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1500 ,
            'prix'  => 247,
        ],
        [
            'genre'    =>2 ,
 	 	 	'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1500 ,
            'prix'  => 261,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1500 ,
            'prix'  => 275,
        ],*/
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1500 ,
            'prix'  => 600,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1500 ,
            'prix'  => 619,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1500 ,
            'prix'  => 638,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1500 ,
            'prix'  => 657,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1500 ,
            'prix'  => 676,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1500 ,
            'prix'  => 695,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1500 ,
            'prix'  => 714,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1500 ,
            'prix'  =>733 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1500 ,
            'prix'  => 752,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1500 ,
            'prix'  => 771,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1500 ,
            'prix'  => 790,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1500 ,
            'prix'  => 809,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1500 ,
            'prix'  => 828,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1500 ,
            'prix'  => 847,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1500 ,
            'prix'  => 867,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1500 ,
            'prix'  => 885,
        ],
        /** larg=1600 */
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1600 ,
            'prix'  => 636,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1600 ,
            'prix'  => 655,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1600 ,
            'prix'  => 675,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1600 ,
            'prix'  => 694,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1600 ,
            'prix'  => 714,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1600 ,
            'prix'  => 733,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1600 ,
            'prix'  =>753 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1600 ,
            'prix'  => 772,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1600 ,
            'prix'  => 792,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1600 ,
            'prix'  => 811,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1600 ,
            'prix'  => 830,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1600 ,
            'prix'  => 850,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1600 ,
            'prix'  => 869,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>6 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1600 ,
            'prix'  => 889,
        ]


    ];

            Modele::insert($modeles);

        }


    }
}
