<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Modele;
use App\Models\Seeders;

class Modeles2Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $seeder = Modele::where('type',2)->count();

        //Check if the seeder exist in the DB
        // fenetre 1V
        if ($seeder==0) {
            $modeles =
            [
            /*larg= 500*/
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 500,
                    'largeur'  =>500 ,
                    'prix'  =>174 ,
				],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    => 1,
                    'hauteur'    =>600 ,
                    'largeur'  =>500 ,
                    'prix'  => 183,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    => 1,
                    'hauteur'    => 700,
                    'largeur'  =>500 ,
                    'prix'  => 187,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    => 1,
                    'hauteur'    => 800,
                    'largeur'  =>500 ,
                    'prix'  =>194 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    => 1,
                    'hauteur'    => 900,
                    'largeur'  =>500 ,
                    'prix'  => 204,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1000,
                    'largeur'  =>500 ,
                    'prix'  => 211,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    =>1100 ,
                    'largeur'  =>500 ,
                    'prix'  =>220 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1200,
                    'largeur'  =>500 ,
                    'prix'  => 227,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1300,
                    'largeur'  =>500 ,
                    'prix'  => 232,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1400,
                    'largeur'  =>500 ,
                    'prix'  => 240,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1500,
                    'largeur'  =>500 ,
                    'prix'  => 247,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1600,
                    'largeur'  =>500 ,
                    'prix'  => 260,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1700,
                    'largeur'  =>500 ,
                    'prix'  => 268,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1800,
                    'largeur'  =>500 ,
                    'prix'  =>276 ,
                ],
                [
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1900,
                    'largeur'  =>500 ,
                    'prix'  =>289 ,
                ],
                [
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2000,
                    'largeur'  =>500 ,
                    'prix'  =>298 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2100,
                    'largeur'  =>500 ,
                    'prix'  =>312 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2200,
                    'largeur'  =>500 ,
                    'prix'  =>370 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2300,
                    'largeur'  =>500 ,
                    'prix'  =>401 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2400,
                    'largeur'  =>500 ,
                    'prix'  =>410 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2500,
                    'largeur'  =>500 ,
                    'prix'  =>421 ,
                ],
             /*Larg= 600*/
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 500,
                'largeur'  =>600 ,
                'prix'  => 183,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    => 1,
                'hauteur'    =>600 ,
                'largeur'  =>600 ,
                'prix'  => 190,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    => 1,
                'hauteur'    => 700,
                'largeur'  =>600 ,
                'prix'  => 194,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    => 1,
                'hauteur'    => 800,
                'largeur'  =>600 ,
                'prix'  => 204,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    => 1,
                'hauteur'    => 900,
                'largeur'  =>600 ,
                'prix'  => 211,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 1000,
                'largeur'  =>600 ,
                'prix'  => 221,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    =>1100 ,
                'largeur'  =>600 ,
                'prix'  => 228,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 1200,
                'largeur'  =>600 ,
                'prix'  => 236,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 1300,
                'largeur'  =>600 ,
                'prix'  => 244,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 1400,
                'largeur'  =>600 ,
                'prix'  => 252,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 1500,
                'largeur'  =>600 ,
                'prix'  => 261,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 1600,
                'largeur'  =>600 ,
                'prix'  =>268 ,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 1700,
                'largeur'  =>600 ,
                'prix'  => 285,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 1800,
                'largeur'  =>600 ,
                'prix'  => 293,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 1900,
                'largeur'  =>600 ,
                'prix'  => 306,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 2000,
                'largeur'  =>600 ,
                'prix'  => 311,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 2100,
                'largeur'  =>600 ,
                'prix'  => 331,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 2200,
                'largeur'  =>600 ,
                'prix'  => 389,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 2300,
                'largeur'  =>600 ,
                'prix'  => 420,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 2400,
                'largeur'  =>600 ,
                'prix'  => 427,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 2500,
                'largeur'  =>600 ,
                'prix'  => 439,
            ],
         /*Larg=700*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>700 ,
            'prix'  => 187,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>700 ,
            'prix'  => 194,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>700 ,
            'prix'  => 204,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>700 ,
            'prix'  => 211,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>700 ,
            'prix'  => 220,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>700 ,
            'prix'  => 227,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>700 ,
            'prix'  => 235,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>700 ,
            'prix'  => 246,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>700 ,
            'prix'  => 258,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>700 ,
            'prix'  => 263,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>700 ,
            'prix'  => 275,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>700 ,
            'prix'  => 285,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>700 ,
            'prix'  => 299,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>700 ,
            'prix'  => 307,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>700 ,
            'prix'  => 321,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>700 ,
            'prix'  => 330,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>700 ,
            'prix'  => 346,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>700 ,
            'prix'  => 403,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>700 ,
            'prix'  => 438,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>700 ,
            'prix'  => 446,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>700 ,
            'prix'  => 457,
        ],
        /*larg=800*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>800 ,
            'prix'  => 194,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>800 ,
            'prix'  => 204,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>800 ,
            'prix'  => 211,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>800 ,
            'prix'  => 221,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>800 ,
            'prix'  => 230,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>800 ,
            'prix'  => 241,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>800 ,
            'prix'  => 250,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>800 ,
            'prix'  => 262,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>800 ,
            'prix'  => 270,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>800 ,
            'prix'  => 284,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>800 ,
            'prix'  => 292,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>800 ,
            'prix'  => 301,//361 ??
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>800 ,
            'prix'  => 317,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>800 ,
            'prix'  => 326,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>800 ,
            'prix'  => 340,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>800 ,
            'prix'  => 347,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>800 ,
            'prix'  => 364,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>800 ,
            'prix'  => 425,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>800 ,
            'prix'  => 456,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>800 ,
            'prix'  => 467,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>800 ,
            'prix'  => 478,
        ],
         /*Larg=900*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>900 ,
            'prix'  => 204,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>900 ,
            'prix'  => 211,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>900 ,
            'prix'  => 220,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>900 ,
            'prix'  => 230,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>900 ,
            'prix'  => 240,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>900 ,
            'prix'  => 252,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>900 ,
            'prix'  => 262,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>900 ,
            'prix'  => 273,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>900 ,
            'prix'  => 286,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>900 ,
            'prix'  => 295,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>900 ,
            'prix'  => 305,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>900 ,
            'prix'  => 314,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>900 ,
            'prix'  => 329,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>900 ,
            'prix'  => 340,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>900 ,
            'prix'  => 354,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>900 ,
            'prix'  => 370,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>900 ,
            'prix'  => 383,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>900 ,
            'prix'  => 439,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>900 ,
            'prix'  => 473,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>900 ,
            'prix'  => 487,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>900 ,
            'prix'  => 496,
        ],

        /*larg=1000*/
        [
            'genre'    =>1 ,
 	 	 	'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1000 ,
            'prix'  => 211,
        ],
        [
            'genre'    =>1 ,
 	 	 	'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1000 ,
            'prix'  => 221,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1000 ,
            'prix'  => 227,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1000 ,
            'prix'  => 241,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1000 ,
            'prix'  => 252,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1000 ,
            'prix'  => 266,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1000 ,
            'prix'  => 273,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1000 ,
            'prix'  => 286,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1000 ,
            'prix'  => 297,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1000 ,
            'prix'  => 308,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1000 ,
            'prix'  =>319 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1000 ,
            'prix'  => 331,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1000 ,
            'prix'  => 346,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1000 ,
            'prix'  => 354,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1000 ,
            'prix'  => 368,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1000 ,
            'prix'  => 390,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1000 ,
            'prix'  => 397,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1000 ,
            'prix'  => 457,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1000 ,
            'prix'  => 492,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1000 ,
            'prix'  => 536,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1000 ,
            'prix'  => 531,
        ],
        /*larg=1100*/
        [
            'genre'    =>1 ,
 	 	 	'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1100 ,
            'prix'  => 220,
        ],
        [
            'genre'    =>1 ,
 	 	 	'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1100 ,
            'prix'  => 228,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1100 ,
            'prix'  => 235,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1100 ,
            'prix'  => 250,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1100 ,
            'prix'  => 262,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1100 ,
            'prix'  => 273,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1100 ,
            'prix'  => 286,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1100 ,
            'prix'  => 297,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1100 ,
            'prix'  => 308,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1100 ,
            'prix'  => 319,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1100 ,
            'prix'  =>331 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1100 ,
            'prix'  => 344,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1100 ,
            'prix'  => 359,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1100 ,
            'prix'  => 369,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1100 ,
            'prix'  => 387,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1100 ,
            'prix'  => 403,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1100 ,
            'prix'  => 466,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1100 ,
            'prix'  => 529,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1100 ,
            'prix'  => 527,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1100 ,
            'prix'  => 545,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1100 ,
            'prix'  => 546,
        ],
        /*larg=1200*/
        [
            'genre'    =>1 ,
 	 	 	'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1200 ,
            'prix'  => 227,
        ],
        [
            'genre'    =>1 ,
 	 	 	'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1200 ,
            'prix'  => 236,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1200 ,
            'prix'  => 246,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1200 ,
            'prix'  => 262,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1200 ,
            'prix'  => 273,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1200 ,
            'prix'  => 286,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1200 ,
            'prix'  => 297,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1200 ,
            'prix'  => 312,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1200 ,
            'prix'  => 324,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1200 ,
            'prix'  => 334,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1200 ,
            'prix'  =>346 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1200 ,
            'prix'  => 359,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1200 ,
            'prix'  => 376,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1200 ,
            'prix'  => 387,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1200 ,
            'prix'  => 404,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1200 ,
            'prix'  => 438,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1200 ,
            'prix'  => 500,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1200 ,
            'prix'  => 537,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1200 ,
            'prix'  => 541,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1200 ,
            'prix'  => 553,
        ],
        /*larg=1300*/
        [
            'genre'    =>1 ,
 	 	 	'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1300 ,
            'prix'  => 232,
        ],
        [
            'genre'    =>1 ,
 	 	 	'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1300 ,
            'prix'  => 244,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1300 ,
            'prix'  => 258,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1300 ,
            'prix'  => 270,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1300 ,
            'prix'  => 283,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1300 ,
            'prix'  => 297,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1300 ,
            'prix'  => 308,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1300 ,
            'prix'  => 324,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1300 ,
            'prix'  => 334,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1300 ,
            'prix'  => 346,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1300 ,
            'prix'  =>360 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1300 ,
            'prix'  => 373,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1300 ,
            'prix'  => 387,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1300 ,
            'prix'  => 389,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1300 ,
            'prix'  => 437,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1300 ,
            'prix'  => 446,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1300 ,
            'prix'  => 515,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1300 ,
            'prix'  => 545,
        ],
        /*larg=1400*/
        [
            'genre'    =>1 ,
 	 	 	'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1400 ,
            'prix'  => 240,
        ],
        [
            'genre'    =>1 ,
 	 	 	'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1400 ,
            'prix'  => 252,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1400 ,
            'prix'  => 263,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1400 ,
            'prix'  => 284,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1400 ,
            'prix'  => 295,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1400 ,
            'prix'  => 308,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1400 ,
            'prix'  => 319,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1400 ,
            'prix'  => 334,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1400 ,
            'prix'  => 346,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1400 ,
            'prix'  => 360,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1400 ,
            'prix'  =>373 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1400 ,
            'prix'  => 384,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1400 ,
            'prix'  => 389,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1400 ,
            'prix'  => 423,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1400 ,
            'prix'  => 452,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1400 ,
            'prix'  => 454,
        ],
        /*larg=1500*/
        [
            'genre'    =>1 ,
 	 	 	'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1500 ,
            'prix'  => 247,
        ],
        [
            'genre'    =>1 ,
 	 	 	'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1500 ,
            'prix'  => 261,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1500 ,
            'prix'  => 275,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1500 ,
            'prix'  => 292,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1500 ,
            'prix'  => 305,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1500 ,
            'prix'  => 319,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1500 ,
            'prix'  => 331,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1500 ,
            'prix'  => 346,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1500 ,
            'prix'  => 360,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1500 ,
            'prix'  => 373,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1500 ,
            'prix'  =>426 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1500 ,
            'prix'  => 419,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1500 ,
            'prix'  => 430,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1500 ,
            'prix'  => 438,
        ],




            ];

            Modele::insert($modeles);

        }


    }
}
