<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Modele;
use App\Models\Seeders;

class Modeles8Seeder extends Seeder  // coulissant 1
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $seeder = Modele::where('type',8)->where('genre',2)->count();

        //Check if the seeder exist in the DB
        if ($seeder==0) {
            $modeles =
            [

         /*Larg=700*/
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>700 ,
            'prix'  => 879,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>700 ,
            'prix'  => 909,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>700 ,
            'prix'  => 938,
        ],

        /*larg=800*/
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>800 ,
            'prix'  => 905,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>800 ,
            'prix'  => 935,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>800 ,
            'prix'  => 963,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>800 ,
            'prix'  => 986,
        ],
          /*Larg=900*/
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>900 ,
            'prix'  => 931,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>900 ,
            'prix'  => 960,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>900 ,
            'prix'  => 989,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>900 ,
            'prix'  => 1014,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1000 ,
            'prix'  => 1046,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1100 ,
            'prix'  => 1078,
        ],
        /*larg=1000*/
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1000 ,
            'prix'  => 956,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1000 ,
            'prix'  => 986,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1000 ,
            'prix'  => 1014,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1000 ,
            'prix'  => 1043,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1000 ,
            'prix'  => 1074,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1000 ,
            'prix'  => 1105,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1000 ,
            'prix'  => 1143,
        ],

        /*larg=1100*/
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1100 ,
            'prix'  => 981,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1100 ,
            'prix'  => 1011,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1100 ,
            'prix'  => 1040,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1100 ,
            'prix'  => 1073,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1100 ,
            'prix'  => 1102,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1100 ,
            'prix'  => 1132,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1100 ,
            'prix'  => 1173,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1100 ,
            'prix'  => 1203,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1100 ,
            'prix'  => 1234,
        ],

        /*larg=1200*/
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1200 ,
            'prix'  => 1006,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1200 ,
            'prix'  => 1036,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1200 ,
            'prix'  => 1069,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1200 ,
            'prix'  => 1099,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1200 ,
            'prix'  => 1129,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1200 ,
            'prix'  => 1161,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1200 ,
            'prix'  => 1200,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1200 ,
            'prix'  => 1232,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1200 ,
            'prix'  => 1264,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1200 ,
            'prix'  =>1294 ,
        ],

        /*larg=1300*/
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1300 ,
            'prix'  => 1031,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1300 ,
            'prix'  => 1064,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1300 ,
            'prix'  => 1093,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1300 ,
            'prix'  => 1126,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1300 ,
            'prix'  => 1158,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1300 ,
            'prix'  => 1191,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1300 ,
            'prix'  => 1230,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1300 ,
            'prix'  => 1261,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1300 ,
            'prix'  => 1293,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1300 ,
            'prix'  =>1326 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1300 ,
            'prix'  => 1474,
        ],
        /*larg=1400*/
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1400 ,
            'prix'  => 1056,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1400 ,
            'prix'  => 1089,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1400 ,
            'prix'  => 1121,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1400 ,
            'prix'  => 1152,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1400 ,
            'prix'  => 1185,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1400 ,
            'prix'  => 1217,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1400 ,
            'prix'  => 1260,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1400 ,
            'prix'  => 1292,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1400 ,
            'prix'  => 1323,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1400 ,
            'prix'  =>1357 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1400 ,
            'prix'  => 1506,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1400 ,
            'prix'  => 1541,
        ],
        /*larg=1500*/
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1500 ,
            'prix'  => 1040,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1500 ,
            'prix'  => 1115,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1500 ,
            'prix'  => 1147,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1500 ,
            'prix'  => 1181,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1500 ,
            'prix'  => 1213,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1500 ,
            'prix'  => 1247,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1500 ,
            'prix'  => 1287,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1500 ,
            'prix'  => 1321,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1500 ,
            'prix'  => 1354,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1500 ,
            'prix'  =>1386 ,
        ],

        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    =>1600 ,
            'largeur'  =>1500 ,
            'prix'  => 1538,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    => 1700,
            'largeur'  =>1500 ,
            'prix'  => 1574,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    => 1800,
            'largeur'  =>1500 ,
            'prix'  => 1611,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    => 1900,
            'largeur'  =>1500 ,
            'prix'  => 1647,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1500 ,
            'prix'  => 1658,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    =>2100 ,
            'largeur'  =>1500 ,
            'prix'  => 1692,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1500 ,
            'prix'  => 1730,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1500 ,
            'prix'  => 1804,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1500 ,
            'prix'  => 1920,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1500 ,
            'prix'  =>1962 ,
        ],
       /*larg=1600*/
       [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    =>600 ,
        'largeur'  =>1600 ,
        'prix'  => 1107,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 700,
        'largeur'  =>1600 ,
        'prix'  => 1142,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 800,
        'largeur'  =>1600 ,
        'prix'  => 1175,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 900,
        'largeur'  =>1600 ,
        'prix'  => 1208,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1000,
        'largeur'  =>1600 ,
        'prix'  => 1243,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    =>1100 ,
        'largeur'  =>1600 ,
        'prix'  => 1275,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1200,
        'largeur'  =>1600 ,
        'prix'  => 1317,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1300,
        'largeur'  =>1600 ,
        'prix'  => 1352,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1400,
        'largeur'  =>1600 ,
        'prix'  => 1384,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1500,
        'largeur'  =>1600 ,
        'prix'  =>1419 ,
    ],

    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    =>1600 ,
        'largeur'  =>1600 ,
        'prix'  => 1571,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1700,
        'largeur'  =>1600 ,
        'prix'  => 1606,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1800,
        'largeur'  =>1600 ,
        'prix'  => 1644,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1900,
        'largeur'  =>1600 ,
        'prix'  => 1683,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2000,
        'largeur'  =>1600 ,
        'prix'  => 1691,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    =>2100 ,
        'largeur'  =>1600 ,
        'prix'  => 1730,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2200,
        'largeur'  =>1600 ,
        'prix'  => 1765,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2300,
        'largeur'  =>1600 ,
        'prix'  => 1838,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2400,
        'largeur'  =>1600 ,
        'prix'  => 1962,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2500,
        'largeur'  =>1600 ,
        'prix'  =>1999 ,
    ],
           /*larg=1700*/
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1700 ,
            'prix'  => 1133,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1700 ,
            'prix'  => 1168,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1700 ,
            'prix'  => 1201,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1700 ,
            'prix'  => 1235,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1700 ,
            'prix'  => 1269,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1700 ,
            'prix'  => 1304,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1700 ,
            'prix'  => 1346,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1700 ,
            'prix'  => 1379,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1700 ,
            'prix'  => 1415,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1700 ,
            'prix'  =>1447 ,
        ],

        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    =>1600 ,
            'largeur'  =>1700 ,
            'prix'  => 1603,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    => 1700,
            'largeur'  =>1700 ,
            'prix'  => 1641,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    => 1800,
            'largeur'  =>1700 ,
            'prix'  => 1678,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    => 1,
            'hauteur'    => 1900,
            'largeur'  =>1700 ,
            'prix'  => 1714,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1700 ,
            'prix'  => 1727,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    =>2100 ,
            'largeur'  =>1700 ,
            'prix'  => 1764,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1700 ,
            'prix'  => 1799,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1700 ,
            'prix'  => 1874,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1700 ,
            'prix'  => 1998,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>8 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1700 ,
            'prix'  =>2038 ,
        ],
       /*larg=1800*/
       [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    =>600 ,
        'largeur'  =>1800 ,
        'prix'  => 1157,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 700,
        'largeur'  =>1800 ,
        'prix'  => 1193,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 800,
        'largeur'  =>1800 ,
        'prix'  => 1226,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 900,
        'largeur'  =>1800 ,
        'prix'  => 1263,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1000,
        'largeur'  =>1800 ,
        'prix'  => 1298,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    =>1100 ,
        'largeur'  =>1800 ,
        'prix'  => 1340,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1200,
        'largeur'  =>1800 ,
        'prix'  => 1375,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1300,
        'largeur'  =>1800 ,
        'prix'  => 1408,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1400,
        'largeur'  =>1800 ,
        'prix'  => 1445,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1500,
        'largeur'  =>1800 ,
        'prix'  =>1480 ,
    ],

    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    =>1600 ,
        'largeur'  =>1800 ,
        'prix'  => 1612,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1700,
        'largeur'  =>1800 ,
        'prix'  => 1650,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1800,
        'largeur'  =>1800 ,
        'prix'  => 1687,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1900,
        'largeur'  =>1800 ,
        'prix'  => 1723,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2000,
        'largeur'  =>1800 ,
        'prix'  => 1722,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    =>2100 ,
        'largeur'  =>1800 ,
        'prix'  => 1759,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2200,
        'largeur'  =>1800 ,
        'prix'  => 1794,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2300,
        'largeur'  =>1800 ,
        'prix'  => 1911,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2400,
        'largeur'  =>1800 ,
        'prix'  => 2038,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2500,
        'largeur'  =>1800 ,
        'prix'  =>2079 ,
    ],
       /*larg=1900*/
       [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    =>600 ,
        'largeur'  =>1900 ,
        'prix'  => 1183,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 700,
        'largeur'  =>1900 ,
        'prix'  => 1219,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 800,
        'largeur'  =>1900 ,
        'prix'  => 1255,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 900,
        'largeur'  =>1900 ,
        'prix'  => 1289,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1000,
        'largeur'  =>1900 ,
        'prix'  => 1325,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    =>1100 ,
        'largeur'  =>1900 ,
        'prix'  => 1369,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1200,
        'largeur'  =>1900 ,
        'prix'  => 1404,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1300,
        'largeur'  =>1900 ,
        'prix'  => 1440,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1400,
        'largeur'  =>1900 ,
        'prix'  => 1475,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1500,
        'largeur'  =>1900 ,
        'prix'  =>1509 ,
    ],

    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    =>1600 ,
        'largeur'  =>1900 ,
        'prix'  => 1644,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1700,
        'largeur'  =>1900 ,
        'prix'  => 1684,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1800,
        'largeur'  =>1900 ,
        'prix'  => 1721,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1900,
        'largeur'  =>1900 ,
        'prix'  => 1785,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2000,
        'largeur'  =>1900 ,
        'prix'  => 1757,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    =>2100 ,
        'largeur'  =>1900 ,
        'prix'  => 1792,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2200,
        'largeur'  =>1900 ,
        'prix'  => 1828,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2300,
        'largeur'  =>1900 ,
        'prix'  => 1947,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2400,
        'largeur'  =>1900 ,
        'prix'  => 2075,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2500,
        'largeur'  =>1900 ,
        'prix'  =>2118 ,
    ],
       /*larg=2000*/
       [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    =>600 ,
        'largeur'  =>2000 ,
        'prix'  => 1209,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 700,
        'largeur'  =>2000 ,
        'prix'  => 1245,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 800,
        'largeur'  =>2000 ,
        'prix'  => 1282,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 900,
        'largeur'  =>2000 ,
        'prix'  => 1316,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1000,
        'largeur'  =>2000 ,
        'prix'  => 1352,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    =>1100 ,
        'largeur'  =>2000 ,
        'prix'  => 1397,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1200,
        'largeur'  =>2000 ,
        'prix'  => 1434,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1300,
        'largeur'  =>2000 ,
        'prix'  => 1469,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1400,
        'largeur'  =>2000 ,
        'prix'  => 1503,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1500,
        'largeur'  =>2000 ,
        'prix'  =>1541 ,
    ],

    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    =>1600 ,
        'largeur'  =>2000 ,
        'prix'  => 1676,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1700,
        'largeur'  =>2000 ,
        'prix'  => 1716,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1800,
        'largeur'  =>2000 ,
        'prix'  => 1754,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1900,
        'largeur'  =>2000 ,
        'prix'  => 1792,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2000,
        'largeur'  =>2000 ,
        'prix'  => 1790,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    =>2100 ,
        'largeur'  =>2000 ,
        'prix'  => 1827,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2200,
        'largeur'  =>2000 ,
        'prix'  => 1865,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2300,
        'largeur'  =>2000 ,
        'prix'  => 1984,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2400,
        'largeur'  =>2000 ,
        'prix'  => 2113,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2500,
        'largeur'  =>2000 ,
        'prix'  =>2154 ,
    ],
       /*larg=2100*/
       [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    =>600 ,
        'largeur'  =>2100 ,
        'prix'  => 1234,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 700,
        'largeur'  =>2100 ,
        'prix'  => 1271,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 800,
        'largeur'  =>2100 ,
        'prix'  => 1308,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 900,
        'largeur'  =>2100 ,
        'prix'  => 1344,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1000,
        'largeur'  =>2100 ,
        'prix'  => 1380,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    =>1100 ,
        'largeur'  =>2100 ,
        'prix'  => 1424,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1200,
        'largeur'  =>2100 ,
        'prix'  => 1461,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1300,
        'largeur'  =>2100 ,
        'prix'  => 1497,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1400,
        'largeur'  =>2100 ,
        'prix'  => 1534,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1500,
        'largeur'  =>2100 ,
        'prix'  =>1570 ,
    ],

    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    =>1600 ,
        'largeur'  =>2100 ,
        'prix'  => 1707,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1700,
        'largeur'  =>2100 ,
        'prix'  => 1748,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1800,
        'largeur'  =>2100 ,
        'prix'  => 1786,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1900,
        'largeur'  =>2100 ,
        'prix'  => 1825,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2000,
        'largeur'  =>2100 ,
        'prix'  => 1823,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    =>2100 ,
        'largeur'  =>2100 ,
        'prix'  => 1861,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2200,
        'largeur'  =>2100 ,
        'prix'  => 1899,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2300,
        'largeur'  =>2100 ,
        'prix'  => 2020,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2400,
        'largeur'  =>2100 ,
        'prix'  => 2152,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2500,
        'largeur'  =>2100 ,
        'prix'  =>2194 ,
    ],
       /*larg=2200*/
       [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    =>600 ,
        'largeur'  =>2200 ,
        'prix'  => 1260,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 700,
        'largeur'  =>2200 ,
        'prix'  => 1297,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 800,
        'largeur'  =>2200 ,
        'prix'  => 1333,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 900,
        'largeur'  =>2200 ,
        'prix'  => 1371,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1000,
        'largeur'  =>2200 ,
        'prix'  => 1407,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    =>1100 ,
        'largeur'  =>2200 ,
        'prix'  => 1454,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1200,
        'largeur'  =>2200 ,
        'prix'  => 1492,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1300,
        'largeur'  =>2200 ,
        'prix'  => 1528,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1400,
        'largeur'  =>2200 ,
        'prix'  => 1564,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1500,
        'largeur'  =>2200 ,
        'prix'  =>1603 ,
    ],

    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    =>1600 ,
        'largeur'  =>2200 ,
        'prix'  => 1740,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1700,
        'largeur'  =>2200 ,
        'prix'  => 1781,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1800,
        'largeur'  =>2200 ,
        'prix'  => 1819,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1900,
        'largeur'  =>2200 ,
        'prix'  => 1859,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2000,
        'largeur'  =>2200 ,
        'prix'  => 1857,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    =>2100 ,
        'largeur'  =>2200 ,
        'prix'  => 1895,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2200,
        'largeur'  =>2200 ,
        'prix'  => 1934,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2300,
        'largeur'  =>2200 ,
        'prix'  => 2056,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2400,
        'largeur'  =>2200 ,
        'prix'  => 2191,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2500,
        'largeur'  =>2200 ,
        'prix'  =>2235 ,
    ],
       /*larg=2300*/
       [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    =>600 ,
        'largeur'  =>2300 ,
        'prix'  => 1286,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 700,
        'largeur'  =>2300 ,
        'prix'  => 1324,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 800,
        'largeur'  =>2300 ,
        'prix'  => 1361,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 900,
        'largeur'  =>2300 ,
        'prix'  => 1399,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1000,
        'largeur'  =>2300 ,
        'prix'  => 1437,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    =>1100 ,
        'largeur'  =>2300 ,
        'prix'  => 1481,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1200,
        'largeur'  =>2300 ,
        'prix'  => 1520,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1300,
        'largeur'  =>2300 ,
        'prix'  => 1558,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1400,
        'largeur'  =>2300 ,
        'prix'  => 1595,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1500,
        'largeur'  =>2300 ,
        'prix'  =>1631 ,
    ],

    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    =>1600 ,
        'largeur'  =>2300 ,
        'prix'  => 1772,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1700,
        'largeur'  =>2300 ,
        'prix'  => 1813,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1800,
        'largeur'  =>2300 ,
        'prix'  => 1853,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1900,
        'largeur'  =>2300 ,
        'prix'  => 1894,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2000,
        'largeur'  =>2300 ,
        'prix'  => 1933,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    =>2100 ,
        'largeur'  =>2300 ,
        'prix'  => 1972,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2200,
        'largeur'  =>2300 ,
        'prix'  => 2014,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2300,
        'largeur'  =>2300 ,
        'prix'  => 2091,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2400,
        'largeur'  =>2300 ,
        'prix'  => 2228,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2500,
        'largeur'  =>2300 ,
        'prix'  =>2271 ,
    ],
       /*larg=2400*/
       [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    =>600 ,
        'largeur'  =>2400 ,
        'prix'  => 1310,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 700,
        'largeur'  =>2400 ,
        'prix'  => 1349,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 800,
        'largeur'  =>2400 ,
        'prix'  => 1388,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 900,
        'largeur'  =>2400 ,
        'prix'  => 1425,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1000,
        'largeur'  =>2400 ,
        'prix'  => 1463,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    =>1100 ,
        'largeur'  =>2400 ,
        'prix'  => 1510,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1200,
        'largeur'  =>2400 ,
        'prix'  => 1549,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1300,
        'largeur'  =>2400 ,
        'prix'  => 1587,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1400,
        'largeur'  =>2400 ,
        'prix'  => 1626,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1500,
        'largeur'  =>2400 ,
        'prix'  =>1663 ,
    ],

    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    =>1600 ,
        'largeur'  =>2400 ,
        'prix'  => 1805,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1700,
        'largeur'  =>2400 ,
        'prix'  => 1847,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1800,
        'largeur'  =>2400 ,
        'prix'  => 1886,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1900,
        'largeur'  =>2400 ,
        'prix'  => 1927,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2000,
        'largeur'  =>2400 ,
        'prix'  => 1968,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    =>2100 ,
        'largeur'  =>2400 ,
        'prix'  => 2010,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2200,
        'largeur'  =>2400 ,
        'prix'  => 2049,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2300,
        'largeur'  =>2400 ,
        'prix'  => 2129,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2400,
        'largeur'  =>2400 ,
        'prix'  => 2267,
    ],
    [
        'genre'    =>2 ,
            'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2500,
        'largeur'  =>2400 ,
        'prix'  =>2311 ,
    ],
       /*larg=2500*/
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    =>600 ,
        'largeur'  =>2500 ,
        'prix'  => 1336,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 700,
        'largeur'  =>2500 ,
        'prix'  => 1378,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 800,
        'largeur'  =>2500 ,
        'prix'  => 1414,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 900,
        'largeur'  =>2500 ,
        'prix'  => 1454,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1000,
        'largeur'  =>2500 ,
        'prix'  => 1492,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    =>1100 ,
        'largeur'  =>2500 ,
        'prix'  => 1539,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1200,
        'largeur'  =>2500 ,
        'prix'  => 1577,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1300,
        'largeur'  =>2500 ,
        'prix'  => 1618,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1400,
        'largeur'  =>2500 ,
        'prix'  => 1656,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1500,
        'largeur'  =>2500 ,
        'prix'  =>1695 ,
    ],

    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    =>1600 ,
        'largeur'  =>2500 ,
        'prix'  => 1836,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1700,
        'largeur'  =>2500 ,
        'prix'  => 1878,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1800,
        'largeur'  =>2500 ,
        'prix'  => 1920,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1900,
        'largeur'  =>2500 ,
        'prix'  => 1962,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2000,
        'largeur'  =>2500 ,
        'prix'  => 2003,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    =>2100 ,
        'largeur'  =>2500 ,
        'prix'  => 2043,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2200,
        'largeur'  =>2500 ,
        'prix'  => 2085,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2300,
        'largeur'  =>2500 ,
        'prix'  => 2165,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2400,
        'largeur'  =>2500 ,
        'prix'  => 2307,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2500,
        'largeur'  =>2500 ,
        'prix'  =>2351 ,
    ],

    /*larg=2600*/
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    =>600 ,
        'largeur'  =>2600 ,
        'prix'  => 1362  ,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 700,
        'largeur'  =>2600 ,
        'prix'  => 1407,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 800,
        'largeur'  =>2600 ,
        'prix'  => 1441,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 900,
        'largeur'  =>2600 ,
        'prix'  => 1483,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1000,
        'largeur'  =>2600 ,
        'prix'  => 1522,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    =>1100 ,
        'largeur'  =>2600 ,
        'prix'  => 1569,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1200,
        'largeur'  =>2600 ,
        'prix'  => 1607,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1300,
        'largeur'  =>2600 ,
        'prix'  => 1650,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1400,
        'largeur'  =>2600 ,
        'prix'  => 1687,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1500,
        'largeur'  =>2600 ,
        'prix'  =>1728 ,
    ],

    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    =>1600 ,
        'largeur'  =>2600 ,
        'prix'  => 1869,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1700,
        'largeur'  =>2600 ,
        'prix'  => 1912,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1800,
        'largeur'  =>2600 ,
        'prix'  => 1954,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1900,
        'largeur'  =>2600 ,
        'prix'  => 1997,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2000,
        'largeur'  =>2600 ,
        'prix'  => 2038,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    =>2100 ,
        'largeur'  =>2600 ,
        'prix'  => 2078,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2200,
        'largeur'  =>2600 ,
        'prix'  => 2120,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2300,
        'largeur'  =>2600 ,
        'prix'  => 2201,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2400,
        'largeur'  =>2600 ,
        'prix'  => 2347,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2500,
        'largeur'  =>2600 ,
        'prix'  =>2391 ,
    ],

    /*larg=2700*/
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    =>600 ,
        'largeur'  =>2700 ,
        'prix'  => 1388,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 700,
        'largeur'  =>2700 ,
        'prix'  => 1436,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 800,
        'largeur'  =>2700 ,
        'prix'  => 1468,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 900,
        'largeur'  =>2700 ,
        'prix'  => 1513,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1000,
        'largeur'  =>2700 ,
        'prix'  => 1552,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    =>1100 ,
        'largeur'  =>2700 ,
        'prix'  => 1599,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1200,
        'largeur'  =>2700 ,
        'prix'  => 1637,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1300,
        'largeur'  =>2700 ,
        'prix'  => 1682,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1400,
        'largeur'  =>2700 ,
        'prix'  => 1718,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1500,
        'largeur'  =>2700 ,
        'prix'  =>1761 ,
    ],

    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    =>1600 ,
        'largeur'  =>2700 ,
        'prix'  => 1902,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1700,
        'largeur'  =>2700 ,
        'prix'  => 1946,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1800,
        'largeur'  =>2700 ,
        'prix'  => 1988,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1900,
        'largeur'  =>2700 ,
        'prix'  => 2032,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2000,
        'largeur'  =>2700 ,
        'prix'  => 2073,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    =>2100 ,
        'largeur'  =>2700 ,
        'prix'  => 2113,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2200,
        'largeur'  =>2700 ,
        'prix'  => 2155,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2300,
        'largeur'  =>2700 ,
        'prix'  => 2237,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2400,
        'largeur'  =>2700 ,
        'prix'  => 2387,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2500,
        'largeur'  =>2700 ,
        'prix'  =>2431 ,
    ],

    /*larg=2800*/
       [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    =>600 ,
        'largeur'  =>2800 ,
        'prix'  => 1414,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 700,
        'largeur'  =>2800 ,
        'prix'  => 1465,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 800,
        'largeur'  =>2800 ,
        'prix'  => 1495,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 900,
        'largeur'  =>2800 ,
        'prix'  => 1544,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1000,
        'largeur'  =>2800 ,
        'prix'  => 1582,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    =>1100 ,
        'largeur'  =>2800 ,
        'prix'  => 1629,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1200,
        'largeur'  =>2800 ,
        'prix'  => 1667,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1300,
        'largeur'  =>2800 ,
        'prix'  => 1714,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1400,
        'largeur'  =>2800 ,
        'prix'  => 1749,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1500,
        'largeur'  =>2800 ,
        'prix'  =>1794 ,
    ],

    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    =>1600 ,
        'largeur'  =>2800 ,
        'prix'  => 1935,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1700,
        'largeur'  =>2800 ,
        'prix'  => 1980,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1800,
        'largeur'  =>2800 ,
        'prix'  => 2022,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1900,
        'largeur'  =>2800 ,
        'prix'  => 2067,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2000,
        'largeur'  =>2800 ,
        'prix'  => 2108,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    =>2100 ,
        'largeur'  =>2800 ,
        'prix'  => 2148,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2200,
        'largeur'  =>2800 ,
        'prix'  => 2190,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2300,
        'largeur'  =>2800 ,
        'prix'  => 2273,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2400,
        'largeur'  =>2800 ,
        'prix'  => 2427,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2500,
        'largeur'  =>2800 ,
        'prix'  =>2471 ,
    ],


    /*larg=2900*/
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    =>600 ,
        'largeur'  =>2900 ,
        'prix'  => 1440,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 700,
        'largeur'  =>2900 ,
        'prix'  => 1494,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 800,
        'largeur'  =>2900 ,
        'prix'  => 1525,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 900,
        'largeur'  =>2900 ,
        'prix'  => 1575,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1000,
        'largeur'  =>2900 ,
        'prix'  => 1612,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    =>1100 ,
        'largeur'  =>2900 ,
        'prix'  => 1659,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1200,
        'largeur'  =>2900 ,
        'prix'  => 1697,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1300,
        'largeur'  =>2900 ,
        'prix'  => 1746,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1400,
        'largeur'  =>2900 ,
        'prix'  => 1780,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1500,
        'largeur'  =>2900 ,
        'prix'  =>1827 ,
    ],

    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    =>1600 ,
        'largeur'  =>2900 ,
        'prix'  => 1968,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1700,
        'largeur'  =>2900 ,
        'prix'  => 2014,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1800,
        'largeur'  =>2900 ,
        'prix'  => 2056,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1900,
        'largeur'  =>2900 ,
        'prix'  => 2102,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2000,
        'largeur'  =>2900 ,
        'prix'  => 2143,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    =>2100 ,
        'largeur'  =>2900 ,
        'prix'  => 2183,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2200,
        'largeur'  =>2900 ,
        'prix'  => 2225,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2300,
        'largeur'  =>2900 ,
        'prix'  => 2309,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2400,
        'largeur'  =>2900 ,
        'prix'  => 2467,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2500,
        'largeur'  =>2900 ,
        'prix'  =>2511 ,
    ],

    /*larg=3000*/
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    =>600 ,
        'largeur'  =>3000 ,
        'prix'  => 1466,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 700,
        'largeur'  =>3000 ,
        'prix'  => 1523,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 800,
        'largeur'  =>3000 ,
        'prix'  => 1555,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 900,
        'largeur'  =>3000 ,
        'prix'  => 1606,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1000,
        'largeur'  =>3000 ,
        'prix'  => 1642,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    =>1100 ,
        'largeur'  =>3000 ,
        'prix'  => 1689,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1200,
        'largeur'  =>3000 ,
        'prix'  => 1732,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1300,
        'largeur'  =>3000 ,
        'prix'  => 1778,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1400,
        'largeur'  =>3000 ,
        'prix'  => 1810,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 1500,
        'largeur'  =>3000 ,
        'prix'  =>1860 ,
    ],

    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    =>1600 ,
        'largeur'  =>3000 ,
        'prix'  => 2001,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1700,
        'largeur'  =>3000 ,
        'prix'  => 2048,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1800,
        'largeur'  =>3000 ,
        'prix'  => 2090,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    => 1,
        'hauteur'    => 1900,
        'largeur'  =>3000 ,
        'prix'  => 2137,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2000,
        'largeur'  =>3000 ,
        'prix'  => 2173,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    =>2100 ,
        'largeur'  =>3000 ,
        'prix'  => 2218,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2200,
        'largeur'  =>3000 ,
        'prix'  => 2260,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2300,
        'largeur'  =>3000 ,
        'prix'  => 2345,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2400,
        'largeur'  =>3000 ,
        'prix'  => 2507,
    ],
    [
        'genre'    =>2 ,
        'type'    =>8 ,
        'couleur'    =>1 ,
        'hauteur'    => 2500,
        'largeur'  =>3000 ,
        'prix'  =>2551 ,
    ],

			];

            Modele::insert($modeles);

        }


    }
}
