<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Modele;
use App\Models\Seeders;

class Modeles3Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $seeder = Modele::where('type',3)->count();

        //Check if the seeder exist in the DB
        // fenetre 2V   pvc
        if ($seeder==0) {
            $modeles =
            [
            /*larg= 900*/
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 500,
                    'largeur'  =>900 ,
                    'prix'  => 372,
				],
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    => 1,
                    'hauteur'    =>600 ,
                    'largeur'  =>900 ,
                    'prix'  => 384,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    => 1,
                    'hauteur'    => 700,
                    'largeur'  =>900 ,
                    'prix'  => 396,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    => 1,
                    'hauteur'    => 800,
                    'largeur'  =>900 ,
                    'prix'  => 408,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    => 1,
                    'hauteur'    => 900,
                    'largeur'  =>900 ,
                    'prix'  => 417,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1000,
                    'largeur'  =>900 ,
                    'prix'  => 437,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    =>1100 ,
                    'largeur'  =>900 ,
                    'prix'  => 445,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1200,
                    'largeur'  =>900 ,
                    'prix'  => 456,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1300,
                    'largeur'  =>900 ,
                    'prix'  => 472,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1400,
                    'largeur'  =>900 ,
                    'prix'  => 480,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1500,
                    'largeur'  =>900 ,
                    'prix'  => 496 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1600,
                    'largeur'  =>900 ,
                    'prix'  => 508 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1700,
                    'largeur'  =>900 ,
                    'prix'  => 528 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1800,
                    'largeur'  =>900 ,
                    'prix'  => 538,
                ],
                [
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1900,
                    'largeur'  =>900 ,
                    'prix'  => 565 ,
                ],
                [
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2000,
                    'largeur'  =>900 ,
                    'prix'  => 575,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2100,
                    'largeur'  =>900 ,
                    'prix'  => 590,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2200,
                    'largeur'  =>900 ,
                    'prix'  => 600,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2300,
                    'largeur'  =>900 ,
                    'prix'  => 630,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2400,
                    'largeur'  =>900 ,
                    'prix'  => 642,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2500,
                    'largeur'  =>900 ,
                    'prix'  =>660 ,
                ],

            /*Larg= 1000*/
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 500,
                'largeur'  =>1000 ,
                'prix'  => 377,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    => 1,
                'hauteur'    =>600 ,
                'largeur'  =>1000 ,
                'prix'  => 389,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    => 1,
                'hauteur'    => 700,
                'largeur'  =>1000 ,
                'prix'  => 399,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    => 1,
                'hauteur'    => 800,
                'largeur'  =>1000 ,
                'prix'  => 414,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    => 1,
                'hauteur'    => 900,
                'largeur'  =>1000 ,
                'prix'  => 426,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 1000,
                'largeur'  =>1000 ,
                'prix'  => 442,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    =>1100 ,
                'largeur'  =>1000 ,
                'prix'  => 451,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 1200,
                'largeur'  =>1000 ,
                'prix'  => 462,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 1300,
                'largeur'  =>1000 ,
                'prix'  => 476,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 1400,
                'largeur'  =>1000 ,
                'prix'  => 488,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 1500,
                'largeur'  =>1000 ,
                'prix'  => 508,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 1600,
                'largeur'  =>1000 ,
                'prix'  =>521 ,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 1700,
                'largeur'  =>1000 ,
                'prix'  => 538,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 1800,
                'largeur'  =>1000 ,
                'prix'  => 554,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 1900,
                'largeur'  =>1000 ,
                'prix'  => 578,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 2000,
                'largeur'  =>1000 ,
                'prix'  => 591,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 2100,
                'largeur'  =>1000 ,
                'prix'  => 604,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 2200,
                'largeur'  =>1000 ,
                'prix'  => 620,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 2300,
                'largeur'  =>1000 ,
                'prix'  => 642,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 2400,
                'largeur'  =>1000 ,
                'prix'  => 659,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 2500,
                'largeur'  =>1000 ,
                'prix'  => 679,
            ],
        /*Larg=1100*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>1100 ,
            'prix'  => 385,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1100 ,
            'prix'  => 397,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1100 ,
            'prix'  => 409,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1100 ,
            'prix'  => 421,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1100 ,
            'prix'  => 435,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1100 ,
            'prix'  => 448,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1100 ,
            'prix'  => 458,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1100 ,
            'prix'  => 473,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1100 ,
            'prix'  => 485,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1100 ,
            'prix'  => 502,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1100 ,
            'prix'  => 521,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1100 ,
            'prix'  => 537,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1100 ,
            'prix'  => 554,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1100 ,
            'prix'  => 571,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1100 ,
            'prix'  => 593,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1100 ,
            'prix'  => 604,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1100 ,
            'prix'  => 637,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1100 ,
            'prix'  => 637,//faute ?
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1100 ,
            'prix'  => 661,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1100 ,
            'prix'  => 676,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1100 ,
            'prix'  => 697,
        ],

        /*larg=1200*/
        [
            'genre'    =>1 ,
 	 	 	'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>1200 ,
            'prix'  => 394,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1200 ,
            'prix'  => 404,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1200 ,
            'prix'  => 416,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1200 ,
            'prix'  => 427,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1200 ,
            'prix'  => 440,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1200 ,
            'prix'  => 546,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1200 ,
            'prix'  => 468,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1200 ,
            'prix'  => 482,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1200 ,
            'prix'  => 497,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1200 ,
            'prix'  => 515,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1200 ,
            'prix'  => 533,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1200 ,
            'prix'  => 546,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1200 ,
            'prix'  => 569,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1200 ,
            'prix'  => 583,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1200 ,
            'prix'  => 608,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1200 ,
            'prix'  => 622,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1200 ,
            'prix'  => 653,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1200 ,
            'prix'  => 652,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1200 ,
            'prix'  => 680,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1200 ,
            'prix'  => 693,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1200 ,
            'prix'  => 716,
        ],

        /*Larg=1300*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>1300 ,
            'prix'  => 400,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1300 ,
            'prix'  => 411,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1300 ,
            'prix'  => 420,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1300 ,
            'prix'  => 436,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1300 ,
            'prix'  => 448,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1300 ,
            'prix'  => 459,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1300 ,
            'prix'  => 477,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1300 ,
            'prix'  => 493,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1300 ,
            'prix'  => 512,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1300 ,
            'prix'  => 529,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1300 ,
            'prix'  => 543,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1300 ,
            'prix'  => 562,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1300 ,
            'prix'  => 583,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1300 ,
            'prix'  => 597,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1300 ,
            'prix'  => 640,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1300 ,
            'prix'  => 637,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1300 ,
            'prix'  => 671,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1300 ,
            'prix'  => 665,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1300 ,
            'prix'  => 697,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1300 ,
            'prix'  => 713,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1300 ,
            'prix'  => 733,
        ],
        /*larg=1400*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1400 ,
            'prix'  => 412,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1400 ,
            'prix'  => 420,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1400 ,
            'prix'  => 432,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1400 ,
            'prix'  => 445,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1400 ,
            'prix'  => 454,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1400 ,
            'prix'  => 477,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1400 ,
            'prix'  => 488,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1400 ,
            'prix'  => 509,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1400 ,
            'prix'  => 523,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1400 ,
            'prix'  => 543,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1400 ,
            'prix'  =>651 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1400 ,
            'prix'  => 576,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1400 ,
            'prix'  => 597,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1400 ,
            'prix'  => 612,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1400 ,
            'prix'  => 655,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1400 ,
            'prix'  => 655,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1400 ,
            'prix'  => 688,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1400 ,
            'prix'  => 688,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1400 ,
            'prix'  => 716,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1400 ,
            'prix'  => 731,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1400 ,
            'prix'  => 755,
        ],
        /*larg=1500*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1500 ,
            'prix'  => 428,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1500 ,
            'prix'  => 424,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1500 ,
            'prix'  => 437,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1500 ,
            'prix'  => 451,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1500 ,
            'prix'  => 460,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1500 ,
            'prix'  => 484,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1500 ,
            'prix'  => 502,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1500 ,
            'prix'  => 518,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1500 ,
            'prix'  => 534,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1500 ,
            'prix'  => 556,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1500 ,
            'prix'  =>573 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1500 ,
            'prix'  => 592,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1500 ,
            'prix'  => 612,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1500 ,
            'prix'  => 626,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1500 ,
            'prix'  => 671,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1500 ,
            'prix'  => 671,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1500 ,
            'prix'  => 701,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1500 ,
            'prix'  => 701,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1500 ,
            'prix'  => 716,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1500 ,
            'prix'  => 733,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1500 ,
            'prix'  => 748,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1500 ,
            'prix'  => 774,
        ],
        /*larg=1600*/ // erreur à vérifier
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1600 ,
            'prix'  => 434,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1600 ,
            'prix'  => 433,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1600 ,
            'prix'  => 446,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1600 ,
            'prix'  => 459,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1600 ,
            'prix'  => 476,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1600 ,
            'prix'  => 494,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1600 ,
            'prix'  => 514,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1600 ,
            'prix'  => 531,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1600 ,
            'prix'  => 547,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1600 ,
            'prix'  => 567,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1600 ,
            'prix'  =>587 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1600 ,
            'prix'  => 602,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1600 ,
            'prix'  => 624,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1600 ,
            'prix'  => 642,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1600 ,
            'prix'  => 685,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1600 ,
            'prix'  => 685,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1600 ,
            'prix'  => 718,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1600 ,
            'prix'  => 720,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1600 ,
            'prix'  => 748,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1600 ,
            'prix'  => 766,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1600 ,
            'prix'  => 792,
        ],

        /*larg=1700*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1700 ,
            'prix'  => 442,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1700 ,
            'prix'  => 443,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1700 ,
            'prix'  => 452,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1700 ,
            'prix'  => 466,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1700 ,
            'prix'  => 483,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1700 ,
            'prix'  => 505,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1700 ,
            'prix'  => 524,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1700 ,
            'prix'  => 542,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1700 ,
            'prix'  => 560,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1700 ,
            'prix'  => 581,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1700 ,
            'prix'  =>598 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1700 ,
            'prix'  => 617,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1700 ,
            'prix'  => 639,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1700 ,
            'prix'  => 656,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1700 ,
            'prix'  => 699,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1700 ,
            'prix'  => 699,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1700 ,
            'prix'  => 735,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1700 ,
            'prix'  => 735,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1700 ,
            'prix'  => 766,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1700 ,
            'prix'  => 782,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1700 ,
            'prix'  => 805,
        ],

        /*larg=1800*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1800 ,
            'prix'  => 449,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1800 ,
            'prix'  => 460,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1800 ,
            'prix'  => 460,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1700 ,
            'prix'  => 480,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1800 ,
            'prix'  => 496,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1800 ,
            'prix'  => 518,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1800 ,
            'prix'  => 536,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1800 ,
            'prix'  => 558,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1800 ,
            'prix'  => 574,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1800 ,
            'prix'  => 594,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1800 ,
            'prix'  =>614 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1800 ,
            'prix'  => 634,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1800 ,
            'prix'  => 657,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1800 ,
            'prix'  => 675,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1800 ,
            'prix'  => 721,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1800 ,
            'prix'  => 718,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1800 ,
            'prix'  => 757,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1800 ,
            'prix'  => 753,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1800 ,
            'prix'  => 783,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1800 ,
            'prix'  => 784,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1800 ,
            'prix'  => 806,
        ],

        /*larg=1900*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 600,
            'largeur'  =>1900 ,
            'prix'  => 466,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1900 ,
            'prix'  => 467,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1900 ,
            'prix'  => 493,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1900 ,
            'prix'  => 512,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1900 ,
            'prix'  => 536,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1900 ,
            'prix'  => 555,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1900 ,
            'prix'  => 575,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1900 ,
            'prix'  => 594,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1900 ,
            'prix'  => 614,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1900 ,
            'prix'  =>634 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1900 ,
            'prix'  => 654,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1900 ,
            'prix'  => 678,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1900 ,
            'prix'  => 695,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1900 ,
            'prix'  => 735,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1900 ,
            'prix'  => 737,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1900 ,
            'prix'  => 776,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1900 ,
            'prix'  => 776,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1900 ,
            'prix'  => 805,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1900 ,
            'prix'  => 806,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1900 ,
            'prix'  => 873,
        ],
        /*larg=2000*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>2000 ,
            'prix'  => 473,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2000 ,
            'prix'  => 479,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2000 ,
            'prix'  => 505,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2000 ,
            'prix'  => 521,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2000 ,
            'prix'  => 546,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2000 ,
            'prix'  => 565,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2000 ,
            'prix'  => 586,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2000 ,
            'prix'  => 604,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2000 ,
            'prix'  => 625,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2000 ,
            'prix'  =>646 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2000 ,
            'prix'  => 664,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2000 ,
            'prix'  => 690,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2000 ,
            'prix'  => 710,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2000 ,
            'prix'  => 754,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2000 ,
            'prix'  => 754,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>2000 ,
            'prix'  => 788,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2000 ,
            'prix'  => 793,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>2000 ,
            'prix'  => 823,
        ],
        /*larg=2100*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>2100 ,
            'prix'  => 483,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2100 ,
            'prix'  => 495,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2100 ,
            'prix'  => 514,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2100 ,
            'prix'  => 530,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2100 ,
            'prix'  => 556,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2100 ,
            'prix'  => 576,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2100 ,
            'prix'  => 598,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2100 ,
            'prix'  => 615,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2100 ,
            'prix'  => 638,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2100 ,
            'prix'  =>658 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2100 ,
            'prix'  => 679,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2100 ,
            'prix'  => 703,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2100 ,
            'prix'  => 725,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2100 ,
            'prix'  => 768,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2100 ,
            'prix'  => 768,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>2100 ,
            'prix'  => 804,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2100 ,
            'prix'  => 806,
        ],
        /*larg=2200*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>2200 ,
            'prix'  => 491,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2200 ,
            'prix'  => 523,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2200 ,
            'prix'  => 520,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2200 ,
            'prix'  => 543,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2200 ,
            'prix'  => 566,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2200 ,
            'prix'  => 487,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2200 ,
            'prix'  => 609,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2200 ,
            'prix'  => 627,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2200 ,
            'prix'  => 651,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2200 ,
            'prix'  =>675 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2200 ,
            'prix'  => 695,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2200 ,
            'prix'  => 720,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2200 ,
            'prix'  => 739,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2200 ,
            'prix'  => 782,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2200 ,
            'prix'  => 784,
        ],
        /*larg=2300*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>2300 ,
            'prix'  => 537,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2300 ,
            'prix'  => 532,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2300 ,
            'prix'  => 552,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2300 ,
            'prix'  => 577,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2300 ,
            'prix'  => 600,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2300 ,
            'prix'  => 620,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2300 ,
            'prix'  => 642,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2300 ,
            'prix'  => 664,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2300 ,
            'prix'  => 688,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2300 ,
            'prix'  =>698 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2300 ,
            'prix'  => 705,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2300 ,
            'prix'  => 736,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2300 ,
            'prix'  => 758,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2200 ,
            'prix'  => 784,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2300 ,
            'prix'  => 802,
        ],
        /*larg=2400*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2400 ,
            'prix'  => 554,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2400 ,
            'prix'  => 561,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2400 ,
            'prix'  => 562,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2400 ,
            'prix'  => 589,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2400 ,
            'prix'  => 611,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2400 ,
            'prix'  => 630,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2400 ,
            'prix'  => 653,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2400 ,
            'prix'  => 678,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2400 ,
            'prix'  =>698 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2400 ,
            'prix'  => 721,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2400 ,
            'prix'  => 751,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2400 ,
            'prix'  => 773,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2400 ,
            'prix'  => 851,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2400 ,
            'prix'  => 870,
        ],

        /*larg=2700*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2400 ,
            'prix'  => 571,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2400 ,
            'prix'  => 574,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2400 ,
            'prix'  => 573,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2400 ,
            'prix'  => 601,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2400 ,
            'prix'  => 622,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2400 ,
            'prix'  => 643,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2400 ,
            'prix'  => 665,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2400 ,
            'prix'  => 689,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2400 ,
            'prix'  =>713 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2400 ,
            'prix'  => 736,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2400 ,
            'prix'  => 752,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2400 ,
            'prix'  => 775,
        ],

        /*larg=2400*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2400 ,
            'prix'  => 554,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2400 ,
            'prix'  => 561,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2400 ,
            'prix'  => 562,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2400 ,
            'prix'  => 589,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2400 ,
            'prix'  => 611,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2400 ,
            'prix'  => 630,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2400 ,
            'prix'  => 653,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2400 ,
            'prix'  => 678,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2400 ,
            'prix'  =>698 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2400 ,
            'prix'  => 721,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2400 ,
            'prix'  => 751,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2400 ,
            'prix'  => 773,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2400 ,
            'prix'  => 851,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2400 ,
            'prix'  => 870,
        ],

        /*larg=2500*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2500 ,
            'prix'  => 571,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2500 ,
            'prix'  => 574,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2500 ,
            'prix'  => 573,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2500 ,
            'prix'  => 601,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2500 ,
            'prix'  => 622,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2500 ,
            'prix'  => 643,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2500 ,
            'prix'  => 665,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2500 ,
            'prix'  => 689,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2500 ,
            'prix'  =>713 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2500 ,
            'prix'  => 736,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2500 ,
            'prix'  => 752,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2500 ,
            'prix'  => 775,
        ],
        /*larg=2600*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2600 ,
            'prix'  => 585,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2600 ,
            'prix'  => 587,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2600 ,
            'prix'  => 584,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2600 ,
            'prix'  => 608,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2600 ,
            'prix'  => 632,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2600 ,
            'prix'  => 654,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2600 ,
            'prix'  => 777,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2600 ,
            'prix'  => 700,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2600 ,
            'prix'  =>725 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2600 ,
            'prix'  => 747,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2600 ,
            'prix'  => 754,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2600 ,
            'prix'  => 776,
        ],

            ];

            Modele::insert($modeles);

        }


    }
}
