<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Modele;
use App\Models\Seeders;

class Modeles2Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $seeder = Modele::where('type',2)->count();

        //Check if the seeder exist in the DB
        // fenetre 1V   pvc
        if ($seeder==0) {
            $modeles =
            [
            /*larg= 500*/
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 500,
                    'largeur'  =>500 ,
                    'prix'  =>162 ,
				],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    => 1,
                    'hauteur'    =>600 ,
                    'largeur'  =>500 ,
                    'prix'  => 171,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    => 1,
                    'hauteur'    => 700,
                    'largeur'  =>500 ,
                    'prix'  => 173,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    => 1,
                    'hauteur'    => 800,
                    'largeur'  =>500 ,
                    'prix'  =>180 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    => 1,
                    'hauteur'    => 900,
                    'largeur'  =>500 ,
                    'prix'  => 190,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1000,
                    'largeur'  =>500 ,
                    'prix'  => 196,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    =>1100 ,
                    'largeur'  =>500 ,
                    'prix'  =>204 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1200,
                    'largeur'  =>500 ,
                    'prix'  => 210,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1300,
                    'largeur'  =>500 ,
                    'prix'  => 215,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1400,
                    'largeur'  =>500 ,
                    'prix'  => 222,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1500,
                    'largeur'  =>500 ,
                    'prix'  => 228,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1600,
                    'largeur'  =>500 ,
                    'prix'  => 240,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1700,
                    'largeur'  =>500 ,
                    'prix'  => 248,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1800,
                    'largeur'  =>500 ,
                    'prix'  =>255 ,
                ],
                [
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1900,
                    'largeur'  =>500 ,
                    'prix'  =>268 ,
                ],
                [
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2000,
                    'largeur'  =>500 ,
                    'prix'  =>276 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2100,
                    'largeur'  =>500 ,
                    'prix'  =>281 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2200,
                    'largeur'  =>500 ,
                    'prix'  =>290 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2300,
                    'largeur'  =>500 ,
                    'prix'  =>301 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2400,
                    'largeur'  =>500 ,
                    'prix'  =>309 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>2 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2500,
                    'largeur'  =>500 ,
                    'prix'  =>320 ,
                ],
             /*Larg= 600*/
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 500,
                'largeur'  =>600 ,
                'prix'  => 171,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    => 1,
                'hauteur'    =>600 ,
                'largeur'  =>600 ,
                'prix'  => 177,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    => 1,
                'hauteur'    => 700,
                'largeur'  =>600 ,
                'prix'  => 180,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    => 1,
                'hauteur'    => 800,
                'largeur'  =>600 ,
                'prix'  => 190,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    => 1,
                'hauteur'    => 900,
                'largeur'  =>600 ,
                'prix'  => 196,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 1000,
                'largeur'  =>600 ,
                'prix'  => 204,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    =>1100 ,
                'largeur'  =>600 ,
                'prix'  => 210,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 1200,
                'largeur'  =>600 ,
                'prix'  => 218,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 1300,
                'largeur'  =>600 ,
                'prix'  => 225,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 1400,
                'largeur'  =>600 ,
                'prix'  => 234,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 1500,
                'largeur'  =>600 ,
                'prix'  => 242,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 1600,
                'largeur'  =>600 ,
                'prix'  =>248 ,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 1700,
                'largeur'  =>600 ,
                'prix'  => 265,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 1800,
                'largeur'  =>600 ,
                'prix'  => 273,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 1900,
                'largeur'  =>600 ,
                'prix'  => 286,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 2000,
                'largeur'  =>600 ,
                'prix'  => 290,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 2100,
                'largeur'  =>600 ,
                'prix'  => 301,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 2200,
                'largeur'  =>600 ,
                'prix'  => 309,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 2300,
                'largeur'  =>600 ,
                'prix'  => 320,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 2400,
                'largeur'  =>600 ,
                'prix'  => 327,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>2 ,
                'couleur'    =>1 ,
                'hauteur'    => 2500,
                'largeur'  =>600 ,
                'prix'  => 340,
            ],
         /*Larg=700*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>700 ,
            'prix'  => 177,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>700 ,
            'prix'  => 180,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>700 ,
            'prix'  => 190,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>700 ,
            'prix'  => 196,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>700 ,
            'prix'  => 204,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>700 ,
            'prix'  => 210,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>700 ,
            'prix'  => 218,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>700 ,
            'prix'  => 228,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>700 ,
            'prix'  => 240,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>700 ,
            'prix'  => 244,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>700 ,
            'prix'  => 255,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>700 ,
            'prix'  => 265,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>700 ,
            'prix'  => 279,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>700 ,
            'prix'  => 286,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>700 ,
            'prix'  => 301,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>700 ,
            'prix'  => 309,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>700 ,
            'prix'  => 316,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>700 ,
            'prix'  => 324,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>700 ,
            'prix'  => 340,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>700 ,
            'prix'  => 347,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>700 ,
            'prix'  => 358,
        ],
        /*larg=800*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>800 ,
            'prix'  => 197,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>800 ,
            'prix'  => 193,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>800 ,
            'prix'  => 200,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>800 ,
            'prix'  => 206,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>800 ,
            'prix'  => 215,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>800 ,
            'prix'  => 225,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>800 ,
            'prix'  => 234,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>800 ,
            'prix'  => 244,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>800 ,
            'prix'  => 251,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>800 ,
            'prix'  => 265,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>800 ,
            'prix'  => 273,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>800 ,
            'prix'  => 281,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>800 ,
            'prix'  => 297,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>800 ,
            'prix'  => 306,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>800 ,
            'prix'  => 320,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>800 ,
            'prix'  => 32,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>800 ,
            'prix'  => 334,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>800 ,
            'prix'  => 347,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>800 ,
            'prix'  => 358,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>800 ,
            'prix'  => 369,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>800 ,
            'prix'  => 379,
        ],
         /*Larg=900*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>900 ,
            'prix'  => 184,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>900 ,
            'prix'  => 196,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>900 ,
            'prix'  => 204,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>900 ,
            'prix'  => 215,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>900 ,
            'prix'  => 222,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>900 ,
            'prix'  => 234,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>900 ,
            'prix'  => 244,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>900 ,
            'prix'  => 255,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>900 ,
            'prix'  => 265,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>900 ,
            'prix'  => 276,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>900 ,
            'prix'  => 286,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>900 ,
            'prix'  => 294,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>900 ,
            'prix'  => 309,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>900 ,
            'prix'  => 320,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>900 ,
            'prix'  => 334,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>900 ,
            'prix'  => 342,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>900 ,
            'prix'  => 354,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>900 ,
            'prix'  => 362,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>900 ,
            'prix'  => 375,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>900 ,
            'prix'  => 390,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>900 ,
            'prix'  => 399,
        ],

        /*larg=1000*/
    /*    [
            'genre'    =>1 ,
 	 	 	'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1000 ,
            'prix'  => 211,
        ],*/
        [
            'genre'    =>1 ,
 	 	 	'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1000 ,
            'prix'  => 204,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1000 ,
            'prix'  => 210,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1000 ,
            'prix'  => 225,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1000 ,
            'prix'  => 234,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1000 ,
            'prix'  => 248,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1000 ,
            'prix'  => 255,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1000 ,
            'prix'  => 268,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1000 ,
            'prix'  => 279,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1000 ,
            'prix'  => 290,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1000 ,
            'prix'  =>301 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1000 ,
            'prix'  => 312,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1000 ,
            'prix'  => 327,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1000 ,
            'prix'  => 334,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1000 ,
            'prix'  => 349,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1000 ,
            'prix'  => 362,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1000 ,
            'prix'  => 369,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1000 ,
            'prix'  => 379,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1000 ,
            'prix'  => 395,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1000 ,
            'prix'  => 406,
        ],/*
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1000 ,
            'prix'  => 531,
        ],*/
        /*larg=1100*//*
        [
            'genre'    =>1 ,
 	 	 	'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1100 ,
            'prix'  => 220,
        ],*/
        [
            'genre'    =>1 ,
 	 	 	'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1100 ,
            'prix'  => 210,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1100 ,
            'prix'  => 222,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1100 ,
            'prix'  => 234,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1100 ,
            'prix'  => 244,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1100 ,
            'prix'  => 257,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1100 ,
            'prix'  => 268,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1100 ,
            'prix'  => 279,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1100 ,
            'prix'  => 290,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1100 ,
            'prix'  => 301,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1100 ,
            'prix'  =>312 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1100 ,
            'prix'  => 324,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1100 ,
            'prix'  => 340,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1100 ,
            'prix'  => 349,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1100 ,
            'prix'  => 369,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1100 ,
            'prix'  => 375,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1100 ,
            'prix'  => 390,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1100 ,
            'prix'  => 399,
        ],/*
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1100 ,
            'prix'  => 527,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1100 ,
            'prix'  => 545,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1100 ,
            'prix'  => 546,
        ],*/
        /*larg=1200*/
    /*    [
            'genre'    =>1 ,
 	 	 	'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1200 ,
            'prix'  => 227,
        ],
        [
            'genre'    =>1 ,
 	 	 	'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1200 ,
            'prix'  => 236,
        ],*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1200 ,
            'prix'  => 234,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1200 ,
            'prix'  => 244,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1200 ,
            'prix'  => 255,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1200 ,
            'prix'  => 273,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1200 ,
            'prix'  => 281,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1200 ,
            'prix'  => 294,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1200 ,
            'prix'  => 306,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1200 ,
            'prix'  => 316,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1200 ,
            'prix'  =>327 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1200 ,
            'prix'  => 340,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1200 ,
            'prix'  => 358,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1200 ,
            'prix'  => 369,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1200 ,
            'prix'  => 386,
        ],/*
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1200 ,
            'prix'  => 438,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1200 ,
            'prix'  => 500,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1200 ,
            'prix'  => 537,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1200 ,
            'prix'  => 541,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1200 ,
            'prix'  => 553,
        ],*/
        /*larg=1300*/
    /*    [
            'genre'    =>1 ,
 	 	 	'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1300 ,
            'prix'  => 243,
        ],
        [
            'genre'    =>1 ,
 	 	 	'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1300 ,
            'prix'  => 257,
        ],*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1300 ,
            'prix'  => 243,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1300 ,
            'prix'  => 257,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1300 ,
            'prix'  => 268,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1300 ,
            'prix'  => 279,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1300 ,
            'prix'  => 294,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1300 ,
            'prix'  => 306,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1300 ,
            'prix'  => 316,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1300 ,
            'prix'  => 327,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1300 ,
            'prix'  =>342 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1300 ,
            'prix'  => 354,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1300 ,
            'prix'  => 369,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1300 ,
            'prix'  => 389,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1300 ,
            'prix'  => 437,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1300 ,
            'prix'  => 446,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1300 ,
            'prix'  => 515,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1300 ,
            'prix'  => 545,
        ],
        /*larg=1400*/
    /*    [
            'genre'    =>1 ,
 	 	 	'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1400 ,
            'prix'  => 240,
        ],
        [
            'genre'    =>1 ,
 	 	 	'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1400 ,
            'prix'  => 252,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1400 ,
            'prix'  => 263,
        ],*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1400 ,
            'prix'  => 282,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1400 ,
            'prix'  => 301,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1400 ,
            'prix'  => 290,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1400 ,
            'prix'  => 301,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1400 ,
            'prix'  => 316,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1400 ,
            'prix'  => 327,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1400 ,
            'prix'  => 342,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1400 ,
            'prix'  =>354 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1400 ,
            'prix'  => 365,
        ],/*
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1400 ,
            'prix'  => 389,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1400 ,
            'prix'  => 423,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1400 ,
            'prix'  => 452,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1400 ,
            'prix'  => 454,
        ],*/
        /*larg=1500*/
    /*    [
            'genre'    =>1 ,
 	 	 	'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1500 ,
            'prix'  => 247,
        ],
        [
            'genre'    =>1 ,
 	 	 	'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1500 ,
            'prix'  => 261,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1500 ,
            'prix'  => 275,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1500 ,
            'prix'  => 292,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1500 ,
            'prix'  => 305,
        ],*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1500 ,
            'prix'  => 312,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1500 ,
            'prix'  => 327,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1500 ,
            'prix'  => 342,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1500 ,
            'prix'  => 354,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1500 ,
            'prix'  => 369,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1500 ,
            'prix'  =>379 ,
        ],/*
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1500 ,
            'prix'  => 419,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1500 ,
            'prix'  => 430,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>2 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1500 ,
            'prix'  => 438,
        ],
*/



            ];

            Modele::insert($modeles);

        }


    }
}
