<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Modele;
use App\Models\Seeders;

class Modeles4Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $seeder = Modele::where('type',4)->count();//3V

        //Check if the seeder exist in the DB
        if ($seeder==0) {
            $modeles =
            [
            /*larg= 1400*/
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 500,
                    'largeur'  =>1400 ,
                    'prix'  => 494,
				],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    => 1,
                    'hauteur'    =>600 ,
                    'largeur'  =>1400 ,
                    'prix'  => 508,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    => 1,
                    'hauteur'    => 700,
                    'largeur'  =>1400 ,
                    'prix'  => 522,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    => 1,
                    'hauteur'    => 800,
                    'largeur'  =>1400 ,
                    'prix'  => 545,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    => 1,
                    'hauteur'    => 900,
                    'largeur'  =>1400 ,
                    'prix'  => 559,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1000,
                    'largeur'  =>1400 ,
                    'prix'  => 579,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    =>1100 ,
                    'largeur'  =>1400 ,
                    'prix'  => 594,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1200,
                    'largeur'  =>1400 ,
                    'prix'  => 613,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1300,
                    'largeur'  =>1400 ,
                    'prix'  => 628,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1400,
                    'largeur'  =>1400 ,
                    'prix'  => 646,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1500,
                    'largeur'  =>1400 ,
                    'prix'  => 664 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1600,
                    'largeur'  =>1400 ,
                    'prix'  => 681 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1700,
                    'largeur'  =>1400 ,
                    'prix'  => 712 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1800,
                    'largeur'  =>1400 ,
                    'prix'  => 734,
                ],
                [
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1900,
                    'largeur'  =>1400 ,
                    'prix'  => 768 ,
                ],
                [
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2000,
                    'largeur'  =>1400 ,
                    'prix'  => 778,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2100,
                    'largeur'  =>1400 ,
                    'prix'  => 854,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2200,
                    'largeur'  =>1400 ,
                    'prix'  => 875,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2300,
                    'largeur'  =>1400 ,
                    'prix'  => 909,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2400,
                    'largeur'  =>1400 ,
                    'prix'  => 934,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>4 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2500,
                    'largeur'  =>1400 ,
                    'prix'  =>968 ,
                ],

            /*Larg= 1500*/
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    =>1 ,
                'hauteur'    => 500,
                'largeur'  =>1500 ,
                'prix'  => 497,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    => 1,
                'hauteur'    =>600 ,
                'largeur'  =>1500 ,
                'prix'  => 511,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    => 1,
                'hauteur'    => 700,
                'largeur'  =>1500 ,
                'prix'  => 531,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    => 1,
                'hauteur'    => 800,
                'largeur'  =>1500 ,
                'prix'  => 549,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    => 1,
                'hauteur'    => 900,
                'largeur'  =>1500 ,
                'prix'  => 566,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    =>1 ,
                'hauteur'    => 1000,
                'largeur'  =>1500 ,
                'prix'  => 588,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    =>1 ,
                'hauteur'    =>1100 ,
                'largeur'  =>1500 ,
                'prix'  => 602,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    =>1 ,
                'hauteur'    => 1200,
                'largeur'  =>1500 ,
                'prix'  => 619,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    =>1 ,
                'hauteur'    => 1300,
                'largeur'  =>1500 ,
                'prix'  => 635,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    =>1 ,
                'hauteur'    => 1400,
                'largeur'  =>1500 ,
                'prix'  => 653,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    =>1 ,
                'hauteur'    => 1500,
                'largeur'  =>1500 ,
                'prix'  => 674,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    =>1 ,
                'hauteur'    => 1600,
                'largeur'  =>1500 ,
                'prix'  =>692 ,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    =>1 ,
                'hauteur'    => 1700,
                'largeur'  =>1500 ,
                'prix'  => 726,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    =>1 ,
                'hauteur'    => 1800,
                'largeur'  =>1500 ,
                'prix'  => 748,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    =>1 ,
                'hauteur'    => 1900,
                'largeur'  =>1500 ,
                'prix'  => 785,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    =>1 ,
                'hauteur'    => 2000,
                'largeur'  =>1500 ,
                'prix'  => 794,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    =>1 ,
                'hauteur'    => 2100,
                'largeur'  =>1500 ,
                'prix'  => 869,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    =>1 ,
                'hauteur'    => 2200,
                'largeur'  =>1500 ,
                'prix'  => 894,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    =>1 ,
                'hauteur'    => 2300,
                'largeur'  =>1500 ,
                'prix'  => 928,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    =>1 ,
                'hauteur'    => 2400,
                'largeur'  =>1500 ,
                'prix'  => 946,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>4 ,
                'couleur'    =>1 ,
                'hauteur'    => 2500,
                'largeur'  =>1500 ,
                'prix'  => 982,
            ],
        /*Larg=1600*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>1600 ,
            'prix'  => 509,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1600 ,
            'prix'  => 524,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1600 ,
            'prix'  => 538,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1600 ,
            'prix'  => 560,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1600 ,
            'prix'  => 574,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1600 ,
            'prix'  => 595,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1600 ,
            'prix'  => 610,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1600 ,
            'prix'  => 629,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1600 ,
            'prix'  => 647,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1600 ,
            'prix'  => 668,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1600 ,
            'prix'  => 686,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1600 ,
            'prix'  => 707,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1600 ,
            'prix'  => 745,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1600 ,
            'prix'  => 767,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1600 ,
            'prix'  => 800,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1600 ,
            'prix'  => 814,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1600 ,
            'prix'  => 891,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1600 ,
            'prix'  => 910,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1600 ,
            'prix'  => 947,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1600 ,
            'prix'  => 973,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1600 ,
            'prix'  => 1004,
        ],

        /*larg=1700*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>1700 ,
            'prix'  => 513,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1700 ,
            'prix'  => 533,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1700 ,
            'prix'  => 547,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1700 ,
            'prix'  => 567,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1700 ,
            'prix'  => 582,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1700 ,
            'prix'  => 604,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1700 ,
            'prix'  => 618,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1700 ,
            'prix'  => 636,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1700 ,
            'prix'  => 657,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1700 ,
            'prix'  => 677,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1700 ,
            'prix'  => 699,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1700 ,
            'prix'  => 722,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1700 ,
            'prix'  => 759,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1700 ,
            'prix'  => 779,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1700 ,
            'prix'  => 815,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1700 ,
            'prix'  => 829,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1700 ,
            'prix'  => 905,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1700 ,
            'prix'  => 930,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1700 ,
            'prix'  => 965,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1700 ,
            'prix'  => 989,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1700 ,
            'prix'  => 1021,
        ],

        /*Larg=1800*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>1800 ,
            'prix'  => 522,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1800 ,
            'prix'  => 536,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1800 ,
            'prix'  => 552,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1800 ,
            'prix'  => 572,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1800 ,
            'prix'  => 588,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1800 ,
            'prix'  => 608,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1800 ,
            'prix'  => 622,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1800 ,
            'prix'  => 649,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1800 ,
            'prix'  => 669,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1800 ,
            'prix'  => 693,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1800 ,
            'prix'  => 712,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1800 ,
            'prix'  => 731,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1800 ,
            'prix'  => 771,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1800 ,
            'prix'  => 794,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1800 ,
            'prix'  => 829,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1800 ,
            'prix'  => 845,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1800 ,
            'prix'  => 921,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1800 ,
            'prix'  => 943,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1800 ,
            'prix'  => 981,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1800 ,
            'prix'  => 1006,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1800 ,
            'prix'  => 1040,
        ],
        /*larg=1900*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1900 ,
            'prix'  => 530,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1900 ,
            'prix'  => 543,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1900 ,
            'prix'  => 559,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1900 ,
            'prix'  => 580,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1900 ,
            'prix'  => 594,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1900 ,
            'prix'  => 617,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1900 ,
            'prix'  => 634,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1900 ,
            'prix'  => 658,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1900 ,
            'prix'  => 680,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1900 ,
            'prix'  => 704,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1900 ,
            'prix'  =>727 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1900 ,
            'prix'  => 748,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1900 ,
            'prix'  => 786,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1900 ,
            'prix'  => 810,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1900 ,
            'prix'  => 845,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1900 ,
            'prix'  => 859,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1900 ,
            'prix'  => 937,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1900 ,
            'prix'  => 963,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1900 ,
            'prix'  => 1000,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1900 ,
            'prix'  => 1022,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1900 ,
            'prix'  => 1056,
        ],
        /*larg=2000*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>2000 ,
            'prix'  => 536,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>2000 ,
            'prix'  => 553,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2000 ,
            'prix'  => 568,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2000 ,
            'prix'  => 584,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2000 ,
            'prix'  => 603,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2000 ,
            'prix'  => 623,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2000 ,
            'prix'  => 645,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2000 ,
            'prix'  => 670,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2000 ,
            'prix'  => 691,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2000 ,
            'prix'  => 716,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2000 ,
            'prix'  => 739,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2000 ,
            'prix'  => 761,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2000 ,
            'prix'  => 799,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2000 ,
            'prix'  => 821,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2000 ,
            'prix'  => 858,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2000 ,
            'prix'  => 875,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>2000 ,
            'prix'  => 953,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2000 ,
            'prix'  => 977,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>2000 ,
            'prix'  => 1014,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>2000 ,
            'prix'  => 1042,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>2000 ,
            'prix'  => 1077,
        ],
        /*larg=2100*///here
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>2100 ,
            'prix'  => 568,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2100 ,
            'prix'  => 585,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2100 ,
            'prix'  => 603,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2100 ,
            'prix'  => 621,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2100 ,
            'prix'  => 645,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2100 ,
            'prix'  => 668,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2100 ,
            'prix'  => 691,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2100 ,
            'prix'  => 716,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2100 ,
            'prix'  => 741,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2100 ,
            'prix'  =>762 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2100 ,
            'prix'  => 788,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2100 ,
            'prix'  => 826,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2100 ,
            'prix'  => 847,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2100 ,
            'prix'  => 883,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2100 ,
            'prix'  => 898,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>2100 ,
            'prix'  => 977,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2100 ,
            'prix'  => 1002,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>2100 ,
            'prix'  => 1044,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>2100 ,
            'prix'  => 107,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>2100 ,
            'prix'  => 755,
        ],

        /*larg=2200*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>2200 ,
            'prix'  => 575,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2200 ,
            'prix'  => 591,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2200 ,
            'prix'  => 611,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2200 ,
            'prix'  => 624,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2200 ,
            'prix'  => 658,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2200 ,
            'prix'  => 679,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2200 ,
            'prix'  => 705,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2200 ,
            'prix'  => 729,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2200 ,
            'prix'  => 752,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2200 ,
            'prix'  =>776 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2200 ,
            'prix'  => 801,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2200 ,
            'prix'  => 840,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2200 ,
            'prix'  => 860,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2200 ,
            'prix'  => 899,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2200 ,
            'prix'  => 916,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>2200 ,
            'prix'  => 996,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2200 ,
            'prix'  => 1019,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>2200 ,
            'prix'  => 1060,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>2200 ,
            'prix'  => 1088,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>2200 ,
            'prix'  => 1121,
        ],

        /*larg=2300*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>2300 ,
            'prix'  => 583,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2300 ,
            'prix'  => 597,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2300 ,
            'prix'  => 616,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2300 ,
            'prix'  => 637,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2300 ,
            'prix'  => 664,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2300 ,
            'prix'  => 690,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2300 ,
            'prix'  => 715,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2300 ,
            'prix'  => 740,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2300 ,
            'prix'  => 767,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2300 ,
            'prix'  =>792 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2300 ,
            'prix'  => 813,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2300 ,
            'prix'  => 852,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2300 ,
            'prix'  => 876,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2300 ,
            'prix'  => 914,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2300 ,
            'prix'  => 932,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>2300 ,
            'prix'  => 1011,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2300 ,
            'prix'  => 1039,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>2300 ,
            'prix'  => 1077,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>2300 ,
            'prix'  => 1103,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>2300 ,
            'prix'  => 1137,
        ],

        /*larg=2400*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>2400 ,
            'prix'  => 587,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2400 ,
            'prix'  => 602,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2400 ,
            'prix'  => 624,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2400 ,
            'prix'  => 644,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2400 ,
            'prix'  => 676,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2400 ,
            'prix'  => 700,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2400 ,
            'prix'  => 726,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2400 ,
            'prix'  => 751,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2400 ,
            'prix'  => 778,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2400 ,
            'prix'  =>802 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2400 ,
            'prix'  => 829,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2400 ,
            'prix'  => 865,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2400 ,
            'prix'  => 889,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2400 ,
            'prix'  => 930,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2400 ,
            'prix'  => 947,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>2400 ,
            'prix'  => 1025,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2400 ,
            'prix'  => 1025,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>2400 ,
            'prix'  => 1052,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>2400 ,
            'prix'  => 1092,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>2400 ,
            'prix'  => 1120,
        ],

        /*larg=2500*/

        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>2500 ,
            'prix'  => 596,//
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2500 ,
            'prix'  => 610,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2500 ,
            'prix'  => 634,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2500 ,
            'prix'  => 656,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2500 ,
            'prix'  => 688,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2500 ,
            'prix'  => 713,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2500 ,
            'prix'  => 741,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2500 ,
            'prix'  => 765,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2500 ,
            'prix'  => 794,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2500 ,
            'prix'  => 817,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2500 ,
            'prix'  => 843,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2500 ,
            'prix'  => 882,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2500 ,
            'prix'  => 905,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2500 ,
            'prix'  =>944 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2500 ,
            'prix'  =>963 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>2500 ,
            'prix'  => 1044,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2500 ,
            'prix'  => 1072,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>2500 ,
            'prix'  => 1110,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>2500 ,
            'prix'  => 1138,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>2500 ,
            'prix'  => 1173,
        ],
        /*larg=2600*/// here

        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2600 ,
            'prix'  => 619,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2600 ,
            'prix'  => 640,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 900,
            'largeur'  =>2600 ,
            'prix'  => 667,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1000 ,
            'largeur'  =>2600 ,
            'prix'  => 699,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2600 ,
            'prix'  => 724,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2600 ,
            'prix'  => 752,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2600 ,
            'prix'  => 777,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2600 ,
            'prix'  => 803,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2600 ,
            'prix'  => 830,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2600 ,
            'prix'  => 855,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2600 ,
            'prix'  => 893,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2600 ,
            'prix'  => 919,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2600 ,
            'prix'  => 958,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2600 ,
            'prix'  => 980,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>2600 ,
            'prix'  => 1058,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2600 ,
            'prix'  => 1086,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2600 ,
            'prix'  => 1127,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2600 ,
            'prix'  => 1156,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2600 ,
            'prix'  => 1191,
        ],
        /*larg=2700*/

        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2700 ,
            'prix'  => 629,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2700 ,
            'prix'  => 655,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2700 ,
            'prix'  => 683,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2700 ,
            'prix'  => 715,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2700 ,
            'prix'  => 737,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2700 ,
            'prix'  => 766,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2700 ,
            'prix'  => 792,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2700 ,
            'prix'  => 819,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2700 ,
            'prix'  =>847 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2700 ,
            'prix'  => 873,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2700 ,
            'prix'  => 914,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2700 ,
            'prix'  => 937,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2700 ,
            'prix'  => 976,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2700 ,
            'prix'  => 996,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>2700 ,
            'prix'  => 1079,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2700 ,
            'prix'  => 1106,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>2700 ,
            'prix'  => 1148,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>2700 ,
            'prix'  => 1179,
        ],
        /*larg=2800*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2800 ,
            'prix'  => 639,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1700 ,
            'prix'  => 665,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2800 ,
            'prix'  => 691,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2800 ,
            'prix'  => 725,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2800 ,
            'prix'  => 749,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2800 ,
            'prix'  => 778,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2800 ,
            'prix'  => 805,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2800 ,
            'prix'  => 834,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2800 ,
            'prix'  =>861 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2800 ,
            'prix'  => 887,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2800 ,
            'prix'  => 927,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2800 ,
            'prix'  => 953,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2800 ,
            'prix'  => 994,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2800 ,
            'prix'  => 1016,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>2800 ,
            'prix'  => 1095,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2800 ,
            'prix'  => 1126,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>2800 ,
            'prix'  => 1168,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>2800 ,
            'prix'  => 1194,
        ],
        /*larg=2900*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2900 ,
            'prix'  => 643,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2900 ,
            'prix'  => 675,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2900 ,
            'prix'  => 701,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2900 ,
            'prix'  => 734,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2900 ,
            'prix'  => 762,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2900 ,
            'prix'  => 788,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2900 ,
            'prix'  => 817,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2900 ,
            'prix'  => 846,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2900 ,
            'prix'  =>874 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2900 ,
            'prix'  => 902,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2900 ,
            'prix'  => 939,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2900 ,
            'prix'  => 966,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2900 ,
            'prix'  => 1009,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2900 ,
            'prix'  => 1030,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>2900 ,
            'prix'  => 1107,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2900 ,
            'prix'  => 1139,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>2900 ,
            'prix'  => 1183,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>2900 ,
            'prix'  => 1213,
        ],
        /*larg=3000*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>3000 ,
            'prix'  => 649,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>3000 ,
            'prix'  => 985,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>3000 ,
            'prix'  => 709,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>3000 ,
            'prix'  => 746,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>3000 ,
            'prix'  => 773,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>3000 ,
            'prix'  => 802,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>3000 ,
            'prix'  => 828,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>3000 ,
            'prix'  => 858,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>3000 ,
            'prix'  =>886 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>3000 ,
            'prix'  => 914,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>3000 ,
            'prix'  => 955,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>3000 ,
            'prix'  => 982,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>3000 ,
            'prix'  => 1019,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>3000 ,
            'prix'  => 1045,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>3000 ,
            'prix'  => 1125,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>3000 ,
            'prix'  => 1154,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>3000 ,
            'prix'  => 1196,
        ],
        /*larg=3100*/

        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>3100 ,
            'prix'  => 681,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>3100 ,
            'prix'  => 694,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>3100 ,
            'prix'  => 722,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>3100 ,
            'prix'  => 756,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>3100 ,
            'prix'  => 783,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>3100 ,
            'prix'  => 815,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>3100 ,
            'prix'  => 839,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>3100 ,
            'prix'  => 871,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>3100 ,
            'prix'  =>897 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>3100 ,
            'prix'  => 927, //  faute noté 827
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>3100 ,
            'prix'  => 967,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>3100 ,
            'prix'  => 997,
        ],
        /*larg=3200*/

        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>3200 ,
            'prix'  => 688,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>3200 ,
            'prix'  => 704,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>3200 ,
            'prix'  => 733,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>3200 ,
            'prix'  => 767,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>3200 ,
            'prix'  => 796,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>3200 ,
            'prix'  => 826,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>3200 ,
            'prix'  => 855,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>3200 ,
            'prix'  => 883,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>3200 ,
            'prix'  =>915 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>3200 ,
            'prix'  => 941,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>3200 ,
            'prix'  => 984,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>3200 ,
            'prix'  => 1012,
        ],
        /*larg=3300*/

        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>3300 ,
            'prix'  => 712,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>3300 ,
            'prix'  => 740,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>3300 ,
            'prix'  => 780,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>3300 ,
            'prix'  =>807 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>3300 ,
            'prix'  => 836 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>3300 ,
            'prix'  => 865 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>3300 ,
            'prix'  => 893 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>3300 ,
            'prix'  =>924 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>3300 ,
            'prix'  => 954,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>3300 ,
            'prix'  => 995,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>3300 ,
            'prix'  => 1025,
        ],

        /*larg=3400*/

        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>3400 ,
            'prix'  => 725,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>3400 ,
            'prix'  => 752,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>3400 ,
            'prix'  => 788,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>3400 ,
            'prix'  => 817,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>3400 ,
            'prix'  => 850,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>3400 ,
            'prix'  => 878,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>3400 ,
            'prix'  => 908,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>3400 ,
            'prix'  =>940 ,
        ],
         /*larg=3500*/

        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>3500 ,
            'prix'  => 754,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>3500 ,
            'prix'  => 767,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>3500 ,
            'prix'  => 802,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>3500 ,
            'prix'  => 832,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>3500 ,
            'prix'  => 864,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>3500 ,
            'prix'  => 892,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>3500 ,
            'prix'  => 924,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>3500 ,
            'prix'  =>955 ,
        ],

        /*larg=3600*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>3600 ,
            'prix'  => 764,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>3600 ,
            'prix'  => 774,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>3600 ,
            'prix'  => 812,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>3600 ,
            'prix'  => 841,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>3600 ,
            'prix'  => 875,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>3600 ,
            'prix'  => 901,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>3600 ,
            'prix'  => 934,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>4 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>3600 ,
            'prix'  =>966 ,
        ],
            ];

            Modele::insert($modeles);

        }


    }
}
