<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Modele;
use App\Models\Seeders;

class Modeles3Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $seeder = Modele::where('type',3)->count();

        //Check if the seeder exist in the DB
        if ($seeder==0) {
            $modeles =
            [
            /*larg= 900*/
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 500,
                    'largeur'  =>900 ,
                    'prix'  => 711,
				],
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    => 1,
                    'hauteur'    =>600 ,
                    'largeur'  =>900 ,
                    'prix'  => 719,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    => 1,
                    'hauteur'    => 700,
                    'largeur'  =>900 ,
                    'prix'  => 751,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    => 1,
                    'hauteur'    => 800,
                    'largeur'  =>900 ,
                    'prix'  => 792,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    => 1,
                    'hauteur'    => 900,
                    'largeur'  =>900 ,
                    'prix'  => 821,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1000,
                    'largeur'  =>900 ,
                    'prix'  => 882,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    =>1100 ,
                    'largeur'  =>900 ,
                    'prix'  => 916,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1200,
                    'largeur'  =>900 ,
                    'prix'  => 996, //faute?
                ],
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1300,
                    'largeur'  =>900 ,
                    'prix'  => 996,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1400,
                    'largeur'  =>900 ,
                    'prix'  => 1042,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1500,
                    'largeur'  =>900 ,
                    'prix'  => 1098 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1600,
                    'largeur'  =>900 ,
                    'prix'  => 1122 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1700,
                    'largeur'  =>900 ,
                    'prix'  => 1200 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1800,
                    'largeur'  =>900 ,
                    'prix'  => 1256,
                ],
                [
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1900,
                    'largeur'  =>900 ,
                    'prix'  => 1284 ,
                ],
                [
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2000,
                    'largeur'  =>900 ,
                    'prix'  => 1333,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2100,
                    'largeur'  =>900 ,
                    'prix'  => 1369,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2200,
                    'largeur'  =>900 ,
                    'prix'  => 1413,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2300,
                    'largeur'  =>900 ,
                    'prix'  => 1460,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2400,
                    'largeur'  =>900 ,
                    'prix'  => 1511,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2500,
                    'largeur'  =>900 ,
                    'prix'  =>1559 ,
                ],

            /*Larg= 1000*/
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 500,
                'largeur'  =>1000 ,
                'prix'  => 719,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    => 1,
                'hauteur'    =>600 ,
                'largeur'  =>1000 ,
                'prix'  => 751,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    => 1,
                'hauteur'    => 700,
                'largeur'  =>1000 ,
                'prix'  => 782,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    => 1,
                'hauteur'    => 800,
                'largeur'  =>1000 ,
                'prix'  => 808,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    => 1,
                'hauteur'    => 900,
                'largeur'  =>1000 ,
                'prix'  => 840,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 1000,
                'largeur'  =>1000 ,
                'prix'  => 899,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    =>1100 ,
                'largeur'  =>1000 ,
                'prix'  => 950,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 1200,
                'largeur'  =>1000 ,
                'prix'  => 996,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 1300,
                'largeur'  =>1000 ,
                'prix'  => 1042,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 1400,
                'largeur'  =>1000 ,
                'prix'  => 1083,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 1500,
                'largeur'  =>1000 ,
                'prix'  => 1144,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 1600,
                'largeur'  =>1000 ,
                'prix'  =>1178 ,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 1700,
                'largeur'  =>1000 ,
                'prix'  => 1239,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 1800,
                'largeur'  =>1000 ,
                'prix'  => 1301,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 1900,
                'largeur'  =>1000 ,
                'prix'  => 1345,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 2000,
                'largeur'  =>1000 ,
                'prix'  => 1386,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 2100,
                'largeur'  =>1000 ,
                'prix'  => 1426,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 2200,
                'largeur'  =>1000 ,
                'prix'  => 1472,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 2300,
                'largeur'  =>1000 ,
                'prix'  => 1511,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 2400,
                'largeur'  =>1000 ,
                'prix'  => 1573,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 2500,
                'largeur'  =>1000 ,
                'prix'  => 1627,
            ],
        /*Larg=1100*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>1100 ,
            'prix'  => 728,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1100 ,
            'prix'  => 767,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1100 ,
            'prix'  => 792,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1100 ,
            'prix'  => 840,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1100 ,
            'prix'  => 864,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1100 ,
            'prix'  => 927,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1100 ,
            'prix'  => 979,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1100 ,
            'prix'  => 1042,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1100 ,
            'prix'  => 1083,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1100 ,
            'prix'  => 1122,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1100 ,
            'prix'  => 1178,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1100 ,
            'prix'  => 1227,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1100 ,
            'prix'  => 1284,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1100 ,
            'prix'  => 1355,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1100 ,
            'prix'  => 1386,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1100 ,
            'prix'  => 1426,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1100 ,
            'prix'  => 1486,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1100 ,
            'prix'  => 1525,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1100 ,
            'prix'  => 1573,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1100 ,
            'prix'  => 1641,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1100 ,
            'prix'  => 1703,
        ],

        /*larg=1200*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>1200 ,
            'prix'  => 767,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1200 ,
            'prix'  => 782,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1200 ,
            'prix'  => 808,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1200 ,
            'prix'  => 852,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1200 ,
            'prix'  => 899,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1200 ,
            'prix'  => 979,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1200 ,
            'prix'  => 1025,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1200 ,
            'prix'  => 1068,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1200 ,
            'prix'  => 1122,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1200 ,
            'prix'  => 1165,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1200 ,
            'prix'  => 1227,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1200 ,
            'prix'  => 1270,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1200 ,
            'prix'  => 1345,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1200 ,
            'prix'  => 1394,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1200 ,
            'prix'  => 1440,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1200 ,
            'prix'  => 1486,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1200 ,
            'prix'  => 1544,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1200 ,
            'prix'  => 1584,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1200 ,
            'prix'  => 1627,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1200 ,
            'prix'  => 1715,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1200 ,
            'prix'  => 1754,
        ],

        /*Larg=1300*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>1300 ,
            'prix'  => 782,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1300 ,
            'prix'  => 792,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1300 ,
            'prix'  => 840,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1300 ,
            'prix'  => 882,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1300 ,
            'prix'  => 927,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1300 ,
            'prix'  => 1012,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1300 ,
            'prix'  => 1051,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1300 ,
            'prix'  => 1108,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1300 ,
            'prix'  => 1151,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1300 ,
            'prix'  => 1214,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1300 ,
            'prix'  => 1270,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1300 ,
            'prix'  => 1319,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1300 ,
            'prix'  => 1386,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1300 ,
            'prix'  => 1460,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1300 ,
            'prix'  => 1493,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1300 ,
            'prix'  => 1544,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1300 ,
            'prix'  => 1596,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1300 ,
            'prix'  => 1641,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1300 ,
            'prix'  => 1703,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1300 ,
            'prix'  => 1785,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1300 ,
            'prix'  => 1831,
        ],
        /*larg=1400*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1400 ,
            'prix'  => 792,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1400 ,
            'prix'  => 821,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1400 ,
            'prix'  => 852,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1400 ,
            'prix'  => 916,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1400 ,
            'prix'  => 966,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1400 ,
            'prix'  => 1042,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1400 ,
            'prix'  => 1098,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1400 ,
            'prix'  => 1151,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1400 ,
            'prix'  => 1200,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1400 ,
            'prix'  => 1256,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1400 ,
            'prix'  =>1319 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1400 ,
            'prix'  => 1369,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1400 ,
            'prix'  => 1426,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1400 ,
            'prix'  => 1493,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1400 ,
            'prix'  => 1544,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1400 ,
            'prix'  => 1596,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1400 ,
            'prix'  => 1651,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1400 ,
            'prix'  => 1715,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1400 ,
            'prix'  => 1777,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1400 ,
            'prix'  => 1843,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1400 ,
            'prix'  => 1901,
        ],

            ];

            Modele::insert($modeles);

        }


    }
}
