<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Modele;
use App\Models\Seeders;

class ModelesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $seeder = Modele::where('type',1)->count();

        //Check if the seeder exist in the DB
        if ($seeder==0) {
            $modeles =
            [
            /*larg= 500*/
				[
                    'genre'    =>1 ,
					'type'    =>1 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 500,
                    'largeur'  =>500 ,
                    'prix'  =>167 ,
				],
				[
                    'genre'    =>1 ,
					'type'    =>1 ,
                    'couleur'    => 1,
                    'hauteur'    =>600 ,
                    'largeur'  =>500 ,
                    'prix'  => 175,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>1 ,
                    'couleur'    => 1,
                    'hauteur'    => 700,
                    'largeur'  =>500 ,
                    'prix'  => 179,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>1 ,
                    'couleur'    => 1,
                    'hauteur'    => 800,
                    'largeur'  =>500 ,
                    'prix'  =>187 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>1 ,
                    'couleur'    => 1,
                    'hauteur'    => 900,
                    'largeur'  =>500 ,
                    'prix'  => 192,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>1 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1000,
                    'largeur'  =>500 ,
                    'prix'  => 202,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>1 ,
                    'couleur'    =>1 ,
                    'hauteur'    =>1100 ,
                    'largeur'  =>500 ,
                    'prix'  =>208 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>1 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1200,
                    'largeur'  =>500 ,
                    'prix'  => 216,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>1 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1300,
                    'largeur'  =>500 ,
                    'prix'  => 222,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>1 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1400,
                    'largeur'  =>500 ,
                    'prix'  => 230,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>1 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1500,
                    'largeur'  =>500 ,
                    'prix'  => 239,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>1 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1600,
                    'largeur'  =>500 ,
                    'prix'  => 246,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>1 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1700,
                    'largeur'  =>500 ,
                    'prix'  => 276,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>1 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1800,
                    'largeur'  =>500 ,
                    'prix'  =>286 ,
                ],

            /*Larg= 600*/
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>1 ,
                'couleur'    =>1 ,
                'hauteur'    => 500,
                'largeur'  =>600 ,
                'prix'  => 175,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>1 ,
                'couleur'    => 1,
                'hauteur'    =>600 ,
                'largeur'  =>600 ,
                'prix'  => 179,
            ],
            [
                'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
                'couleur'    => 1,
                'hauteur'    => 700,
                'largeur'  =>600 ,
                'prix'  => 187,
            ],
            [
                'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
                'couleur'    => 1,
                'hauteur'    => 800,
                'largeur'  =>600 ,
                'prix'  => 192,
            ],
            [
                'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
                'couleur'    => 1,
                'hauteur'    => 900,
                'largeur'  =>600 ,
                'prix'  => 201,
            ],
            [
                'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
                'couleur'    =>1 ,
                'hauteur'    => 1000,
                'largeur'  =>600 ,
                'prix'  => 208,
            ],
            [
                'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
                'couleur'    =>1 ,
                'hauteur'    =>1100 ,
                'largeur'  =>600 ,
                'prix'  => 212,
            ],
            [
                'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
                'couleur'    =>1 ,
                'hauteur'    => 1200,
                'largeur'  =>600 ,
                'prix'  => 222,
            ],
            [
                'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
                'couleur'    =>1 ,
                'hauteur'    => 1300,
                'largeur'  =>600 ,
                'prix'  => 233,
            ],
            [
                'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
                'couleur'    =>1 ,
                'hauteur'    => 1400,
                'largeur'  =>600 ,
                'prix'  => 242,
            ],
            [
                'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
                'couleur'    =>1 ,
                'hauteur'    => 1500,
                'largeur'  =>600 ,
                'prix'  => 251,
            ],
            [
                'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
                'couleur'    =>1 ,
                'hauteur'    => 1600,
                'largeur'  =>600 ,
                'prix'  =>259 ,
            ],
            [
                'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
                'couleur'    =>1 ,
                'hauteur'    => 1700,
                'largeur'  =>600 ,
                'prix'  => 290,
            ],
            [
                'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
                'couleur'    =>1 ,
                'hauteur'    => 1800,
                'largeur'  =>600 ,
                'prix'  => 301,
            ],
         /*Larg=700*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>700 ,
            'prix'  => 179,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>700 ,
            'prix'  => 187,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>700 ,
            'prix'  => 192,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>700 ,
            'prix'  => 201,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>700 ,
            'prix'  => 208,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>700 ,
            'prix'  => 212,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>700 ,
            'prix'  => 222,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>700 ,
            'prix'  => 233,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>700 ,
            'prix'  => 245,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>700 ,
            'prix'  => 251,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>700 ,
            'prix'  => 265,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>700 ,
            'prix'  => 293,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>700 ,
            'prix'  => 303,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>700 ,
            'prix'  => 314,
        ],
        /*larg=800*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>800 ,
            'prix'  => 187,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>800 ,
            'prix'  => 192,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>800 ,
            'prix'  => 201,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>800 ,
            'prix'  => 219,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>800 ,
            'prix'  => 227,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>800 ,
            'prix'  => 239,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>800 ,
            'prix'  => 245,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>800 ,
            'prix'  => 257,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>800 ,
            'prix'  => 267,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>800 ,
            'prix'  => 278,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>800 ,
            'prix'  => 288,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>800 ,
            'prix'  => 321,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>800 ,
            'prix'  => 332,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>800 ,
            'prix'  => 340,
        ],
         /*Larg=900*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>900 ,
            'prix'  => 192,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>900 ,
            'prix'  => 201,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>900 ,
            'prix'  => 208,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>900 ,
            'prix'  => 227,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>900 ,
            'prix'  => 239,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>900 ,
            'prix'  => 245,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>900 ,
            'prix'  => 257,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>900 ,
            'prix'  => 270,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>900 ,
            'prix'  => 280,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>900 ,
            'prix'  => 287,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>900 ,
            'prix'  => 301,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>900 ,
            'prix'  => 332,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>900 ,
            'prix'  => 343,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>900 ,
            'prix'  => 354,
        ],
        /*larg=1000*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>1000 ,
            'prix'  => 202,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1000 ,
            'prix'  => 208,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1000 ,
            'prix'  => 212,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1000 ,
            'prix'  => 239,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1000 ,
            'prix'  => 245,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1000 ,
            'prix'  => 256,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1000 ,
            'prix'  => 270,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1000 ,
            'prix'  => 300,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1000 ,
            'prix'  => 311,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1000 ,
            'prix'  => 325,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1000 ,
            'prix'  =>334 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1000 ,
            'prix'  => 347,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1000 ,
            'prix'  => 360,
        ],
        /*larg=1100*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>1100 ,
            'prix'  => 208,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1100 ,
            'prix'  => 212,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1100 ,
            'prix'  => 222,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1100 ,
            'prix'  => 245,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1100 ,
            'prix'  => 257,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1100 ,
            'prix'  => 270,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1100 ,
            'prix'  => 299,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1100 ,
            'prix'  => 311,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1100 ,
            'prix'  => 326,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1100 ,
            'prix'  => 334,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1100 ,
            'prix'  =>347 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1100 ,
            'prix'  => 360,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1100 ,
            'prix'  => 374,
        ],
        /*larg=1200*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>1200 ,
            'prix'  => 216,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1200 ,
            'prix'  => 222,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1200 ,
            'prix'  => 233,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1200 ,
            'prix'  => 257,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1200 ,
            'prix'  => 270,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1200 ,
            'prix'  => 300,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1200 ,
            'prix'  => 311,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1200 ,
            'prix'  => 324,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1200 ,
            'prix'  => 334,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1200 ,
            'prix'  => 347,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1200 ,
            'prix'  =>362 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1200 ,
            'prix'  => 374,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1200 ,
            'prix'  => 374,
        ],
        /*larg=1300*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>1300 ,
            'prix'  => 222,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1300 ,
            'prix'  => 233,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1300 ,
            'prix'  => 245,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1300 ,
            'prix'  => 267,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1300 ,
            'prix'  => 280,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1300 ,
            'prix'  => 311,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1300 ,
            'prix'  => 326,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1300 ,
            'prix'  => 334,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1300 ,
            'prix'  => 347,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1300 ,
            'prix'  => 360,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1300 ,
            'prix'  =>374 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1300 ,
            'prix'  => 383,
        ],
        /*larg=1400*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>1400 ,
            'prix'  => 230,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1400 ,
            'prix'  => 242,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1400 ,
            'prix'  => 251,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1400 ,
            'prix'  => 278,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1400 ,
            'prix'  => 287,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1400 ,
            'prix'  => 325,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1400 ,
            'prix'  => 334,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1400 ,
            'prix'  => 347,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1400 ,
            'prix'  => 360,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1400 ,
            'prix'  => 374,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1400 ,
            'prix'  =>388 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1400 ,
            'prix'  => 399,
        ],
        /*larg=1500*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>1500 ,
            'prix'  => 239,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1500 ,
            'prix'  => 251,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1500 ,
            'prix'  => 265,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1500 ,
            'prix'  => 288,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1500 ,
            'prix'  => 301,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1500 ,
            'prix'  => 334,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1500 ,
            'prix'  => 347,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1500 ,
            'prix'  => 362,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1500 ,
            'prix'  => 374,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1500 ,
            'prix'  => 388,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1500 ,
            'prix'  =>407 ,
        ],
        /*larg=1600*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>1600 ,
            'prix'  => 246,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1600 ,
            'prix'  => 259,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1600 ,
            'prix'  => 293,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1600 ,
            'prix'  => 321,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1600 ,
            'prix'  => 332,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1600 ,
            'prix'  => 347,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1600 ,
            'prix'  => 360,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1600 ,
            'prix'  => 374,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1600 ,
            'prix'  => 383,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1600 ,
            'prix'  => 399,
        ],
        /*larg=1600*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>1600 ,
            'prix'  => 246,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1600 ,
            'prix'  => 259,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1600 ,
            'prix'  => 293,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1600 ,
            'prix'  => 321,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1600 ,
            'prix'  => 332,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1600 ,
            'prix'  => 347,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1600 ,
            'prix'  => 360,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1600 ,
            'prix'  => 374,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1600 ,
            'prix'  => 383,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1600 ,
            'prix'  => 399,
        ],
        /*larg=1700*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>1700 ,
            'prix'  => 276,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1700 ,
            'prix'  => 290,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1700 ,
            'prix'  => 303,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1700 ,
            'prix'  => 332,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1700 ,
            'prix'  => 343,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1700 ,
            'prix'  => 360,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1700 ,
            'prix'  => 374,
        ],
        /*larg=1800*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>1800 ,
            'prix'  => 286,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1800 ,
            'prix'  => 301,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1800 ,
            'prix'  => 314,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1800 ,
            'prix'  => 340,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1800 ,
            'prix'  => 354,
        ],

        /*larg=1900*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1900 ,
            'prix'  => 309,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1900 ,
            'prix'  => 324,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1900 ,
            'prix'  => 351,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1900 ,
            'prix'  => 367,
        ],
        /*larg=2000*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>2000 ,
            'prix'  => 312,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2000 ,
            'prix'  => 329,
        ],
        /*larg=2100*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>2100 ,
            'prix'  => 323,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2100 ,
            'prix'  => 336,
        ],
        /*larg=2200*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>2200 ,
            'prix'  => 330,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2200 ,
            'prix'  => 348,
        ],
        /*larg=2300*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>2300 ,
            'prix'  => 338,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>1 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2300 ,
            'prix'  => 355,
        ],
    ];

            Modele::insert($modeles);

        }


    }
}
