<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Modele;
use App\Models\Seeders;

class Modeles3F2V_ALU extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $seeder = Modele::where('type',3)->where('genre',2)->count();

        //Check if the seeder exist in the DB
        // fenetre 2V  ALU
        if ($seeder==0) {
            $modeles =
            [
            /*larg= 668*/
            [
                'genre'    =>2 ,
                'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 404,
                'largeur'  =>668 ,
                'prix'  => 502,
            ],
            [
                'genre'    =>2 ,
                'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 500,
                'largeur'  =>668 ,
                'prix'  => 524,
            ],
            [
                'genre'    =>2 ,
                'type'    =>3 ,
                'couleur'    => 1,
                'hauteur'    =>600 ,
                'largeur'  =>668 ,
                'prix'  => 546,
            ],
            [
                'genre'    =>2 ,
                'type'    =>3 ,
                'couleur'    => 1,
                'hauteur'    => 700,
                'largeur'  =>668 ,
                'prix'  => 568,
            ],
            [
                'genre'    =>2 ,
                'type'    =>3 ,
                'couleur'    => 1,
                'hauteur'    => 800,
                'largeur'  =>668 ,
                'prix'  => 590,
            ],

            /*larg= 700*/
            [
                'genre'    =>2 ,
                'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 404,
                'largeur'  =>700 ,
                'prix'  => 502,
            ],
            [
                'genre'    =>2 ,
                'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 500,
                'largeur'  =>700 ,
                'prix'  => 524,
            ],
            [
                'genre'    =>2 ,
                'type'    =>3 ,
                'couleur'    => 1,
                'hauteur'    =>600 ,
                'largeur'  =>700 ,
                'prix'  => 546,
            ],
            [
                'genre'    =>2 ,
                'type'    =>3 ,
                'couleur'    => 1,
                'hauteur'    => 700,
                'largeur'  =>700 ,
                'prix'  => 568,
            ],
            [
                'genre'    =>2 ,
                'type'    =>3 ,
                'couleur'    => 1,
                'hauteur'    => 800,
                'largeur'  =>700 ,
                'prix'  => 590,
            ],

            /*larg= 800*/
            [
                'genre'    =>2 ,
                'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 404,
                'largeur'  =>800 ,
                'prix'  => 516,
            ],
            [
                'genre'    =>2 ,
                'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 500,
                'largeur'  =>800 ,
                'prix'  => 538,
            ],
            [
                'genre'    =>2 ,
                'type'    =>3 ,
                'couleur'    => 1,
                'hauteur'    =>600 ,
                'largeur'  =>800 ,
                'prix'  => 560,
            ],
            [
                'genre'    =>2 ,
                'type'    =>3 ,
                'couleur'    => 1,
                'hauteur'    => 700,
                'largeur'  =>800 ,
                'prix'  => 582,
            ],
            [
                'genre'    =>2 ,
                'type'    =>3 ,
                'couleur'    => 1,
                'hauteur'    => 800,
                'largeur'  =>800 ,
                'prix'  => 605,
            ],

            /*larg= 900*/
                [
                    'genre'    =>2 ,
                    'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 404,
                    'largeur'  =>900 ,
                    'prix'  => 529,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 500,
                    'largeur'  =>900 ,
                    'prix'  => 552,
				],
				[
                    'genre'    =>2 ,
					'type'    =>3 ,
                    'couleur'    => 1,
                    'hauteur'    =>600 ,
                    'largeur'  =>900 ,
                    'prix'  => 574,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>3 ,
                    'couleur'    => 1,
                    'hauteur'    => 700,
                    'largeur'  =>900 ,
                    'prix'  => 597,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>3 ,
                    'couleur'    => 1,
                    'hauteur'    => 800,
                    'largeur'  =>900 ,
                    'prix'  => 620,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>3 ,
                    'couleur'    => 1,
                    'hauteur'    => 900,
                    'largeur'  =>900 ,
                    'prix'  => 643,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1000,
                    'largeur'  =>900 ,
                    'prix'  => 666,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    =>1100 ,
                    'largeur'  =>900 ,
                    'prix'  => 688,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1200,
                    'largeur'  =>900 ,
                    'prix'  => 711,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1300,
                    'largeur'  =>900 ,
                    'prix'  => 733,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1400,
                    'largeur'  =>900 ,
                    'prix'  => 756,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1500,
                    'largeur'  =>900 ,
                    'prix'  => 855 ,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1600,
                    'largeur'  =>900 ,
                    'prix'  => 802 ,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1700,
                    'largeur'  =>900 ,
                    'prix'  => 825 ,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1800,
                    'largeur'  =>900 ,
                    'prix'  => 847,
                ],
                [
                    'genre'    =>2 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1900,
                    'largeur'  =>900 ,
                    'prix'  => 870 ,
                ],
                [
                    'genre'    =>2 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2000,
                    'largeur'  =>900 ,
                    'prix'  => 893,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2100,
                    'largeur'  =>900 ,
                    'prix'  => 915,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2200,
                    'largeur'  =>900 ,
                    'prix'  => 938,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2300,
                    'largeur'  =>900 ,
                    'prix'  => 961,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2400,
                    'largeur'  =>900 ,
                    'prix'  => 984,
                ],
				[
                    'genre'    =>2 ,
					'type'    =>3 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 2500,
                    'largeur'  =>900 ,
                    'prix'  =>1006 ,
                ],

            /*Larg= 1000*/
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 404,
                'largeur'  =>1000 ,
                'prix'  => 556,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 500,
                'largeur'  =>1000 ,
                'prix'  => 566,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>3 ,
                'couleur'    => 1,
                'hauteur'    =>600 ,
                'largeur'  =>1000 ,
                'prix'  => 589,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>3 ,
                'couleur'    => 1,
                'hauteur'    => 700,
                'largeur'  =>1000 ,
                'prix'  => 612,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>3 ,
                'couleur'    => 1,
                'hauteur'    => 800,
                'largeur'  =>1000 ,
                'prix'  => 635,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>3 ,
                'couleur'    => 1,
                'hauteur'    => 900,
                'largeur'  =>1000 ,
                'prix'  => 658,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 1000,
                'largeur'  =>1000 ,
                'prix'  => 681,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    =>1100 ,
                'largeur'  =>1000 ,
                'prix'  => 704,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 1200,
                'largeur'  =>1000 ,
                'prix'  => 728,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 1300,
                'largeur'  =>1000 ,
                'prix'  => 751,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 1400,
                'largeur'  =>1000 ,
                'prix'  => 774,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 1500,
                'largeur'  =>1000 ,
                'prix'  => 797,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 1600,
                'largeur'  =>1000 ,
                'prix'  =>821 ,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 1700,
                'largeur'  =>1000 ,
                'prix'  => 844,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 1800,
                'largeur'  =>1000 ,
                'prix'  => 867,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 1900,
                'largeur'  =>1000 ,
                'prix'  => 890,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 2000,
                'largeur'  =>1000 ,
                'prix'  => 913,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 2100,
                'largeur'  =>1000 ,
                'prix'  => 936,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 2200,
                'largeur'  =>1000 ,
                'prix'  => 959,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 2300,
                'largeur'  =>1000 ,
                'prix'  => 982,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 2400,
                'largeur'  =>1000 ,
                'prix'  => 1006,
            ],
            [
                'genre'    =>2 ,
 	 	 	    'type'    =>3 ,
                'couleur'    =>1 ,
                'hauteur'    => 2500,
                'largeur'  =>1000 ,
                'prix'  => 1029,
            ],
        /*Larg=1100*/
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 404,
            'largeur'  =>1100 ,
            'prix'  => 543,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>1100 ,
            'prix'  => 579,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1100 ,
            'prix'  => 603,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1100 ,
            'prix'  => 627,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1100 ,
            'prix'  => 650,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1100 ,
            'prix'  => 674,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1100 ,
            'prix'  => 697,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1100 ,
            'prix'  => 721,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1100 ,
            'prix'  => 745,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1100 ,
            'prix'  => 768,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1100 ,
            'prix'  => 792,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1100 ,
            'prix'  => 816,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1100 ,
            'prix'  => 839,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1100 ,
            'prix'  => 862,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1100 ,
            'prix'  => 886,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1100 ,
            'prix'  => 910,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1100 ,
            'prix'  =>933 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1100 ,
            'prix'  => 957,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1100 ,
            'prix'  => 981,//faute ?
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1100 ,
            'prix'  => 1004,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1100 ,
            'prix'  => 1028,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1100 ,
            'prix'  => 1051,
        ],

        /*larg=1200*/
        [
            'genre'    =>2 ,
 	 	 	'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>1200 ,
            'prix'  => 593,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1200 ,
            'prix'  => 617,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1200 ,
            'prix'  => 642,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1200 ,
            'prix'  => 666,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1200 ,
            'prix'  => 690,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1200 ,
            'prix'  => 714,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1200 ,
            'prix'  => 738,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1200 ,
            'prix'  => 761,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1200 ,
            'prix'  => 785,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1200 ,
            'prix'  => 809,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1200 ,
            'prix'  => 833,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1200 ,
            'prix'  => 857,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1200 ,
            'prix'  => 882,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1200 ,
            'prix'  => 906,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1200 ,
            'prix'  => 930,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1200 ,
            'prix'  => 954,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1200 ,
            'prix'  => 978,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1200 ,
            'prix'  => 1002,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1200 ,
            'prix'  => 1026,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1200 ,
            'prix'  => 1050,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1200 ,
            'prix'  => 1074,
        ],

        /*Larg=1300*/
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>1300 ,
            'prix'  => 607,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1300 ,
            'prix'  => 631,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1300 ,
            'prix'  => 656,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1300 ,
            'prix'  => 680,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1300 ,
            'prix'  => 705,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1300 ,
            'prix'  => 729,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1300 ,
            'prix'  => 754,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1300 ,
            'prix'  => 778,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1300 ,
            'prix'  => 803,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1300 ,
            'prix'  => 827,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1300 ,
            'prix'  => 852,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1300 ,
            'prix'  => 876,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1300 ,
            'prix'  => 901,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1300 ,
            'prix'  => 925,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1300 ,
            'prix'  => 950,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1300 ,
            'prix'  => 974,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1300 ,
            'prix'  => 999,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1300 ,
            'prix'  => 1023,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1300 ,
            'prix'  => 1047,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1300 ,
            'prix'  => 1072,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1300 ,
            'prix'  => 1074,
        ],
        /*larg=1400*/
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1400 ,
            'prix'  => 621,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1400 ,
            'prix'  => 646,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1400 ,
            'prix'  => 671,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1400 ,
            'prix'  => 696,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1400 ,
            'prix'  => 721,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1400 ,
            'prix'  => 746,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1400 ,
            'prix'  => 770,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1400 ,
            'prix'  => 795,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1400 ,
            'prix'  => 820,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1400 ,
            'prix'  => 845,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1400 ,
            'prix'  =>870 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1400 ,
            'prix'  => 895,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1400 ,
            'prix'  => 920,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1400 ,
            'prix'  => 945,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1400 ,
            'prix'  => 970,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1400 ,
            'prix'  => 994,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1400 ,
            'prix'  => 1019,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1400 ,
            'prix'  => 1044,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1400 ,
            'prix'  => 1069,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1400 ,
            'prix'  => 1094,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1400 ,
            'prix'  => 1096,
        ],
        /*larg=1500*/
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1500 ,
            'prix'  => 635,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1500 ,
            'prix'  => 660,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1500 ,
            'prix'  => 685,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1500 ,
            'prix'  => 711,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1500 ,
            'prix'  => 736,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1500 ,
            'prix'  => 761,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1500 ,
            'prix'  => 787,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1500 ,
            'prix'  => 812,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1500 ,
            'prix'  => 837,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1500 ,
            'prix'  => 862,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1500 ,
            'prix'  =>888 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1500 ,
            'prix'  => 913,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1500 ,
            'prix'  => 938,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1500 ,
            'prix'  => 964,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1500 ,
            'prix'  => 989,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1500 ,
            'prix'  => 1014,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1500 ,
            'prix'  => 1040,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1500 ,
            'prix'  => 1065,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1500 ,
            'prix'  => 1090,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1500 ,
            'prix'  => 1116,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1500 ,
            'prix'  => 1141,
        ],
        /*larg=1600*/
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1600 ,
            'prix'  => 649,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1600 ,
            'prix'  => 675,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1600 ,
            'prix'  => 700,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1600 ,
            'prix'  => 726,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1600 ,
            'prix'  => 752,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1600 ,
            'prix'  => 777,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1600 ,
            'prix'  => 803,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1600 ,
            'prix'  => 829,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1600 ,
            'prix'  => 855,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1600 ,
            'prix'  => 880,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1600 ,
            'prix'  =>906 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1600 ,
            'prix'  => 932,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1600 ,
            'prix'  => 958,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1600 ,
            'prix'  => 983,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1600 ,
            'prix'  => 1009,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1600 ,
            'prix'  => 1035,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1600 ,
            'prix'  => 1060,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1600 ,
            'prix'  => 1086,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1600 ,
            'prix'  => 1112,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1600 ,
            'prix'  => 1138,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1600 ,
            'prix'  => 1163,
        ],

        /*larg=1700
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1700 ,
            'prix'  => 342,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1700 ,
            'prix'  => 353,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1700 ,
            'prix'  => 362,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1700 ,
            'prix'  => 376,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1700 ,
            'prix'  => 394,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1700 ,
            'prix'  => 417,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1700 ,
            'prix'  => 437,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1700 ,
            'prix'  => 455,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1700 ,
            'prix'  => 474,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1700 ,
            'prix'  => 496,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1700 ,
            'prix'  =>514 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1700 ,
            'prix'  => 534,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1700 ,
            'prix'  => 556,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1700 ,
            'prix'  => 575,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1700 ,
            'prix'  => 605,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1700 ,
            'prix'  => 619,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1700 ,
            'prix'  => 639,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1700 ,
            'prix'  => 656,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1700 ,
            'prix'  => 690,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1700 ,
            'prix'  => 707,
        ],

        /*larg=1800
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1800 ,
            'prix'  => 349,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1800 ,
            'prix'  => 360,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1800 ,
            'prix'  => 369,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1700 ,
            'prix'  => 390,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1800 ,
            'prix'  => 406,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1800 ,
            'prix'  => 429,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1800 ,
            'prix'  => 448,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1800 ,
            'prix'  => 471,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1800 ,
            'prix'  => 488,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1800 ,
            'prix'  => 509,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1800 ,
            'prix'  =>530 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1800 ,
            'prix'  => 551,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1800 ,
            'prix'  => 575,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1800 ,
            'prix'  => 594,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1800 ,
            'prix'  => 619,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1800 ,
            'prix'  => 639,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1800 ,
            'prix'  => 656,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1800 ,
            'prix'  => 676,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1800 ,
            'prix'  => 707,
        ],/*
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1800 ,
            'prix'  => 784,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1800 ,
            'prix'  => 806,
        ],
*/
        /*larg=1900
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 600,
            'largeur'  =>1900 ,
            'prix'  => 366,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1900 ,
            'prix'  => 376,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1900 ,
            'prix'  => 403,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1900 ,
            'prix'  => 423,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1900 ,
            'prix'  => 448,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1900 ,
            'prix'  => 468,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1900 ,
            'prix'  => 488,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1900 ,
            'prix'  => 509,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1900 ,
            'prix'  => 530,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1900 ,
            'prix'  =>551 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1900 ,
            'prix'  => 572,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>1900 ,
            'prix'  => 597,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>1900 ,
            'prix'  => 615,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>1900 ,
            'prix'  => 642,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>1900 ,
            'prix'  => 659,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>1900 ,
            'prix'  => 649,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>1900 ,
            'prix'  => 699,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>1900 ,
            'prix'  => 730,
        ],/*
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2400,
            'largeur'  =>1900 ,
            'prix'  => 806,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2500,
            'largeur'  =>1900 ,
            'prix'  => 873,
        ],*/
        /*larg=2000
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>2000 ,
            'prix'  => 371,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2000 ,
            'prix'  => 387,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2000 ,
            'prix'  => 415,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2000 ,
            'prix'  => 432,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2000 ,
            'prix'  => 458,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2000 ,
            'prix'  => 478,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2000 ,
            'prix'  => 500,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2000 ,
            'prix'  => 519,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2000 ,
            'prix'  => 541,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2000 ,
            'prix'  =>562 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2000 ,
            'prix'  => 581,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2000 ,
            'prix'  => 609,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2000 ,
            'prix'  => 630,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2000 ,
            'prix'  => 656,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2000 ,
            'prix'  => 676,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>2000 ,
            'prix'  => 699,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2000 ,
            'prix'  => 717,
        ],/*
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2300,
            'largeur'  =>2000 ,
            'prix'  => 823,
        ],*/
        /*larg=2100
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>2100 ,
            'prix'  => 381,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2100 ,
            'prix'  => 394,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2100 ,
            'prix'  => 423,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2100 ,
            'prix'  => 441,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2100 ,
            'prix'  => 468,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2100 ,
            'prix'  => 488,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2100 ,
            'prix'  => 512,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2100 ,
            'prix'  => 530,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2100 ,
            'prix'  => 553,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2100 ,
            'prix'  =>575 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2100 ,
            'prix'  => 597,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2100 ,
            'prix'  => 622,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2100 ,
            'prix'  => 646,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2100 ,
            'prix'  => 676,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2100 ,
            'prix'  => 690,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2100,
            'largeur'  =>2100 ,
            'prix'  => 711,
        ],/*
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2200,
            'largeur'  =>2100 ,
            'prix'  => 806,
        ],*/
        /*larg=2200
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>2200 ,
            'prix'  => 389,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2200 ,
            'prix'  => 423,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2200 ,
            'prix'  => 429,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2200 ,
            'prix'  => 453,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2200 ,
            'prix'  => 478,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2200 ,
            'prix'  => 500,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2200 ,
            'prix'  => 523,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2200 ,
            'prix'  => 541,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2200 ,
            'prix'  => 567,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2200 ,
            'prix'  => 591,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2200 ,
            'prix'  => 612,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2200 ,
            'prix'  => 639,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2200 ,
            'prix'  => 659,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2200 ,
            'prix'  => 690,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2200 ,
            'prix'  => 707,
        ],
        /*larg=2300
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>2300 ,
            'prix'  => 537,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2300 ,
            'prix'  => 436,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2300 ,
            'prix'  => 441,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2300 ,
            'prix'  => 461,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2300 ,
            'prix'  => 488,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2300 ,
            'prix'  => 512,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2300 ,
            'prix'  => 534,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2300 ,
            'prix'  => 556,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2300 ,
            'prix'  => 579,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2300 ,
            'prix'  => 605,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2300 ,
            'prix'  => 622,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2300 ,
            'prix'  => 656,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2300 ,
            'prix'  => 679,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2200 ,
            'prix'  => 705,
        ],/*
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2300 ,
            'prix'  => 802,
        ],*/
        /*larg=2400
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2400 ,
            'prix'  => 554,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2400 ,
            'prix'  => 561,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2400 ,
            'prix'  => 562,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2400 ,
            'prix'  => 589,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2400 ,
            'prix'  => 611,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2400 ,
            'prix'  => 630,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2400 ,
            'prix'  => 653,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2400 ,
            'prix'  => 678,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2400 ,
            'prix'  =>698 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2400 ,
            'prix'  => 721,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2400 ,
            'prix'  => 751,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2400 ,
            'prix'  => 773,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1900,
            'largeur'  =>2400 ,
            'prix'  => 851,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 2000,
            'largeur'  =>2400 ,
            'prix'  => 870,
        ],

        /*larg=2500
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2500 ,
            'prix'  => 571,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2500 ,
            'prix'  => 574,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2500 ,
            'prix'  => 573,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2500 ,
            'prix'  => 601,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2500 ,
            'prix'  => 622,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2500 ,
            'prix'  => 643,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2500 ,
            'prix'  => 665,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2500 ,
            'prix'  => 689,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2500 ,
            'prix'  =>713 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2500 ,
            'prix'  => 736,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2500 ,
            'prix'  => 752,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2500 ,
            'prix'  => 775,
        ],
        /*larg=2600
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2600 ,
            'prix'  => 585,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2600 ,
            'prix'  => 587,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2600 ,
            'prix'  => 584,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2600 ,
            'prix'  => 608,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2600 ,
            'prix'  => 632,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2600 ,
            'prix'  => 654,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2600 ,
            'prix'  => 777,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2600 ,
            'prix'  => 700,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2600 ,
            'prix'  =>725 ,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2600 ,
            'prix'  => 747,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1700,
            'largeur'  =>2600 ,
            'prix'  => 754,
        ],
        [
            'genre'    =>2 ,
 	 	 	 'type'    =>3 ,
            'couleur'    =>1 ,
            'hauteur'    => 1800,
            'largeur'  =>2600 ,
            'prix'  => 776,
        ],
*/
            ];

            Modele::insert($modeles);

        }


    }
}
