<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Modele;
use App\Models\Seeders;

class Modeles12PVCSeeder extends Seeder  //Coulissant 2V  PVC
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $seeder = Modele::where('type',12)->count();
        //Coulissant 2V PVC
        //Check if the seeder exist in the DB
        if ($seeder==0) {
            $modeles =
            [

            /*larg= 1000*/
            [
                'genre'    =>1 ,
                'type'    =>12 ,
                'couleur'    =>1 ,
                'hauteur'    => 500,
                'largeur'  =>1000 ,
                'prix'  => 471,
            ],
            [
                'genre'    =>1 ,
                'type'    =>12 ,
                'couleur'    => 1,
                'hauteur'    =>600 ,
                'largeur'  =>1000 ,
                'prix'  => 481,
            ],
            [
                'genre'    =>1 ,
                'type'    =>12 ,
                'couleur'    => 1,
                'hauteur'    => 700,
                'largeur'  =>1000 ,
                'prix'  => 499,
            ],
            [
                'genre'    =>1 ,
                'type'    =>12 ,
                'couleur'    => 1,
                'hauteur'    => 800,
                'largeur'  =>1000 ,
                'prix'  => 515,
            ],
            [
                'genre'    =>1 ,
                'type'    =>12 ,
                'couleur'    => 1,
                'hauteur'    => 900,
                'largeur'  =>1000 ,
                'prix'  => 531,
            ],
            [
                'genre'    =>1 ,
                'type'    =>12 ,
                'couleur'    =>1 ,
                'hauteur'    => 1000,
                'largeur'  =>1000 ,
                'prix'  => 547,
            ],
            [
                'genre'    =>1 ,
                'type'    =>12 ,
                'couleur'    =>1 ,
                'hauteur'    =>1100 ,
                'largeur'  =>1000 ,
                'prix'  => 564,
            ],
            [
                'genre'    =>1 ,
                'type'    =>12 ,
                'couleur'    =>1 ,
                'hauteur'    => 1200,
                'largeur'  =>1000 ,
                'prix'  => 581,
            ],
            [
                'genre'    =>1 ,
                'type'    =>12 ,
                'couleur'    =>1 ,
                'hauteur'    => 1300,
                'largeur'  =>1000 ,
                'prix'  => 597,
            ],
            [
                'genre'    =>1 ,
                'type'    =>12 ,
                'couleur'    =>1 ,
                'hauteur'    => 1400,
                'largeur'  =>1000 ,
                'prix'  => 613,
            ],
            [
                'genre'    =>1 ,
                'type'    =>12 ,
                'couleur'    =>1 ,
                'hauteur'    => 1500,
                'largeur'  =>1000 ,
                'prix'  => 628 ,
            ],
            [
                'genre'    =>1 ,
                'type'    =>12 ,
                'couleur'    =>1 ,
                'hauteur'    => 1600,
                'largeur'  =>1000 ,
                'prix'  => 647 ,
            ],
            /*larg= 1100*/
            [
                'genre'    =>1 ,
                'type'    =>12 ,
                'couleur'    =>1 ,
                'hauteur'    => 500,
                'largeur'  =>1100 ,
                'prix'  => 478,
            ],
            [
                'genre'    =>1 ,
                'type'    =>12 ,
                'couleur'    => 1,
                'hauteur'    =>600 ,
                'largeur'  =>1100 ,
                'prix'  => 492,
            ],
            [
                'genre'    =>1 ,
                'type'    =>12 ,
                'couleur'    => 1,
                'hauteur'    => 700,
                'largeur'  =>1100 ,
                'prix'  => 508,
            ],
            [
                'genre'    =>1 ,
                'type'    =>12 ,
                'couleur'    => 1,
                'hauteur'    => 800,
                'largeur'  =>1100 ,
                'prix'  => 527,
            ],
            [
                'genre'    =>1 ,
                'type'    =>12 ,
                'couleur'    => 1,
                'hauteur'    => 900,
                'largeur'  =>1100 ,
                'prix'  => 541,
            ],
            [
                'genre'    =>1 ,
                'type'    =>12 ,
                'couleur'    =>1 ,
                'hauteur'    => 1000,
                'largeur'  =>1100 ,
                'prix'  => 560,
            ],
            [
                'genre'    =>1 ,
                'type'    =>12 ,
                'couleur'    =>1 ,
                'hauteur'    =>1100 ,
                'largeur'  =>1100 ,
                'prix'  => 577,
            ],
            [
                'genre'    =>1 ,
                'type'    =>12 ,
                'couleur'    =>1 ,
                'hauteur'    => 1200,
                'largeur'  =>1100 ,
                'prix'  => 592,
            ],
            [
                'genre'    =>1 ,
                'type'    =>12 ,
                'couleur'    =>1 ,
                'hauteur'    => 1300,
                'largeur'  =>1100 ,
                'prix'  => 610,
            ],
            [
                'genre'    =>1 ,
                'type'    =>12 ,
                'couleur'    =>1 ,
                'hauteur'    => 1400,
                'largeur'  =>1100 ,
                'prix'  => 626,
            ],
            [
                'genre'    =>1 ,
                'type'    =>12 ,
                'couleur'    =>1 ,
                'hauteur'    => 1500,
                'largeur'  =>1100 ,
                'prix'  => 644 ,
            ],
            [
                'genre'    =>1 ,
                'type'    =>12 ,
                'couleur'    =>1 ,
                'hauteur'    => 1600,
                'largeur'  =>1100 ,
                'prix'  => 660 ,
            ],
            /*larg= 1200*/
				[
                    'genre'    =>1 ,
					'type'    =>12 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 500,
                    'largeur'  =>1200 ,
                    'prix'  => 483,
				],
				[
                    'genre'    =>1 ,
					'type'    =>12 ,
                    'couleur'    => 1,
                    'hauteur'    =>600 ,
                    'largeur'  =>1200 ,
                    'prix'  => 502,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>12 ,
                    'couleur'    => 1,
                    'hauteur'    => 700,
                    'largeur'  =>1200 ,
                    'prix'  => 513,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>12 ,
                    'couleur'    => 1,
                    'hauteur'    => 800,
                    'largeur'  =>1200 ,
                    'prix'  => 532,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>12 ,
                    'couleur'    => 1,
                    'hauteur'    => 900,
                    'largeur'  =>1200 ,
                    'prix'  => 550,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>12 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1000,
                    'largeur'  =>1200 ,
                    'prix'  => 659,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>12 ,
                    'couleur'    =>1 ,
                    'hauteur'    =>1100 ,
                    'largeur'  =>1200 ,
                    'prix'  => 589,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>12 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1200,
                    'largeur'  =>1200 ,
                    'prix'  => 606,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>12 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1300,
                    'largeur'  =>1200 ,
                    'prix'  => 622,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>12 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1400,
                    'largeur'  =>1200 ,
                    'prix'  => 642,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>12 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1500,
                    'largeur'  =>1200 ,
                    'prix'  => 656 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>12 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1600,
                    'largeur'  =>1200 ,
                    'prix'  => 676 ,
                ],

                /*larg= 1300*/
				[
                    'genre'    =>1 ,
					'type'    =>12 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 500,
                    'largeur'  =>1300 ,
                    'prix'  => 492,
				],
				[
                    'genre'    =>1 ,
					'type'    =>12 ,
                    'couleur'    => 1,
                    'hauteur'    =>600 ,
                    'largeur'  =>1300 ,
                    'prix'  => 513,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>12 ,
                    'couleur'    => 1,
                    'hauteur'    => 700,
                    'largeur'  =>1300 ,
                    'prix'  => 527,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>12 ,
                    'couleur'    => 1,
                    'hauteur'    => 800,
                    'largeur'  =>1300 ,
                    'prix'  => 546,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>12 ,
                    'couleur'    => 1,
                    'hauteur'    => 900,
                    'largeur'  =>1300 ,
                    'prix'  => 564,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>12 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1000,
                    'largeur'  =>1300 ,
                    'prix'  => 583,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>12 ,
                    'couleur'    =>1 ,
                    'hauteur'    =>1100 ,
                    'largeur'  =>1300 ,
                    'prix'  => 602,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>12 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1200,
                    'largeur'  =>1300 ,
                    'prix'  => 617,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>12 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1300,
                    'largeur'  =>1300 ,
                    'prix'  => 640,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>12 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1400,
                    'largeur'  =>1300 ,
                    'prix'  => 652,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>12 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1500,
                    'largeur'  =>1300 ,
                    'prix'  => 674 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>12 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1600,
                    'largeur'  =>1300 ,
                    'prix'  => 688 ,
                ],

            /*larg= 1400*/
				[
                    'genre'    =>1 ,
					'type'    =>12 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 500,
                    'largeur'  =>1400 ,
                    'prix'  => 499,
				],
				[
                    'genre'    =>1 ,
					'type'    =>12 ,
                    'couleur'    => 1,
                    'hauteur'    =>600 ,
                    'largeur'  =>1400 ,
                    'prix'  => 526,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>12 ,
                    'couleur'    => 1,
                    'hauteur'    => 700,
                    'largeur'  =>1400 ,
                    'prix'  => 547,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>12 ,
                    'couleur'    => 1,
                    'hauteur'    => 800,
                    'largeur'  =>1400 ,
                    'prix'  => 564,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>12 ,
                    'couleur'    => 1,
                    'hauteur'    => 900,
                    'largeur'  =>1400 ,
                    'prix'  => 580,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>12 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1000,
                    'largeur'  =>1400 ,
                    'prix'  => 597,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>12 ,
                    'couleur'    =>1 ,
                    'hauteur'    =>1100 ,
                    'largeur'  =>1400 ,
                    'prix'  => 613,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>12 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1200,
                    'largeur'  =>1400 ,
                    'prix'  => 631,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>12 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1300,
                    'largeur'  =>1400 ,
                    'prix'  => 649,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>12 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1400,
                    'largeur'  =>1400 ,
                    'prix'  => 666,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>12 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1500,
                    'largeur'  =>1400 ,
                    'prix'  => 685 ,
                ],
				[
                    'genre'    =>1 ,
					'type'    =>12 ,
                    'couleur'    =>1 ,
                    'hauteur'    => 1600,
                    'largeur'  =>1400 ,
                    'prix'  => 701 ,
                ],


            /*Larg= 1500*/
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>12 ,
                'couleur'    =>1 ,
                'hauteur'    => 500,
                'largeur'  =>1500 ,
                'prix'  => 502,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>12 ,
                'couleur'    => 1,
                'hauteur'    =>600 ,
                'largeur'  =>1500 ,
                'prix'  => 534,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>12 ,
                'couleur'    => 1,
                'hauteur'    => 700,
                'largeur'  =>1500 ,
                'prix'  => 557,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>12 ,
                'couleur'    => 1,
                'hauteur'    => 800,
                'largeur'  =>1500 ,
                'prix'  => 569,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>12 ,
                'couleur'    => 1,
                'hauteur'    => 900,
                'largeur'  =>1500 ,
                'prix'  => 590,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>12 ,
                'couleur'    =>1 ,
                'hauteur'    => 1000,
                'largeur'  =>1500 ,
                'prix'  => 610,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>12 ,
                'couleur'    =>1 ,
                'hauteur'    =>1100 ,
                'largeur'  =>1500 ,
                'prix'  => 624,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>12 ,
                'couleur'    =>1 ,
                'hauteur'    => 1200,
                'largeur'  =>1500 ,
                'prix'  => 644,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>12 ,
                'couleur'    =>1 ,
                'hauteur'    => 1300,
                'largeur'  =>1500 ,
                'prix'  => 662,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>12 ,
                'couleur'    =>1 ,
                'hauteur'    => 1400,
                'largeur'  =>1500 ,
                'prix'  => 680,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>12 ,
                'couleur'    =>1 ,
                'hauteur'    => 1500,
                'largeur'  =>1500 ,
                'prix'  => 697,
            ],
            [
                'genre'    =>1 ,
 	 	 	    'type'    =>12 ,
                'couleur'    =>1 ,
                'hauteur'    => 1600,
                'largeur'  =>1500 ,
                'prix'  =>717 ,
            ],

        /*Larg=1600*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>1600 ,
            'prix'  => 509,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1600 ,
            'prix'  => 546,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1600 ,
            'prix'  => 563,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1600 ,
            'prix'  => 580,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1600 ,
            'prix'  => 599,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1600 ,
            'prix'  => 617,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1600 ,
            'prix'  => 640,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1600 ,
            'prix'  => 656,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1600 ,
            'prix'  => 676,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1600 ,
            'prix'  => 694,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1600 ,
            'prix'  => 711,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1600 ,
            'prix'  => 731,
        ],

        /*larg=1700*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>1700 ,
            'prix'  => 517,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1700 ,
            'prix'  => 554,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1700 ,
            'prix'  => 575,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1700 ,
            'prix'  => 590,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1700 ,
            'prix'  => 613,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1700 ,
            'prix'  => 631,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1700 ,
            'prix'  => 649,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1700 ,
            'prix'  => 670,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1700 ,
            'prix'  => 688,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1700 ,
            'prix'  => 709,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1700 ,
            'prix'  => 728,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1700 ,
            'prix'  => 747,
        ],

        /*Larg=1800*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 500,
            'largeur'  =>1800 ,
            'prix'  => 523,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1800 ,
            'prix'  => 565,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1800 ,
            'prix'  => 585,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1800 ,
            'prix'  => 602,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1800 ,
            'prix'  => 624,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1800 ,
            'prix'  => 644,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1800 ,
            'prix'  => 662,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1800 ,
            'prix'  => 682,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1800 ,
            'prix'  => 701,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1800 ,
            'prix'  => 719,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1800 ,
            'prix'  => 739,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1800 ,
            'prix'  => 760,
        ],

        /*larg=1900*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>1900 ,
            'prix'  => 530,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>1900 ,
            'prix'  => 577,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>1900 ,
            'prix'  => 596,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1900 ,
            'prix'  => 610,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>1900 ,
            'prix'  => 631,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>1900 ,
            'prix'  => 652,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>1900 ,
            'prix'  => 676,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>1900 ,
            'prix'  => 694,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>1900 ,
            'prix'  => 713,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>1900 ,
            'prix'  => 733,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>1900 ,
            'prix'  =>753 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>1900 ,
            'prix'  => 770,
        ],

        /*larg=2000*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>2000 ,
            'prix'  => 535,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>2000 ,
            'prix'  => 589,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2000 ,
            'prix'  => 610,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2000 ,
            'prix'  => 626,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2000 ,
            'prix'  => 648,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2000 ,
            'prix'  => 666,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2000 ,
            'prix'  => 685,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2000 ,
            'prix'  => 709,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2000 ,
            'prix'  => 728,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2000 ,
            'prix'  => 747,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2000 ,
            'prix'  => 765,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2000 ,
            'prix'  => 790,
        ],

        /*larg=2100*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>2100 ,
            'prix'  => 541,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 600,
            'largeur'  =>2100 ,
            'prix'  => 602,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2100 ,
            'prix'  => 622,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2100 ,
            'prix'  => 642,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 900,
            'largeur'  =>2100 ,
            'prix'  => 660,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    =>1000 ,
            'largeur'  =>2100 ,
            'prix'  => 680,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2100 ,
            'prix'  => 697,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2100 ,
            'prix'  => 719,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2100 ,
            'prix'  => 739,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2100 ,
            'prix'  => 760,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2100 ,
            'prix'  =>782 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2100 ,
            'prix'  => 799,
        ],
        /*larg=2200*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>2200 ,
            'prix'  => 549,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 600,
            'largeur'  =>2200 ,
            'prix'  => 613,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2200 ,
            'prix'  => 627,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2200 ,
            'prix'  => 649,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2200 ,
            'prix'  => 674,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2200 ,
            'prix'  => 691,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2200 ,
            'prix'  => 711,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2200 ,
            'prix'  => 733,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2200 ,
            'prix'  => 753,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2200 ,
            'prix'  => 773,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2200 ,
            'prix'  =>795 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2200 ,
            'prix'  => 815,
        ],

        /*larg=2300*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>2300 ,
            'prix'  => 557,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>2300 ,
            'prix'  => 617,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2300 ,
            'prix'  => 640,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2300 ,
            'prix'  => 656,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2300 ,
            'prix'  => 680,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2300 ,
            'prix'  => 701,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2300 ,
            'prix'  => 724,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2300 ,
            'prix'  => 747,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2300 ,
            'prix'  => 765,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2300 ,
            'prix'  => 790,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2300 ,
            'prix'  =>808 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2300 ,
            'prix'  => 829,
        ],

        /*larg=2400*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>2400 ,
            'prix'  => 564,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    =>600 ,
            'largeur'  =>2400 ,
            'prix'  => 624,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2400 ,
            'prix'  => 648,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2400 ,
            'prix'  => 670,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2400 ,
            'prix'  => 691,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2400 ,
            'prix'  => 713,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2400 ,
            'prix'  => 735,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2400 ,
            'prix'  => 756,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2400 ,
            'prix'  => 778,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2400 ,
            'prix'  => 799,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2400 ,
            'prix'  =>823 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2400 ,
            'prix'  => 841,
        ],
        /*larg=2500*/

        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    =>500 ,
            'largeur'  =>2500 ,
            'prix'  => 584,//
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 600,
            'largeur'  =>2500 ,
            'prix'  => 640,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2500 ,
            'prix'  => 660,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2500 ,
            'prix'  => 682,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 900,
            'largeur'  =>2500 ,
            'prix'  => 706,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    =>1000 ,
            'largeur'  =>2500 ,
            'prix'  => 728,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1100,
            'largeur'  =>2500 ,
            'prix'  => 750,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2500 ,
            'prix'  => 768,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2500 ,
            'prix'  => 791,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2500 ,
            'prix'  => 814,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2500 ,
            'prix'  => 837,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2500 ,
            'prix'  => 858,
        ],

        /*larg=2600*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 500,
            'largeur'  =>2600 ,
            'prix'  => 590,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 600,
            'largeur'  =>2600 ,
            'prix'  => 648,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2600 ,
            'prix'  => 670,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2600 ,
            'prix'  => 691,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 900,
            'largeur'  =>2600 ,
            'prix'  => 713,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    =>1000 ,
            'largeur'  =>2600 ,
            'prix'  => 735,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2600 ,
            'prix'  => 760,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2600 ,
            'prix'  => 782,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2600 ,
            'prix'  => 803,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2600 ,
            'prix'  => 827,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2600 ,
            'prix'  => 848,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2600 ,
            'prix'  => 871,
        ],

        /*larg=2700*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 500,
            'largeur'  =>2700 ,
            'prix'  => 598,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 600,
            'largeur'  =>2700 ,
            'prix'  => 660,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2700 ,
            'prix'  => 682,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2700 ,
            'prix'  => 706,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2700 ,
            'prix'  => 728,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2700 ,
            'prix'  => 750,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2700 ,
            'prix'  => 770,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2700 ,
            'prix'  => 795,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2700 ,
            'prix'  => 815,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2700 ,
            'prix'  => 840,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2700 ,
            'prix'  =>862 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2700 ,
            'prix'  => 883,
        ],

        /*larg=2800*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 500,
            'largeur'  =>2800 ,
            'prix'  => 606,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 600,
            'largeur'  =>2800 ,
            'prix'  => 674,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2800 ,
            'prix'  => 694,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>1700 ,
            'prix'  => 717,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2800 ,
            'prix'  => 739,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2800 ,
            'prix'  => 763,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2800 ,
            'prix'  => 785,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2800 ,
            'prix'  => 808,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2800 ,
            'prix'  => 829,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2800 ,
            'prix'  => 856,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2800 ,
            'prix'  =>876 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2800 ,
            'prix'  => 899,
        ],

        /*larg=2900*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 500,
            'largeur'  =>2900 ,
            'prix'  => 613,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 600,
            'largeur'  =>2900 ,
            'prix'  => 681,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>2900 ,
            'prix'  => 704,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>2900 ,
            'prix'  => 728,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>2900 ,
            'prix'  => 753,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>2900 ,
            'prix'  => 773,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>2900 ,
            'prix'  => 796,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>2900 ,
            'prix'  => 821,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>2900 ,
            'prix'  => 841,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>2900 ,
            'prix'  => 867,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>2900 ,
            'prix'  =>892 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>2900 ,
            'prix'  => 912,
        ],

        /*larg=3000*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 500,
            'largeur'  =>3000 ,
            'prix'  => 623,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 600,
            'largeur'  =>3000 ,
            'prix'  => 690,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>3000 ,
            'prix'  => 714,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>3000 ,
            'prix'  => 733,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>3000 ,
            'prix'  => 760,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>3000 ,
            'prix'  => 785,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>3000 ,
            'prix'  => 810,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>3000 ,
            'prix'  => 833,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>3000 ,
            'prix'  => 858,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>3000 ,
            'prix'  => 879,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>3000 ,
            'prix'  =>903 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>3000 ,
            'prix'  => 929,
        ],
        /*larg=3100*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 500,
            'largeur'  =>3100 ,
            'prix'  => 628,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 600,
            'largeur'  =>3100 ,
            'prix'  => 702,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>3100 ,
            'prix'  => 726,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>3100 ,
            'prix'  => 747,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>3100 ,
            'prix'  => 770,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>3100 ,
            'prix'  => 796,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>3100 ,
            'prix'  => 823,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>3100 ,
            'prix'  => 845,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>3100 ,
            'prix'  => 871,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>3100 ,
            'prix'  => 895,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>3100 ,
            'prix'  =>919 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>3100 ,
            'prix'  => 942,
        ],
        /*larg=3200*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 500,
            'largeur'  =>3200 ,
            'prix'  => 639,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 600,
            'largeur'  =>3200 ,
            'prix'  => 712,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>3200 ,
            'prix'  => 735,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>3200 ,
            'prix'  => 765,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>3200 ,
            'prix'  => 790,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>3200 ,
            'prix'  => 810,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>3200 ,
            'prix'  => 833,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>3200 ,
            'prix'  => 858,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>3200 ,
            'prix'  => 883,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>3200 ,
            'prix'  => 906,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>3200 ,
            'prix'  =>933 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>3200 ,
            'prix'  => 955,
        ],

        /*larg=3300*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 500,
            'largeur'  =>3300 ,
            'prix'  => 645,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 600,
            'largeur'  =>3300 ,
            'prix'  => 724,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>3300 ,
            'prix'  => 747,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>3300 ,
            'prix'  => 770,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>3300 ,
            'prix'  => 799,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>3300 ,
            'prix'  => 823,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>3300 ,
            'prix'  =>845 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>3300 ,
            'prix'  => 871 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>3300 ,
            'prix'  => 897 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>3300 ,
            'prix'  => 919 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>3300 ,
            'prix'  =>943 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>3300 ,
            'prix'  => 970,
        ],

        /*larg=3400*/
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 500,
            'largeur'  =>3400 ,
            'prix'  => 651,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 600,
            'largeur'  =>3400 ,
            'prix'  => 733,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>3400 ,
            'prix'  => 758,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>3400 ,
            'prix'  => 782,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>3400 ,
            'prix'  => 808,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>3400 ,
            'prix'  => 833,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>3400 ,
            'prix'  => 858,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>3400 ,
            'prix'  => 883,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>3400 ,
            'prix'  => 908,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>3400 ,
            'prix'  => 936,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>3400 ,
            'prix'  =>958 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>3400 ,
            'prix'  =>983 ,
        ],
         /*larg=3500*/
         [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 500,
            'largeur'  =>3500 ,
            'prix'  => 653,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 600,
            'largeur'  =>3500 ,
            'prix'  => 744,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 700,
            'largeur'  =>3500 ,
            'prix'  => 768,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 800,
            'largeur'  =>3500 ,
            'prix'  => 795,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    => 1,
            'hauteur'    => 900,
            'largeur'  =>3500 ,
            'prix'  => 821,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1000,
            'largeur'  =>3500 ,
            'prix'  => 845,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    =>1100 ,
            'largeur'  =>3500 ,
            'prix'  => 871,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1200,
            'largeur'  =>3500 ,
            'prix'  => 897,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1300,
            'largeur'  =>3500 ,
            'prix'  => 923,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1400,
            'largeur'  =>3500 ,
            'prix'  => 947,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1500,
            'largeur'  =>3500 ,
            'prix'  =>974 ,
        ],
        [
            'genre'    =>1 ,
 	 	 	 'type'    =>12 ,
            'couleur'    =>1 ,
            'hauteur'    => 1600,
            'largeur'  =>3500 ,
            'prix'  =>997 ,
        ],

    ];

            Modele::insert($modeles);

        }


    }
}
